### ISSUE TITLE
Kovri: upgrade ARMv8 box disk space

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#1]
Effects https://github.com/monero-project/kovri/pull/431, build log [here](https://build.getmonero.org/builders/kovri-all-debian-arm8/builds/0/steps/compile/logs/stdio). A fix is currently in-progress, ticketing for housekeeping.

**Comment by anonimal** [comment]
Build [success](https://build.getmonero.org/builders/kovri-all-debian-arm8/builds/5). Thanks @danrmiller.

**Comment by anonimal** [comment]
@danrmiller the disk is back at 100% but buildbot builds don't appear to be effected. I had to `make clean` to make some room though I can't do any build/testing of my own on the machine.

**Comment by danrmiller** [comment]
All set, host added storage and we moved some things around.

**Comment by anonimal** [comment]
Thank you very much @danrmiller

**Comment by anonimal** [comment]
ARMv8 is out of space again https://build.getmonero.org/builders/kovri-all-debian-arm8/builds/163/steps/compile/logs/stdio.

**Comment by danrmiller** [comment]
Cleared /tmp. Feel free to re-run any failed builds, or let me know which ones to rebuild. I'm not going to do it otherwise since the builds take so long.

**Comment by anonimal** [comment]
Ok, thanks.
