### ISSUE TITLE
User List for Label-bot access on monero repo

### ISSUE THREAD

**Issue by medusadigital** [monero-project/meta#100]
create github User List for Label-bot access on **monero** repo

**Comment by fluffypony** [comment]
moneromooo, gingeropolous, pigeons, and then those from the monero-core user list

**Comment by moneromooo-monero** [comment]
moneromooo-monero please, not moneromooo (that last one's mine, but from a less secure VM which doesn't have the monero signing keys).

**Comment by danrmiller** [comment]
What labels should be supported?

**Comment by danrmiller** [comment]
I am adding @hyc https://github.com/hyc

**Comment by selsta** [comment]
Label bot has been replaced by Github org features. Ask core team / luigi for access.
