### ISSUE TITLE
User List for Label-bot access on monero-core repo

### ISSUE THREAD

**Issue by medusadigital** [monero-project/meta#101]
Create Github User List for Label-bot access on **monero-core** repo

+Task

**Comment by fluffypony** [comment]
medusa, jaqueee, dEBRUYNE, and people from the Monero repo?

**Comment by medusadigital** [comment]
fits for me. 

the profiles: 

https://github.com/medusadigital
https://github.com/Jaqueeee
https://github.com/debruyne-1

**Comment by issue-helper** [comment]
The bot is now active for the monero-core repo.

**Comment by medusadigital** [comment]
ok, the labels are: 

+bug
+feature
+enhancement
+high prio
+easy
+help wanted


the Label that close the issue automatically are:

+resolved
+duplicate
+wontfix

**Comment by danrmiller** [comment]
Don't use the + or - modifiers like that on lines by themselves unless you actually want those labels added or removed from the issue.

**Comment by danrmiller** [comment]
-bug
-resolved
-duplicate
-enhancement
-feature
-help wanted
-wontfix

**Comment by skftn** [comment]
skftn

**Comment by sanecito** [comment]
+resolved

**Comment by selsta** [comment]
Label bot has been replaced by Github org features. Ask core team / luigi for access.
