### ISSUE TITLE
User List for Label-bot access on meta repo

### ISSUE THREAD

**Issue by medusadigital** [monero-project/meta#102]
Create Github User List for Label-bot access on **meta** repo

**Comment by fluffypony** [comment]
I'd suggest anyone who organises meetings (sgp, anonimal), as well as community members like dEBRUYNE

**Comment by danrmiller** [comment]
OK, I'll add github usernames danrmiller, medusadigital, anonimal, SamsungGalaxyPlayer, and dEBRUYNE-1 to the access list for the meta repository.

**Comment by selsta** [comment]
Label bot has been replaced by Github org features. Ask core team / luigi for access.
