### ISSUE TITLE
Monero Community Workgroup Meeting: Saturday 22nd June 15:00UTC

### ISSUE THREAD

**Issue by plowsof** [monero-project/meta#1027]
Location: [Libera.chat, #monero-community](https://libera.chat/) | [Matrix](https://matrix.to/#/#monero-community:monero.social?via=matrix.org&via=monero.social)

[Instructions for joining the monero.social Matrix server.](https://www.getmonero.org/resources/user-guides/join-monero-matrix.html)

Time
15:00 UTC [Check your timezone](https://www.timeanddate.com/worldclock/converter.html)

Moderator: plowsof

Please reach out in advance of the meeting if you would like to propose an agenda item.

Proposed Meeting Items:

1. Introduction
2. Greetings
3. Community highlights    
News: [Monero Observer](https://www.monero.observer/) - [Revuo Monero](https://revuo-xmr.com/) - [Monero Moon](https://www.themoneromoon.com/)    
4. [CCS updates](https://ccs.getmonero.org/)   pending payouts: ~~[j-berman](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/453#note_24704) 125.3~~ / ~~[escapethe3ra](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/446#note_24832) 16~~ / ~~[selsta](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/452#note_24834) 53~~ / [plowsof](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/440#note_24837) 53.38 / ~~[anhdres](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/346#note_24804) 30 or 41~~ / ~~[hinto](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/456#note_24880) 52.8~~ / ~~[v1do](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/420#note_24946) 17.4~~ / ~~[jeffro256](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/436#note_24954) 57~~ / ~~[boog900](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/431#note_24971) 162~~ / ~~[vthor](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/465#note_25012) 5.38~~
  a. [Seraphis General Paper Review](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/441)    
  b. [New Monero Website](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/450)    
  c. [How to mine Monero guide](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/451)    
  d. [I2P SAMv3](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/454)    
  e. [ofrnxmr feat. BasicSwapDEX - take over the world pt 2](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/457)    
  f. [Monero Poker Infrastructure Project](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/461)    
  g. [Mobazha with Monero in Privacy Ecommerce](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/463)    
  h. [Development of New CCS Proposal Platform](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/464)    
  i. [Revuo Monero maintenance (2024 Q3)](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/466)    
  j. [Jeffro256 Full-time 2024 Q3](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/467)    
5. Workgroup reports    
  a. Dev workgroup
  b. Localization workgroup
  c. Outreach workgroup
  d. Events workgroup - [MoneroKon 2024](https://github.com/MoneroKon/)
  e. Website workgroup
  f. Policy workgroup
  g. Research workgroup
  h. [Seraphis Migration workgroup](https://github.com/seraphis-migration)
6. Open ideas time    
7. Confirm next meeting date/time    

[Previous meeting including logs](https://github.com/monero-project/meta/issues/1018)    

Meeting logs will be posted here afterwards.

**Comment by rottenwheel** [comment]
Remember to take Monero Standard off the list of newsletters.

**Comment by rottenwheel** [comment]
When log? Do better!

**Comment by plowsof** [comment]
Recanmann has fixed the monerologs repo. Soon(tm) another instance will be online

**Comment by plowsof** [comment]
Logs 
> __< plowsof >__ Last minute meeting in 30 mins for those around https://github.com/monero-project/meta/issues/1027     

> __< p​lowsof:matrix.org >__ meeting in 10 mins~ https://github.com/monero-project/meta/issues/1027     

> __< f​engzie:monero.social >__ how do join?     

> __< f​engzie:monero.social >__ use the camera icon in the group?     

> __< plowsof >__ Meeting time https://github.com/monero-project/meta/issues/1027     

> __< plowsof >__ meetings here are text only. other community events (e.g. Monerotopia) take place via audio/video on youtube      

> __< r​ottenwheel:kernal.eu >__ 👋 Hola.     

> __< p​arasew:matrix.org >__ hello!     

> __< plowsof >__ greetings and hello, i have not been able to prepare for this meeting (as showcased by the last minute announcement, apologies)      

> __< r​ucknium:monero.social >__ Hi     

> __< plowsof >__ stressnet had its 'official' launch at 15:00utc 19th June , that was fun, the stressnet team have accomplished alot      

> __< plowsof >__ what is next for Stressnet? it has already resulted in pull requests to improve monero-core https://github.com/spackle-xmr/monero/releases     

> __< r​ottenwheel:kernal.eu >__ Unacceptable. Step down or do better! plowsof     

> __< plowsof >__ i noticed a screenshot of a blockweight graph appearing in this tweet from untraceable https://nitter.poast.org/DontTraceMeBruh/status/1803882854662778933     

> __< r​ucknium:monero.social >__ The stressnet monitor is here: https://monitor.stressnet.net/ . Usually it is accurate and up to date. Sometimes it goes down     

> __< m​ichael:monero.social >__ Hello.     

> __< r​ucknium:monero.social >__ The blockchain explorer isn't working now since it's hard on the node: https://explorer.stressnet.net/     

> __< plowsof >__ awesome page Rucknium     

> __< plowsof >__ typo there on the explorer url?     

> __< plowsof >__ or is it temp offline      

> __< plowsof >__ ignore, thanks      

> __< r​ucknium:monero.social >__ I just said it's offline lol     

> __< plowsof >__ monkey see link, monkey click     

> __< p​reland:monero.social >__ Was it ever online? I had tried using it when the network was first launched but it still sent a 502     

> __< plowsof >__ i could host it on node3 (which is running a stressnet node already) is the limitation, ram?     

> __< r​ucknium:monero.social >__ The monitor is GPL-2 open source and should work OK on mainnet nodes too: https://github.com/Rucknium/monerod-monitor     

> __< r​ucknium:monero.social >__ It's RAM and just the RPC calls from the explorer slow down the node. And the RPC lock is something that developers are trying to solve     

> __< r​ucknium:monero.social >__ preland: It was online before the spamming started. Then the spamming killed it :(     

> __< r​ucknium:monero.social >__ The monitor makes just a few RPC calls and one OS call every 30 seconds     

> __< plowsof >__ i have been busy running workflows on github - watching it error - and trying again. for monero-site translaitons / weblate. i am almost ready to on-board a budding site maintainer, just require a our weblate to be back online or the files for my own instance     

> __< plowsof >__ translations*     

> __< p​reland:monero.social >__ Who would’ve guessed that the stress net monitor would get stressed     

> __< vthor >__ :D     

> __< plowsof >__ vthor , who has taken over MoneroSigner project has completed his first milestone. nice work     

> __< r​ucknium:monero.social >__ Nice job, vthor     

> __< plowsof >__ hackerindustrial, has been "fired". this is the same person behind the ccs hack investigation who has not provided any updates on that. after being fired for reasons including inactivity im not surprised      

> __< vthor >__ :) thnk you, but milestone already delayed two days :/     

> __< c​t:xmr.mx >__ milestone payment?     

> __< plowsof >__ if anyone is interested i made a #monero-ccs-emojis channel. specifically to be alerted when people leave emoji reactions on the ccs gitlab, or when luigi pushes things to master.       

> __< plowsof >__ irc only at the moment      

> __< vthor >__ I got the milestone 1 payment, thank you! :)     

> __< r​ucknium:monero.social >__ One more thing about stressnet: Discussion of stressnet is happening in #monero-stressnet:monero.social  on Matrix and ##monero-stressnet on Libera Chat IRC. You can run a stressnet node by running the monerod binary in https://github.com/spackle-xmr/monero/releases     

> __< plowsof >__ was there not talk of doing a 'monero fork' instead of a testnet-fork? to avoid some issues?     

> __< c​t:xmr.mx >__ And device spec requirements rucknium?     

> __< ofrnxmr >__ Enough ram     

> __< ofrnxmr >__ Not enough ram = it will OOM     

> __< vthor >__ How I already interrupted, I will throw another question in the room, can I rename MoneroSigner to XmrSigner for various reasons: a)confusion with the hackerindustrial project/domains and so forth and me having now different variables and strings in my repos, driving me nuts to be not uniform :D?     

> __< c​t:xmr.mx >__ is 16GB enough?     

> __< vthor >__ sorry, foret my qustion, was too slow     

> __< ofrnxmr >__ yes, imo @ct      

> __< r​ucknium:monero.social >__ ceetee.mx: Two-thread CPU and 8GB of RAM seem ok. 4GB of RAM seems to be not enough. I think the storage requirements are 15GB now. We could have a blockchain of 50GB by the end of two months when we expect to end it.     

> __< ofrnxmr >__ Vthor, i see np with that     

> __< plowsof >__ better than Gupax and Gupaxx      

> __< c​t:xmr.mx >__ okey, then I can spin up extra nodes     

> __< c​t:xmr.mx >__ Do multiple (physical) devices on the same local network help? 10Mb upload bandwidth unfortunately     

> __< ofrnxmr >__ Im running 2 nodes on the same host     

> __< r​ucknium:monero.social >__ You have to run the monerod with `--testnet` check the repo's README for more instructions     

> __< plowsof >__ one such pull request to core from 0xffff directly thanks to stressnet https://github.com/monero-project/monero/pull/9376      

> __< plowsof >__ News: [Monero Observer](https://www.monero.observer/) - [Revuo Monero](https://revuo-xmr.com/) - [Monero Moon](https://www.themoneromoon.com/)         

> __< ofrnxmr >__ the pr by 0xfffc increases startup speed by ~3x in my testong 25-30min vs 80min     

> __< ofrnxmr >__ A full tx pool caused an 80min delay to restart a node     

> __< c​t:xmr.mx >__ heart     

> __< c​t:xmr.mx >__ ^because irc cant see emojis     

> __< 0​xfffc:monero.social >__ 🙏🏻🙏🏻 my understanding is it is possible to optimize it further. So hopefully we will have even faster implementation soon.     

> __< r​ucknium:monero.social >__ IMHO, everything in monerod needs to be parallelized and async. But that's easier said than done lol     

> __< plowsof >__ click of the heels      

> __< ofrnxmr >__ Currently startup uses 1 thread 🫠     

> __< plowsof >__ thanks for confirming ofrnxmr, ive had some issues getting to to be slow to begin with     

> __< ofrnxmr >__ 0x is working on a few diff problems atm.. if any other devs want to help , 🤲     

> __< plowsof >__ shall we jump into the ccs merge list whilst skipping a few select ones      

> __< ofrnxmr >__ (yes)     

> __< plowsof >__ skipping seraphis review (MRL issue) and moving briefly to   b. [New Monero Website](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/450)         

> __< r​ottenwheel:kernal.eu >__ +1 merge from me.     

> __< plowsof >__ luigis comments here suggest core are looking for a current site maintainer, to explain my trip to weblate school. i need to follow up with janaka now (they mention AI translations, and weblate provides these features , either as suggestions, or directly added and labelled as requiring edits to translators get presented with them to confirm. but     

> __< plowsof >__ yeah, our weblate is offline       

> __< ofrnxmr >__ +1 merge     

> __< c​t:xmr.mx >__ Interested in long term maintainer position sounds good     

> __< c​t:xmr.mx >__ +1 from me too, hoping it works out long term     

> __< ofrnxmr >__ Lets see how this website pans out and can think about maintainer later imo     

> __< plowsof >__ after making a 100,000+ change pull request to my own test repo i see why we needed a dedicated "translations coordinator"      

> __< ofrnxmr >__ Maintainer overlaps with this. Nothing to maintain before its built. Let it be built then we can decide on a maintainer     

> __< ofrnxmr >__ +1 plowsof, but tl has been rip for a long time. We had a tl coordinator didnt we, then we cancelled ccs for tl     

> __< plowsof >__ i plan to do the initial 'get us to square one' work and then hand off (lol)     

> __< plowsof >__ yeah translations shuld be part of the site maintainer role      

> __< ofrnxmr >__ Ty plow     

> __< c​t:xmr.mx >__ ofc ofrn, but I'd rather have a builder interested in maintaining, then a builder who is looking to exit after the job     

> __< plowsof >__ sign them onto a 14 fight deal instead of 1 prize fight, noted     

> __< ofrnxmr >__ Ofc. But we just neutered the proposal     

> __< plowsof >__ yeah pushing external problems onto the proposor (delaying) is not going to make them stick aroud neither     

> __< ofrnxmr >__ They are doing what we asked them to do atm. Can't keep moving goalposts. 3 months isnt a long time, we'll be back to talk about maintaining soon     

> __< c​t:xmr.mx >__ we share the same opinion ofrn     

> __< plowsof >__ we can leave it there, ill follow up with them about weblate (and ask back end admin to pretty please get it back online or send me the files somehow.. learning as i go here)     

> __< plowsof >__ but try to keep that unrelated from stopping them going forward     

> __< ofrnxmr >__ 🙏     

> __< plowsof >__   c. [How to mine Monero guide](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/451)         

> __< plowsof >__ hasnt had the most feedback so far, make of that what you will     

> __< ofrnxmr >__ I dont know if i sent the msg, but we need to update the getmonero mining page     

> __< c​t:xmr.mx >__ promised last time to read trough it, didn't have the time for it, sorry     

> __< plowsof >__ moneroguides has to remind us more      

> __< ofrnxmr >__ The reason for proposals like the one above, sre because instructions are all over the place and all all of them noisy and partially incorrect.      

> __< plowsof >__ no response about the rates difference yet, but uhm, i found the first videos to be pleasant and informing      

> __< c​t:xmr.mx >__ in general: proposers feel free to ask for feedback/review in this room outside the meeting times (as long as you dont spam)     

> __< plowsof >__ (skipping i2p proposal)      

> __< plowsof >__   e. [ofrnxmr feat. BasicSwapDEX - take over the world pt 2](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/457)         

> __< plowsof >__ the reason i made the emoji alert room, as we cant follow when porposals get >10 reactions      

> __< a​illia:matrix.org >__ + often outdated     

> __< ofrnxmr >__ Emoji alert room? 👀     

> __< plowsof >__ #monero-ccs-emojis      

> __< plowsof >__ irc only     

> __< c​t:xmr.mx >__ what is holding up the basicswap proposal if I may ask?     

> __< 0​xfffc:monero.social >__ I have a shaky connection atm. + from me.     

> __< plowsof >__ in response to hintos comment here https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/457#note_24904 (reg custody of funds / 100% custody ) - at this stage in the game we should have a multisig solution for this. tobtoht as you can imagine has alot of tasks on his plate and we should hopefully start getting updates      

> __< ofrnxmr >__ Idk whats holding it up, but were still working. Hinto wanted a comment from the devs, @crz offered to comment but i dont understand why im supposed to nag the devs repeatedly for politics. "post a gist here" "post a gist there"     

> __< ofrnxmr >__ im not particularly concerned with a multiisig. Generalfund and ccs don't use them. I trust plowsof     

> __< r​ucknium:monero.social >__ IMHO the general idea of this proposal is good. My 2 piconeros: Having this project in multiple stages would be good. We can see the progress on the first proposal and then hopefully fund a second one. The funds custody issue need to be figured out.     

> __< s​yntheticbird:monero.social >__ Tbf old *gist requests* were because it was mess in between fake accounts supporting you or hating you and there was indeed a need to know if the devs were aware. Please make a distinction with hinto's request     

> __< plowsof >__ luigi1111 needs go through the merge list      

> __< ofrnxmr >__ its nkt a dictinction. Crz posred the first gist. Cryptoguard posted a second k e     

> __< ofrnxmr >__ One*     

> __< ofrnxmr >__ If crz creates an account on giab, he'll have to post a third. Its very annoying and spams their gits with nonsense.      

> __< plowsof >__ with 9 mins left we can continue talk on this at the end (skipping monero poker, and development of a new ccs platform, although the monero poker is a valid proposal open for feedback. a few comments noted that xmr.poker exists but nobody uses it and theres an unanswered question related to that)      

> __< plowsof >__ frengzie, would you llike to comment on your direction with your proposal @   g. [Mobazha with Monero in Privacy Ecommerce](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/463)         

> __< f​engzie:monero.social >__ yes, thanks plowsof for mentioning this proposal.     

> __< f​engzie:monero.social >__ For this proposal,  I want to apply it to advance usability and adoption of Monero instead of infrastructure building. I definitely believe it would be much helpful for Monero to reach more users.     

> __< plowsof >__ its closed source still?      

> __< f​engzie:monero.social >__ Currently the network is deployed worldwide, and we are in preparation of publicity stage.     

> __< c​t:xmr.mx >__ closed source would disqualify it from the ccs     

> __< ofrnxmr >__ Proprietary?     

> __< plowsof >__ yeah      

> __< ofrnxmr >__ Ct - nah, movies winnibg oscars were approved      

> __< f​engzie:monero.social >__ the team works on it for more than 3 years, and i am always thinking how to sustain the team and make it developed in a long term. I haven't found out a solution yet to open source and gain profit for sustain     

> __< ofrnxmr >__ fergzie - close proposal, come back when figured out     

> __< s​yntheticbird:monero.social >__ no need to press let him finish     

> __< ofrnxmr >__ (ct - i was being sarcastic btw.)      

> __< plowsof >__ im glad you have introduced your project to a new audience, for the ccs closed source is a no go, i wish you best of luck with other fundraisers to integrate other cryptos (e.g. the open zcash proposal you have open)      

> __< c​t:xmr.mx >__ ofrn: ikik     

> __< f​engzie:monero.social >__ i'm thinking about tokenization and white paper, however it might be a long run. At this moment, i strongly will to have monero support inside, and sell related assasorites etc.     

> __< plowsof >__ its just not compatible with the CCS rules or our FOSS community      

> __< ofrnxmr >__ Kuno doesnt care about foss btw. But ccs shouldnt support non-foss projects, imho and by RTFM      

> __< f​engzie:monero.social >__ the team is struggling to sustain and move forward, and we really want to do the business. so we look around for help.     

> __< s​yntheticbird:monero.social >__ to be clear, there has been no exceptions to this rule and/or closed-source analogy in other funded project     

> __< ofrnxmr >__ syntheticbird - yes there has     

> __< plowsof >__ yes, Kuno is a great option to raise funds for your project fengzie     

> __< s​yntheticbird:monero.social >__ Don't take that as a judgement of your work.     

> __< ofrnxmr >__ the movie ccs isnt foss     

> __< f​engzie:monero.social >__ my thinking is that: some funds would be applied for some activities, there is no code     

> __< f​engzie:monero.social >__ for this one, don't think it is a coding project, but just a publicity/promotion project     

> __< s​yntheticbird:monero.social >__ lol, i sure want the adobe clip file ofrnxmr     

> __< plowsof >__ xmrbazaar.com has also just released as noted by ofrnxmr in that projects matrix room      

> __< f​engzie:monero.social >__ and we could sign contract and donate back if there is profit     

> __< ofrnxmr >__ fengzie, please. Foss or no     

> __< plowsof >__ haveno... basicswap... also     

> __< ofrnxmr >__ Were not a vc investing platform     

> __< f​engzie:monero.social >__ ok. xmrbazaar is a different concept. it is just a single store, while mobazha is a stores network     

> __< f​engzie:monero.social >__ ok.     

> __< s​yntheticbird:monero.social >__ fengzie, this is unfortunately out of scope for a CCS. Sorry for your struggle, but it isn't how it is working. There are no corporation behind monerod and the community wouldn't trust one. There is simply no way to adapt these for your project     

> __< plowsof >__ wait, the movie proposal was for funding/promotion of closed source* material and that was allowed. so luigi has to take a look      

> __< c​t:xmr.mx >__ sorry this has been dragged out for such a long time fengzie     

> __< plowsof >__ but for a dev project, it fits too perfectly into the rules as being out of scope      

> __< ofrnxmr >__ yeah, plowsof but i think the movie proposal should not set precedent. Imo it was a terrible mistake to merge. Do we even have access to the movie?     

> __< f​engzie:monero.social >__ ok, thanks for the information..     

> __< plowsof >__   i. [Revuo Monero maintenance (2024 Q3)](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/466)         

> __< ofrnxmr >__ Or did we just pay for him to market his movie and self serve?     

> __< plowsof >__ i guess we can ask geonic for an update (he has kept us up to date on each of the meetups / promotional events)     

> __< ofrnxmr >__ he made $ at each of those events (paid viewing etc)     

> __< ofrnxmr >__ the movie didnt win an oscsr btw     

> __< x​mrfamily:matrix.org >__ What movie proposal? I am working on documentary on lmad, Alex has agreed to be interviewed     

> __< ofrnxmr >__ limite      

> __< plowsof >__ rottenwheels revuo proposal sirs      

> __< ofrnxmr >__ Im not voting for or against rotten. Is revuo active again?     

> __< plowsof >__ monero moon had a run of the ccs, and rottens rates are less. spirobel has left some negative feedback      

> __< c​t:xmr.mx >__ yes, its active     

> __< s​yntheticbird:monero.social >__ im against as I think this ccs is way to good looking and rottenwheels is perfect, so its very sus     

> __< c​t:xmr.mx >__ last quarter of revuo was also funded iirc     

> __< ofrnxmr >__ Spirobel said rotten was being political when choosing what efforts to cover and voted against it, so idk     

> __< s​yntheticbird:monero.social >__ I've seen other being more political tbh...     

> __< ofrnxmr >__ I dont follow rotten tho. I just remember him cancelling it recently      

> __< s​yntheticbird:monero.social >__ but one project being forgot shouldn't destroy the good track of revuo     

> __< s​yntheticbird:monero.social >__ ofrnxmr I heard of it too, i dont remember exactly what it was about     

> __< ofrnxmr >__ hd msgd me to tell me he wasnt going to write it anymore, but at the same time he opened a pr to list it on getmonero     

> __< ofrnxmr >__ Im abstaining from the vote on this one today     

> __< ofrnxmr >__ but     

> __< plowsof >__ yes after that he returned (has since been funded by a kuno to obtain monerokon if thats relavant)     

> __< plowsof >__ s/obtain/attend     

> __< ofrnxmr >__ Ill votr that @monero twitter needs to stop censoring it     

> __< plowsof >__ someone who also attended monerokon has a proposal open,   j. [Jeffro256 Full-time 2024 Q3](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/467)         

> __< ofrnxmr >__ We need jeff to look into the rpc issues with stresnet     

> __< plowsof >__ jeffro has also complimented boog900's latest ccs update/work      

> __< 0​xfffc:monero.social >__ Obviously merge.     

> __< ofrnxmr >__ You cant connect a wallet when txpool is full     

> __< ofrnxmr >__ When he did mrl 109, he had 2 prs. 1 of them sped stuff up, perhaps he can do something similar here      

> __< s​yntheticbird:monero.social >__ merge or ill steal your monero plow     

> __< ofrnxmr >__ I havent looked at the ccs, but merge and pls ask him to help w stressnet      

> __< c​t:xmr.mx >__ obv. merge     

> __< plowsof >__ there is mention of "Multi-threaded compute"      

> __< ofrnxmr >__ Yeah, but he needs to join stressnet 🙏     

> __< s​yntheticbird:monero.social >__ jeffro entered the chat     

> __< j​effro256:monero.social >__ Hi     

> __< ofrnxmr >__ Helloo jeffroo     

> __< s​yntheticbird:monero.social >__ what are you referring by multi-threaded compute im curious. what could be parallelized     

> __< 0​xfffc:monero.social >__ Hello     

> __< j​effro256:monero.social >__ Sorry did I miss something ?     

> __< ofrnxmr >__ Ccs meeting     

> __< ofrnxmr >__ Were discussing your proposal     

> __< ofrnxmr >__ And im asking you if you can help solve "wallets wont connect to full txpool" and "parallelize start up" with #stressnet     

> __< j​effro256:monero.social >__ When scanning e-notes, we need to do 1 ECDH op for each 1/256 e-notes on chain. This is pretty expensive but can be easily parallelized     

> __< j​effro256:monero.social >__ Just like how current wallet scanning is multi threaded     

> __< j​effro256:monero.social >__ Ofrnxmr are there GIthub issues for those ?     

> __< ofrnxmr >__ No, its a test network that were attacking / stressing     

> __< s​yntheticbird:monero.social >__ there is the #monero-stressnet channel for that.     

> __< j​effro256:monero.social >__ What does "wallet won't connect to full txpool" mean?     

> __< ofrnxmr >__ if wont connect      

> __< plowsof >__ https://libera.monerologs.net/monero-community/20240622#c389214     

> __< ofrnxmr >__ When txpool is 300+mb, wallets simply fail to connect     

> __< j​effro256:monero.social >__ BTW I am running a stressnet node tho     

> __< j​effro256:monero.social >__ Like it won't connect to a daemon with a full txpool?     

> __< ofrnxmr >__ Yes     

> __< j​effro256:monero.social >__ Does it timeout ?     

> __< ofrnxmr >__ yes     

> __< r​ucknium:monero.social >__ When txpool is large, over 100MB, monero-wallet-rpc and -cli (I think) cannot connect to monerod     

> __< r​ucknium:monero.social >__ The temporary solution is to `flush_txpool` on the node     

> __< 0​xfffc:monero.social >__ Interesting problem.     

> __< plowsof >__ jeffros work is on FCMP++ but stressnet could help test some new features there      

> __< ofrnxmr >__ it starts the connection, you see the node receive the rpc call, but eventually it just dies and says "no connection to daemon. 0 blocks received"     

> __< 0​xfffc:monero.social >__ flush_txpool itself is going to be optimized too. It is O(n) and should be O(1)     

> __< r​ucknium:monero.social >__ AFAIK it can _maintain_ a connection as the txpool gets very large. But if you get disconnected it doesnt want to disconnect     

> __< ofrnxmr >__ Doesn't want to reconnect*. Yes     

> __< r​ucknium:monero.social >__ Yeah. Anyway, I know you have set your priorities jeffro and it is probably hard to switch task areas     

> __< ofrnxmr >__ jeffro is the getblocks.bin expert tho :P     

> __< r​ucknium:monero.social >__ The stressnet will go for about two months. It would be hard to analyze the issues without a live testing environment like stressnet     

> __< 0​xfffc:monero.social >__ I wish we can shut it down and start it up. For example we set up everything ready. And we can start it regularly based on some schedule.     

> __< 0​xfffc:monero.social >__ Leaving it running for a long time might not be economical     

> __< ofrnxmr >__ We can probably schedule when we spam etc     

> __< 0​xfffc:monero.social >__ Anyway that is discussion for another thread     

> __< ofrnxmr >__ Meeting over though plowsof +1 merge jeffro     

> __< plowsof >__ lets end the meeting there then, thank you all for attending and please continue      


Automated by [this](https://github.com/plowsof/post-libera-meeting-logs)

**Comment by plowsof** [comment]
original monerologs is back. i have an irc bouncer with messages in an sqlite database that can also be called upon in a pinch.

**Comment by rottenwheel** [comment]
@plowsof what channels is your bouncer part of? Just curious.

**Comment by plowsof** [comment]
every channel "plowsof" is in

**Comment by rottenwheel** [comment]
Damn, all our dirty secrets are getting logged by plowsof!
