### ISSUE TITLE
Monero Community Workgroup Meeting: Saturday 6th July 15:00UTC

### ISSUE THREAD

**Issue by plowsof** [monero-project/meta#1032]
Location: [Libera.chat, #monero-community](https://libera.chat/) | [Matrix](https://matrix.to/#/#monero-community:monero.social?via=matrix.org&via=monero.social)

[Instructions for joining the monero.social Matrix server.](https://www.getmonero.org/resources/user-guides/join-monero-matrix.html)

Time
15:00 UTC [Check your timezone](https://www.timeanddate.com/worldclock/converter.html)

Moderator: plowsof

Please reach out in advance of the meeting if you would like to propose an agenda item.

Proposed Meeting Items:

1. Introduction
2. Greetings
3. Community highlights    
    - p2pool 4.0 'hardfork ready' with merge mining support https://github.com/SChernykh/p2pool/releases/tag/v4.0    
    - Animated explainer video on randomX - vostoemisio/xenu rawfile/YTlink @ [ccs.getmonero](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/412#note_25078)
    - [Help4XMR](https://github.com/HardenedSteel/Help4XMR) - hardenedsteel 
    - [MVP Tor-based Mobile Web Application To Interact With Ledger Nano X And Haveno](https://bounties.monero.social/posts/128/100-100m-mvp-tor-based-mobile-web-application-to-interact-with-ledger-nano-x-and-haveno) receives a 100xmr donation
    - LIMITE/Mark of distinction [final report](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/371#note_25187) - geonic
    - MRL to discuss FCMP++ related research paper- [Ruckniums ccs comment](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/449#note_25181)
 
News: [Monero Observer](https://www.monero.observer/) - [Revuo Monero](https://revuo-xmr.com/)        

5. [CCS updates](https://ccs.getmonero.org/)    
  a. [How to mine Monero guide](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/451)    
  b. [ofrnxmr feat. BasicSwapDEX - take over the world pt 2](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/457)    
  c. [Monero Poker Infrastructure Project](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/461)    
  d. [Development of New CCS Proposal Platform](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/464)    
  e. [rehrar help out the project](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/470)    
  f. [VOSTOEMISIO - FCMP Animated Explainer Video](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/472)    
  g. [VOSTOEMISIO - Remake Introductory "What Is Monero?" Video](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/473)    
  h. [Pago Payment Processor](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/475)    
  i. [monerobull for website workgroup](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/476)    
6. Workgroup reports    
  a. Dev workgroup
  b. Localization workgroup
  c. Outreach workgroup
  d. Events workgroup - [MoneroKon 2024](https://www.monerokon.org/)
  e. Website workgroup
  f. Policy workgroup
  g. Research workgroup
  h. [Seraphis Migration workgroup](https://github.com/seraphis-migration)
7. Open ideas time
    - 0mq FFS overfunding - geonic     
    - Weekly/Bi-weekly twitter spaces?
9. Confirm next meeting date/time    

[Previous meeting including logs](https://github.com/monero-project/meta/issues/1027)    

Meeting logs will be posted here afterwards.

**Comment by plowsof** [comment]
Not going to bring these proposals up inside meetings anymore unless there are any major changes/updates or there is enough interest in doing so. 
  a. [Seraphis General Paper Review](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/441)    
  d. [I2P SAMv3](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/454) 
  g. [Mobazha with Monero in Privacy Ecommerce](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/463)    
  h. [Development of New CCS Proposal Platform](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/464)

**Comment by nahuhh** [comment]
>  Not going to bring these proposals up inside meetings anymore unless there are any major changes/updates or there is enough interest in doing so. 
>   a. [Seraphis General Paper Review](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/441)    
>   d. [I2P SAMv3](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/454) 
>   g. [Mobazha with Monero in Privacy Ecommerce](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/463)    
>   h. [Development of New CCS Proposal Platform](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/464)   

a. Move to MRL meeting @Rucknium
d. Close and open a bounty
g. Close at [request of proposer](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/463#note_24931)
h. 🤷‍♂️ i haven't looked at it

**Comment by Rucknium** [comment]
Can you add this to the agenda?:

- [MAGIC Monero Fund proposal: xmrtoken](https://github.com/MAGICGrants/Monero-Fund/issues/30)

I don't personally like this proposal, but the community should have an opportunity to give input.

**Comment by plowsof** [comment]
Logs 
> __< plowsof >__ <3      

> __< x​mrfamily:matrix.org >__ Telegram bridge relay needed, don't discriminate     

> __< ofrnxmr >__ No     

> __< ofrnxmr >__ We do discriminate against TG and discord here.     

> __< x​mrfamily:matrix.org >__ Matrix/ discord maybe. Where tg bot     

> __< nioCat >__ no telegram, no discord      

> __< x​mrfamily:matrix.org >__ Telegram is not liked on matrix     

> __< plowsof >__ Meeting time      

> __< plowsof >__ greetings, https://github.com/monero-project/meta/issues/1032     

> __< m​onerobull:matrix.org >__ Hello     

> __< nioCat >__ hi     

> __< r​ottenwheel:kernal.eu >__ Hola.     

> __< r​ottenwheel:kernal.eu >__ Hallo.     

> __< h​into:monero.social >__ hi     

> __< plowsof >__ happy 4th of July weekend everyone, great timing i know      

> __< p​lowsof:matrix.org >__ has the CCS ideas page been the highlight of the past previous 2 weeks?     

> __< m​ichael:monero.social >__ Hello, sorry to arrive late.     

> __< p​lowsof:matrix.org >__ no worries MSvB welcome, anything to share from your end?     

> __< r​ottenwheel:kernal.eu >__ Kastelo when?     

> __< r​ottenwheel:kernal.eu >__ crickets.ogg     

> __< p​lowsof:matrix.org >__ News: [Monero Observer](https://www.monero.observer/) - [Revuo Monero](https://revuo-xmr.com/)     

> __< p​lowsof:matrix.org >__ the 100 xmr donation to this bounty made me look twice [MVP Tor-based Mobile Web Application To Interact With Ledger Nano X And Haveno](https://bounties.monero.social/posts/128/100-100m-mvp-tor-based-mobile-web-application-to-interact-with-ledger-nano-x-and-haveno) receives a 100xmr donation  FreeRoss     

> __< r​ucknium:monero.social >__ Stressnet has entered its third week. Discussion is in #monero-stressnet:monero.social  and ##monero-stressnet on IRC. rbrunner put up a GitHub issue about the first major problem that stressnet found: "Daemons processing big blocks may bump against serializer sanity checks and fail to sync" https://github.com/monero-project/monero/issues/9388     

> __< p​lowsof:matrix.org >__ p2pool miners, please update so you're ready for the hardfork  https://github.com/SChernykh/p2pool/releases/tag/v4.0 , nice work sech1     

> __< r​ottenwheel:kernal.eu >__ Revuo Monero has brand-new imagery and logo across the board. Port from Jekyll CSS/HTML to Hugo Markdown is 90% completed. Active Kuno fundraiser still running. Consider sending some piconeros if you like what we're doing! https://kuno.anne.media/fundraiser/kaib/     

> __< r​ottenwheel:kernal.eu >__ New matrix room too, in case you'd like to jump in. Revuo Monero IRC channel: #revuo-xmr on libera.     

> __< p​lowsof:matrix.org >__ monero-site (Jekyll) has an open issue for being ported to Hugo (for issues related to translation plugins)     

> __< p​lowsof:matrix.org >__ perhaps the same devs who complete the revuo transfer could look into that / offer a quote :)     

> __< p​lowsof:matrix.org >__ is there anything else people would like to share?     

> __< m​onerobull:matrix.org >__ Haveno reached 100 offers     

> __< p​reland:monero.social >__ I broke my Qubes install a few days ago, and only had the time to fix it last night     

> __< ofrnxmr >__ This may already be known, but monero-lws has subaddress support      

> __< r​ucknium:monero.social >__ The MAGIC Monero Fund got this proposal: "xmrtoken": https://github.com/MAGICGrants/Monero-Fund/issues/30     

> __< p​lowsof:matrix.org >__ hardenedsteel has been busy with his roadmap 2024 pull request on site https://github.com/monero-project/monero-site/pull/2310 , triptych will finally be removed from our roadmap, hooray     

> __< r​ucknium:monero.social >__ I don't like the proposal, but it is here for community input     

> __< p​lowsof:matrix.org >__ NACK the xmrtoken proposal, interpolarity / smart contracts not for me     

> __< s​pirobel:kernal.eu >__ left a comment on the pago payment processor ccs https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/475#note_25283 I can go into more detail what the limitations of the wallet-rpc are if necessary.     

> __< p​lowsof:matrix.org >__ thanks spirobel     

> __< p​lowsof:matrix.org >__ ok with that mention of ccs proposals, lets cover the ideas page     

> __< ofrnxmr >__ " I will write a payment processor as part of this kuno https://kuno.anne.media/fundraiser/07nm/ I can give you more detailed feedback on this CCS if you want" << spirobel has a fundraiser      

> __< nioCat >__ if they want to make a "token" they should be "free" to do so  :D     

> __< plowsof >__ 40kusd for "penetesting"     

> __< p​lowsof:matrix.org >__ a. [How to mine Monero guide](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/451)     

> __< r​ottenwheel:kernal.eu >__ +1 for the guide. Monero guides does a good job.     

> __< p​lowsof:matrix.org >__ rates where adjusted since the last meeting (0.29xmr/hr > 0.23)https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/451#note_25036     

> __< ofrnxmr >__ I think they need to correct their existing guide(s) before making more     

> __< ofrnxmr >__ "ARM-based (Advanced RISC Machine) systems would be ideal for something like this. However, it’s in fact not the best platform for running the Monero daemon. This is because the hardware lacks support for the “Advanced Encryption Standard” (AES) instruction set. The major dissadvantage is drastically longer sync times. Typically, only systems     

> __< ofrnxmr >__ with x86 architecture will benefit from this instruction set."      

> __< ofrnxmr >__ This is false and only applies to rasp pi     

> __< p​lowsof:matrix.org >__ 7. You're done. Now go drum up some support. https://ccs.getmonero.org/how-to-ccs/     

> __< ofrnxmr >__ "The Monero daemon requires 1 to 2 GB of memory to run, so aim to use a system with at least 4 GB of memory." Also false     

> __< ofrnxmr >__ (unless you like to OOM your node)     

> __< ofrnxmr >__ Well written and well spoken, but shotty info     

> __< ofrnxmr >__ I support the quality if production, but the quality of content leaves a lot to be desired      

> __< r​ottenwheel:kernal.eu >__ moneroguides sir?     

> __< r​ottenwheel:kernal.eu >__ plowsof @plowsof:matrix.org next one or we'll run out of time.     

> __< p​lowsof:matrix.org >__ perhaps too busy (per comment) to drum up support, i'd like to see more of that especially since their last series where a year ago     

> __< p​lowsof:matrix.org >__ b. [ofrnxmr feat. BasicSwapDEX - take over the world pt 2](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/457)     

> __< r​ottenwheel:kernal.eu >__ 👎     

> __< p​lowsof:matrix.org >__ no major changes to the proposal for a while now, no feedback from luigi yet     

> __< p​lowsof:matrix.org >__ moving on     

> __< c​t:xmr.mx >__ yeah I wondering what is holding up the process on bsx     

> __< p​lowsof:matrix.org >__ c. [Monero Poker Infrastructure Project](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/461)     

> __< c​t:xmr.mx >__ Who or what are we waiting for regarding bsx     

> __< p​lowsof:matrix.org >__ not much activity here, xmr.poker existing already and not being popular does not reflect well on this proposal^     

> __< r​ottenwheel:kernal.eu >__ 👎     

> __< p​lowsof:matrix.org >__ bsx proposal: decision from roundup of events / or pointed guidance (if changes are required) from luigi     

> __< c​t:xmr.mx >__ I tried the poker demo at different times, and always zero users besides me. I think it makes little sense to pour money into something that is not used     

> __< nioCat >__ I left a comment on the poker     

> __< p​lowsof:matrix.org >__ thanks for confirming this ceetee, and niocat for commenting     

> __< p​lowsof:matrix.org >__ closing?     

> __< nioCat >__ basically he says the it is free software and then states that if you want to use it commercially he will give you a special license       

> __< nioCat >__ lol     

> __< p​lowsof:matrix.org >__ niocs comment https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/461#note_25282     

> __*__ geonic shows up late     

> __< p​lowsof:matrix.org >__ you're early geonic     

> __< ofrnxmr >__ ct - ill play with you next time,lmj     

> __< ofrnxmr >__ lmk*     

> __< p​lowsof:matrix.org >__ d. [Development of New CCS Proposal Platform](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/464)     

> __< p​lowsof:matrix.org >__ i had assumed the sentiment was for closing this proposal. any disagreements?     

> __< ofrnxmr >__ Ai written responses are cringe      

> __< m​onerobull:matrix.org >__ No     

> __< c​t:xmr.mx >__ ofrn I dont even like poker, I was checking for activity     

> __< nioCat >__ for activity you need hundreds of people signed up at a minimum     

> __< p​lowsof:matrix.org >__ close alternative ccs platform please     

> __< c​t:xmr.mx >__ current CCS software is good enough     

> __< p​lowsof:matrix.org >__ e. [rehrar help out the project](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/470)     

> __< nioCat >__ having software and running a poker room are 2 very different things      

> __< ofrnxmr >__ close. Tell them come bk when they dont need gpt to write their resposes     

> __< p​lowsof:matrix.org >__ as it is july 4th weekend / diego was here last saturday when no meeting issue was posted and was here most of the week discussing it     

> __< m​onerobull:matrix.org >__ Hm yes he really has his finger on the pulse     

> __< ofrnxmr >__ i think we should let this proposal simmer for a bit. There are competing proposals and a lot of the scope is less than ensured.     

> __< ofrnxmr >__ i left comment on MB's proposal re: site, about wanting to see some work first      

> __< geonic >__ maybe work on the website workgroup can begin while the proposals are pending?     

> __< ofrnxmr >__ There are a few very active contributors there     

> __< ofrnxmr >__ What is a website "workgroup? We dont collaborate, we are independent. Prs come as people make them, reviews come as people do them     

> __< ofrnxmr >__ We dont have dev meetings, idk why we'd have site meetings      

> __< ofrnxmr >__ He have a contribution guide     

> __< plowsof >__ because monerobull and diego's are similar and competing? proposals. let me just share vostos recent ideas:     

> __< plowsof >__   f. [VOSTOEMISIO - FCMP Animated Explainer Video](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/472)         

> __< plowsof >__   g. [VOSTOEMISIO - Remake Introductory "What Is Monero?" Video](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/473)         

> __< plowsof >__ open for feedback^      

> __< plowsof >__   i. [monerobull for website workgroup](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/476)         

> __< plowsof >__ (skipping over the payment processor for now)      

> __< geonic >__ it's not clear to me whether these videos include a round of client revisions or not     

> __< ofrnxmr >__ what is monero is intended to replace our outdated one homepage video     

> __< geonic >__ including the ones already produced and under discussion in monero-site     

> __< plowsof >__ during the initial creation stage we get storyboards      

> __< ofrnxmr >__ Client revision, meaning future updates? Or feedback during creation?     

> __< plowsof >__ storyboards? concepts? still image with script text on each scene?     

> __< geonic >__ feedback after the production of the video     

> __< ofrnxmr >__ I believe so, as well as during      

> __< plowsof >__ most recent video being the randomX one https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/412#note_25078     

> __< plowsof >__ that is the update / payout request      

> __< geonic >__ is the voice AI?     

> __< geonic >__ sounds monotonous and loses me     

> __< v​ostoemisio:matrix.org >__ Surprisingly not     

> __< v​ostoemisio:matrix.org >__ I'm at a dinner but I'll be available here for any immediate questions     

> __< plowsof >__ geonic please consider what the previous animated team produced for us      

> __< m​onerobull:matrix.org >__ Flying eye monster?     

> __< plowsof >__ we're talking floating bag of flesh / eye with an AI sounding voice that was human somehow     

> __< plowsof >__ lol     

> __< plowsof >__ doe splowsof need to help on-board any budding site maintainers?      

> __< 4​rp:matrix.org >__ Hello, today I bought crypto for the first time, the website shows that everything is fine, but not xDD.  They didn't send it and they say it's the wallet's fault. Do you know any legit websites without KYC?     

> __< ofrnxmr >__ 4rp we are in a meeting for 9 more mins. Please hold     

> __< plowsof >__ +1 thanks      

> __< h​into:monero.social >__ is there a reason why both monerobull and Diego Salazar can't lead the site workgroup and/or split responsibilities? too much synchronization needed?     

> __< ofrnxmr >__ Because overkill?     

> __< d​iego:cypherstack.com >__ Hi     

> __< plowsof >__ hello     

> __< m​onerobull:matrix.org >__ You're right, it's really a $200k position if you think about it /s     

> __< plowsof >__ diego arrived 7 days early to this meeting btw      

> __< d​iego:cypherstack.com >__ Lol true     

> __< d​iego:cypherstack.com >__ Also true that I'm at a family gathering. Tons of cousins in town that I don't see often. Sorry.     

> __< ofrnxmr >__ Merging stuff is easy. Leading workgroup = what? Idk. Who is spending 20+/-hrs/week writing and reviewing prs? site doesnt need bureaucracy, it has a cobtribution guide      

> __< plowsof >__ thanks for attending, you've been answering questions all week      

> __< d​iego:cypherstack.com >__ If we want to rehash old conversation and be sardonic with each other ill have to skip this round.     

> __< r​ottenwheel:kernal.eu >__ "Round of client revisions". That's a new one. 🤣     

> __< ofrnxmr >__ rotten, its not new. You are 💀     

> __< geonic >__ 5 minutes left let's move on pls     

> __< plowsof >__ i have skipped over :   h. [Pago Payment Processor](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/475)         

> __< ofrnxmr >__ oh, acceptxmr was mentioned in pago ccs     

> __< plowsof >__ its new and feedback is arriving (spirobel at the start of the meeting shared)     

> __< r​ottenwheel:kernal.eu >__ What's not new, mongoloid?     

> __< ofrnxmr >__ Acceptxmr finished a milestone recently     

> __< r​ottenwheel:kernal.eu >__ +1 both Vosto's proposals.     

> __< ofrnxmr >__ Your insults. Theyre pretty dry as well. Go squash or. Thx     

> __< ofrnxmr >__ Pr*     

> __< plowsof >__ thanks ofrnxmr, i forgot to add that to the meeting notes, nice busyboredom     

> __< r​ottenwheel:kernal.eu >__ Good luck figuring out what will be of the website thing lol.     

> __< ofrnxmr >__ Dont need luck when you have ppl who work more than they talk     

> __< r​ottenwheel:kernal.eu >__ I don't do what you tell me. Also, a quote isn't an insult. Mind your business.     

> __< plowsof >__ now moving on to AOB whilst leaving many open threads to discuss still ^      

> __< ofrnxmr >__ Squash the pr or close it     

> __< plowsof >__     - 0mq FFS overfunding - geonic          

> __< plowsof >__ specifically https://forum.getmonero.org/9/work-in-progress/2564/0mq-by-tewinget     

> __< geonic >__ I've checked and don't see a 867xmr donation to the GF, as promised in 2020. let's seek clarification from core on who has/had access to this wallet and other FFS wallets     

> __< plowsof >__ so far geonic has received a "fuck off"      

> __< plowsof >__ we can improve upon this      

> __< ofrnxmr >__ Oioioi, rotten, whats a mongoloid?     

> __< plowsof >__ geonic we can add 9mq situation to the awaited transparency report      

> __< plowsof >__ 0mq*     

> __< ofrnxmr >__ +1     

> __< plowsof >__     - Weekly/Bi-weekly twitter spaces?      

> __< plowsof >__ who would like to attend such an event? and when would be a time to have them? and what would they be for?      

> __< geonic >__ there are other ffs proposals with money sitting in them, according to the page. so let's ask for view keys/key images for any & all ffs wallets. or at least clarity on who has them if it's not binaryFate. I don't want to slow the transparency report more with this     

> __< r​ottenwheel:kernal.eu >__ First off, what Twitter handle is hosting the spaces?     

> __< geonic >__ @monero      

> __< r​ottenwheel:kernal.eu >__ Last time Justin tried to start those via @monero it was a shitshow.     

> __< geonic >__ I offered dEBRUYNE to help moderate. he would start the meeting and can assign two other moderators.     

> __< r​ottenwheel:kernal.eu >__ Ew...     

> __< plowsof >__ xmrscott has attended similar events iirc and might be interested      

> __< geonic >__ the question is whether there's any benefit to doing this over the weekly Monerotopia hangout     

> __< ofrnxmr >__ Twitter spaced from @monero sound pretty questionable     

> __< ofrnxmr >__ Who decided this?     

> __< geonic >__ it's just an idea at this point     

> __< j​effro256:monero.social >__ Who runs the @monero twitter account?     

> __< plowsof >__ cc sgp      

> __< r​ottenwheel:kernal.eu >__ John Snow.     

> __< ofrnxmr >__ I want to see the @monero stop being so cringe with its "excited" and "pleased" lead ins for every lost     

> __< plowsof >__ and diego topic: twitter spaces     

> __< ofrnxmr >__ Post*.     

> __< m​onerobull:matrix.org >__ Can I close my ccs now     

> __< geonic >__ most actively & recently dEBRUYNE. sgp has access and fluffy holds the keys     

> __< r​ottenwheel:kernal.eu >__ Why would you close it if you just opened it though?     

> __< r​ottenwheel:kernal.eu >__ Nicholas, my understanding is that sgp no longer has access.     

> __< ofrnxmr >__ End meeting ?      

> __< ofrnxmr >__ Rotten cant stay focused      

> __< m​onerobull:matrix.org >__ Ofrn said we don't need a website group     

> __< r​ottenwheel:kernal.eu >__ 😂😂😂     

> __< r​ottenwheel:kernal.eu >__ And you listen to the stream of nonsensical stuff he says?     

> __< ofrnxmr >__ rotten, go squash your pr      

> __< r​ottenwheel:kernal.eu >__ It is clear per luigi and diego comments during the week that they do want a workgroup.     

> __< ofrnxmr >__ wheres the nonsense there? Csnt merge it as is     

> __< r​ottenwheel:kernal.eu >__ Who's a core team member and a well known community member of those 3?     

> __< ofrnxmr >__ Theres 1 core team member and 2 well known community members there     

> __< r​ottenwheel:kernal.eu >__ 🤣🤣🤣     

> __< ofrnxmr >__ if you dont know how to squash a pr, just say so     

> __< geonic >__ workgroups are usually unfunded until they've shown some results. we're doing it backwards here, which I guess is ok     

> __< geonic >__ is there any moderation in this channel     

> __< p​reland:monero.social >__ Yk someday I’m going to just autism out and make a “people chart” of all the relationships in this community 😂     

> __< p​reland:monero.social >__ Yes, but actually it depends on who’s online     

> __< p​reland:monero.social >__ Most of the time people get modded 100% of the time     

> __< ofrnxmr >__ rotten got yelllw card for gay/tranny comments, then ragequit. Came back to make mongoloid comments ans shitpost for the meeting     

> __< m​onerobull:matrix.org >__ Good idea     

> __< m​onerobull:matrix.org >__ I'll make a tierlist     

> __< m​onerobull:matrix.org >__ S tier: Kayaba, artic, etc     

> __< plowsof >__ yes i think we can end it there and continue discussion, thank you all for attending , pinging for transparency report again immediate. id like to avoid rottenwheels mongoloids comment      

> __< m​ichael:monero.social >__ Dankon for the meeting, and goodbye.     

> __< ofrnxmr >__ +1 thanks     

> __< ofrnxmr >__ So many site coordinators, but nobody asking rotten to squash his pr     

> __< plowsof >__ +     

> __< geonic >__ tx bye     

> __< m​onero-guides:matrix.org >__ -_- got the meeting time wrong     

> __< plowsof >__ your proposal does not mention keeping fingers on a pulse, you're fine, thank you for joining today      

> __< ofrnxmr >__ MG, any interest in updating old guides and voiceovers?     

> __< m​onero-guides:matrix.org >__ Please elaborate; like so many of your typically negative comments you say something and do nothing to support your claim.     

> __< ofrnxmr >__ Arm processors do have aes supoort     

> __< m​onero-guides:matrix.org >__ Do you understand who these videos are aimed at?     

> __< ofrnxmr >__ people who like to OOM their nodes?     

> __< ofrnxmr >__ Idk     

> __< plowsof >__ "Hello, today I bought crypto for the first time, the website shows that everything is fine, but not xDD.  They didn't send it and they say it's the wallet's fault. Do you know any legit websites without KYC?" 4rp, sorry      

> __< plowsof >__ kycnot.me      


Automated by [this](https://github.com/plowsof/post-libera-meeting-logs)
