### ISSUE TITLE
Monero Website Meeting - Sun 11 August 2024, 19:00 UTC

### ISSUE THREAD

**Issue by monerobull** [monero-project/meta#1049]
Location: [Matrix](https://matrix.to/#/#monero-site:monero.social) | [Libera.chat, #monero-site](https://libera.chat)

Time: 19:00 UTC [Check in your timezone](https://www.timeanddate.com/worldclock/converter.html?iso=20211027T190000&p1=1440)

Main discussion topics:

    Greetings

    New Website CCS proposal (https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/450)

    Any other business

    Confirm next meeting agenda

Please comment on GitHub in advance of the meeting if you would like to propose an agenda item.

**Comment by rottenwheel** [comment]
Please add URI to #monero-site on libera.chat, like this: Location: (Matrix), [Libera.chat, #monero-site](https://libera.chat/).

**Comment by rottenwheel** [comment]
@plowsof could we get your logs bot working in here for those?
