### ISSUE TITLE
Kovri meeting: September 24th, 2017, 18:00 UTC

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#109]
### Location:
- [Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | Irc2P | [Slack](https://monero.slack.com)
  - `#kovri-dev`

### Proposed meeting items:
1. Greetings
2. Brief review of what's been completed since the previous meeting
3. Contributor FFS check-in / status
4. Moving meeting date/time
5. Website reorganization
6. Code + ticket discussion / Q & A
7. Any additional meeting items
8. Confirm next meeting date/time

Notes:
- Meeting log will be posted to https://getmonero.org/blog/tags/dev%20diaries

**Comment by anonimal** [comment]
Meeting moved to the 17th.

**Comment by anonimal** [comment]
Moved to 19th.

**Comment by anonimal** [comment]
Third times a charm! Moved to the 24th!

**Comment by rehrar** [comment]
@anonimal can we add 'Website reorganization' to the agenda. I'm working on the overhaul to the Kovri site, and have quite a few things to present for discussions, including a new site map, and some wires for the new pages. I'm hoping to take no more than 10-15 minutes, but it's fairly extensive.

**Comment by anonimal** [comment]
Added.
