### ISSUE TITLE
Kovri social media accounts

### ISSUE THREAD

**Issue by rehrar** [monero-project/meta#113]
Just wondering if Kovri would benefit from social media accounts such as twitter/mastadon, facebook, or anything else. Perhaps @dEBRUYNE_1 can fill us in on the effectiveness of the Monero social media accounts. If we don't need them now, then perhaps something to consider for the future.

**Comment by QuickBASIC** [comment]
I think at least establishing the social media accounts is important even now just to park the names. (Facebook page names, Twitter handles, Google+ pages, Instagram handles, etc are usually need to be unique.) Claiming the names now might avoid troll accounts later.

**Comment by anonimal** [comment]
https://twitter.com/getkovri
`@kovri@mastadon.social`

**Comment by anonimal** [comment]
See https://github.com/monero-project/kovri/pull/716 re: mastodon.

**Comment by anonimal** [comment]
>Twitter handles

[@getkovri](https://twitter.com/getkovri)

>Facebook page names
>Google+ pages

I have zero interest in dealing with these people. Unofficial pages maintained by the community are welcome though.

>Instagram handles

But with what photos?

**Comment by anonimal** [comment]
>Facebook page names
>Google+ pages

Also, a bit hypocritical to be a pro-privacy software that uses these services, no?

**Comment by QuickBASIC** [comment]
> But with what photos?

Instagram users put textual information in images. I'm not sure why. Here's [an example](https://www.instagram.com/deeper_church/?hl=en) of that phenomenon. (Not that I'm making a case for it.)

**Comment by QuickBASIC** [comment]
I understand, Google+ and Twitter because they help tremendously with SEO and maybe Facebook for the average Joe, but Instagram is probably pointless.

**Comment by rehrar** [comment]
I'm telling you guys, Snapchat is where it's at. But seriously, if this is not something to spend time on, then let's forget about the unnecessary ones.

**Comment by anonimal** [comment]
>help tremendously with SEO

How exactly?

Btw, I've never heard of a google+ monero until you told me, and there are only 112 people in the group.

>Facebook for the average Joe

I thought that's what reddit was for?

Do we know anyone who is excited/adamant about actively maintaining either of these accounts?

**Comment by QuickBASIC** [comment]
> I've never heard of a google+ monero until you told me

I didn't know there was an existing page. It helps with SEO in a lot of subtle ways; Links posted on a Google+ page get indexed quicker so will show up in searches sooner, Google+ pages allow you to post a lot of easily indexable information that can link to other profiles or communities and tend help those links rank higher in search results. 

> I thought that's what reddit was for?

I don't think so. I have a relatively large circle of friends and colleagues and the majority of them use Facebook, Twitter, and Instagram to get information in a syndicated fashion and Snapchat, Kik, iMessage, Messenger for communication. I would say that the majority of them have not heard of Reddit.

**Comment by anonimal** [comment]
>Google+
>Facebook

These two [robber barons](https://en.wikipedia.org/wiki/Robber_baron_(industrialist)) have acquired their power because of arguments like the aforementioned. Suggesting that people use google and/or facebook, in order to advance their position, is not a pro-privacy initiative and, IMHO, not in the best interest of Kovri (e.g., feeding the beast which bites our hand is not in our best interest). Now, if we did something which increased SEO for DuckDuckGo, then I'm on-board (with a DuckDuckGo-only solution).

Note: it's unfortunate that google has cataloged a "best of coder habits" over the years when concocting their style guides - otherwise kovri wouldn't use their style guides.

>>Do we know anyone who is excited/adamant about actively maintaining either of these accounts?

Nothing is stopping anyone from creating unofficial community pages. As for the community to pay me or rehrar to maintain accounts on google+ or facebook, I think that's out of the question.

**Comment by erciccione** [comment]
I don't see the point of a Snapchat or Instagram account

>These two robber barons have acquired their power because of arguments like the aforementioned

Can't agree more. These companies base their power over a monopoly that they are enforcing, we are fighting this claiming our right of privacy. If the price is a bad SEO (on Google) I think we should pay it.
>Nothing is stopping anyone from creating unofficial community page

+1, and I'm sure when Kovri gains in popularity this will happen quite soon, but these accounts won't be bond to the Kovri team

**Comment by ArticMine** [comment]
> Nothing is stopping anyone from creating unofficial community pages. As for the community to pay me or rehrar to maintain accounts on google+ or facebook, I think that's out of the question.

+1 I agree. 

Facebook's entire business model is based upon surveillance capitalism. Google can be used  privately provided one does not sign in and uses a private browser session. This of course precludes Google+

**Comment by QuickBASIC** [comment]
> I don't see the point of a Snapchat or Instagram account

Park the name to limit trolling. That's the only reason I suggested it.
