### ISSUE TITLE
Build: OpenBSD dynamic build failing for Kovri 

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#118]
```
CMake Error at /usr/local/share/cmake/Modules/CMakeDetermineCCompiler.cmake:57 (message):
  Could not find compiler set in environment variable CC:

  clang38.
Call Stack (most recent call first):
  CMakeLists.txt:8 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

https://build.getmonero.org/builders/kovri-all-openbsd-amd64/builds/247/steps/compile/logs/stdio

**Comment by anonimal** [comment]
@danrmiller I also still can't login to the machine. pings sent through IRC, not sure if you've ever received them.

**Comment by danrmiller** [comment]
Previously this used a separate build job that set the speficic options the openbsd job needed, but eventually the BSD builds didn't need anything individual from each other so I set them all to use the same job. 

What I missed was on this machine clang 3.8.0 is at ```/usr/local/bin/clang-3.8``` while on the other BSDs we build for its at ```/usr/local/bin/clang38``` so I just symlinked it here.

There is a new address for you to connect to the openbsd testing machine, catch me on IRC.

**Comment by danrmiller** [comment]
+ resolved

https://build.getmonero.org/builders/kovri-all-openbsd-amd64/builds/288

**Comment by danrmiller** [comment]
+resolved

**Comment by anonimal** [comment]
Thanks @danrmiller
