### ISSUE TITLE
Monero Coffee Chat: 7 October 2017 16:00 UTC

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/meta#123]
**Introduction**

Announcing the first ever live Monero Coffee Chat!

![Monero Coffee Chat](https://i.imgur.com/7G4Powo.png)

This monthly meeting will feature longtime active members of the Monero community, who will answer questions from others. It will be loosely organized, and it will run about one hour.

This meeting hopes to make the community more accessible and open.  It will also serve as a medium to communicate the latest and upcoming developments.

Since this is the first meeting, we would love to hear suggestions (including on the name).  It's with your help that these meetings can be worth everyone's time.

**Location**

[YouTube Livestream](https://www.youtube.com/watch?v=Xf4FOwun6Fk) with [Jitsi](https://jitsi.org), a free open-source video conferencing tool

**Time**

[Use this timezone calculator to convert UTC to your time zone](https://www.timeanddate.com/worldclock/converter.html?iso=20171007T160000&p1=tz_et&p2=28&p3=111&p4=49&p5=179&p6=70&p7=224&p8=48&p9=136).

UTC 16:00
ICT (Bangkok) 23:00
EDT (New York) 12:00 noon
CDT (Chicago/Dallas) 11:00
PDT (San Francisco) 09:00
EEST (Bucharest) 19:00
CSET (Brussels) 18:00
BST (London) 17:00

**Comment by binaryFate** [comment]
+1 for Bluejeans (iirc it was the one used for the Kovri / Monero chat in August, was good).   

For the name, I suggest "Monero Coffee Time" which rolls better than "hour", and we may one day decide to do it for more or less than an hour.

**Comment by bigreddmachine** [comment]
Just to add a bit, you can still record and post to YouTube for future viewers. Could probably even simulcast, though less certain about that.

+1 on @binaryFate's idea for name, hadn't thought about the "hour" bit being taken too literally.

**Comment by binaryFate** [comment]
Or "Monero Coffee Break"? Because the rest of the time, everyone's busy as hell.

**Comment by SamsungGalaxyPlayer** [comment]
@anonimal @binaryFate Thoughts on [Jitsi](https://jitsi.org/)? It's also free and has the same features. We can use that instead.

Otherwise, I will pay for a BlueJeans subscription.

**Comment by ArticMine** [comment]
Jitsi sounds to me at first glance like the best choice so far. None of the spying with something like Google hangouts. BlueJeans would be my second choice since it requires a centralized paid server.

**Comment by anonimal** [comment]
I haven't used Jitsi in a long time, and never for a conference call. If it is functional and reliable for conference calls, then 👍 for Jitsi.

**Comment by anonimal** [comment]
Re: title/name, how about "The Monero [insert Esperanto word for 'coffee'] Roundtable"? Roundtable is too decisive?

**Comment by gaspard** [comment]
So how does this works ? Are there any explanations on how to use jitsi for a "hangout" ?

**Comment by SamsungGalaxyPlayer** [comment]
@gaspard we will speak on Jitsi, which will be livestreamed to YouTube. People can then comment and ask questions on YouTube

**Comment by johnking7** [comment]
@SamsungGalaxyPlayer - Haven't used Jitsu before - looks like we will need a URL to connect to?

**Comment by SamsungGalaxyPlayer** [comment]
Recording: https://youtu.be/EcKgnjqSXpA
