### ISSUE TITLE
Monero Coffee Chat: 4 November 2017 15:00 UTC

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/meta#127]
![Monero Coffee Chat](https://i.imgur.com/7G4Powo.png)

**Introduction**

This monthly meeting will feature longtime active members of the Monero community, who will answer questions from others. It will be loosely organized, and it will run about one hour.

This meeting hopes to make the community more accessible and open.  It will also serve as a medium to communicate the latest and upcoming developments.

**Location**

**[YouTube Livestream](https://www.youtube.com/watch?v=CoY60a_qhPg)** with [Jitsi](https://jitsi.org), a free open-source video conferencing tool

**Time**

The date and time are subject to change.

[Use this timezone calculator to convert UTC to your time zone](https://www.timeanddate.com/worldclock/converter.html?iso=20171104T150000&p1=tz_et&p2=28&p3=111&p4=49&p5=179&p6=70&p7=224&p8=48&p9=136).

UTC 16:00
ICT (Bangkok) 22:00
EDT (New York) 11:00
CDT (Chicago/Dallas) 10:00
PDT (San Francisco) 08:00
EEST (Bucharest) 18:00
CSET (Brussels) 17:00
BST (London) 16:00

**Proposed Agenda**

Monero Coffee Chats intend to be casual and encourage free flows of thought. Nevertheless, the meeting will be guided by the following topics:

1. How people can contribute
2. Current initiatives and progress
3. Future developments
4. Research lab "office hours"
5. Guiding philosophies

**Comment by h173k** [comment]
When LN for XMR?

**Comment by SamsungGalaxyPlayer** [comment]
Click on the YouTube livestream to view the event.
