### ISSUE TITLE
Dev Meeting: October 22nd, 2017, 17:00 UTC

### ISSUE THREAD

**Issue by rehrar** [monero-project/meta#128]
# UPDATE!
Lots of merging and fixing going on during the day and time of the meeting (super exciting stuff actually, check it out), so the meeting is rescheduled to one week after its intended time. We are sorry for any inconvenience.

### Location
- [Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | [Slack](https://monero.slack.com/) | Irc2P | [Mattermost](https://mattermost.getmonero.org)
  - #monero-dev

### Time

Use the [timezone converter](https://www.timeanddate.com/worldclock/converter.html?iso=20171022T170000&p1=tz_gmt&p2=tz_et&p3=28&p4=111&p5=49&p6=179&p7=70&p8=224&p9=48) to see when the meeting is for you.

### Proposed Meeting Items
1. Greetings
2. Brief review of what's been completed since the previous meeting
3. Code + ticket discussion / Q & A
4. Any additional meeting items
5. Confirm next meeting date/time

*Notes:*
- Given that workgroups are starting to hold their own meetings, we will no longer be relaying between channels. Please make an effort to attend all meetings relevant to you. Monero contributors should at least try attend the Kovri meeting in #kovri-dev immediately after this one.
- Meeting log will be posted to [https://getmonero.org/blog/tags/dev%20diaries](https://getmonero.org/blog/tags/dev%20diaries)

**Comment by michaesc** [comment]
Hi rehrar,

The rescheduling threw me off, so my chance of attending is less than 100%. If I'm able to be here, it would be great to take one minute and decide the question:

> Should regular hardware development reporting and discussion be part of #monero-dev (biweekly meetings), #monero-community (biweekly meetings), or something else?

There is already a #monero-hardware IRC channel and Mattermost bridge. The FFS specifies reporting in the developer meetings, but there has been considerable interest in the community meetings.

This question needs to be part of a meeting minutes, to satisfy the FFS proposal terms.

---

If there's extra time and interest, obviously we hardware devs have other things to report as well.
