### ISSUE TITLE
Kovri: cache/upload PR'd dynamic builds on ARMv7/8 machines

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#129]
Similar to [monero's build](https://build.getmonero.org/downloads/monero-5609b35-linux-armv7.tar.gz), if we can afford the disk space then doing this will save time and help with testing.

**Comment by danrmiller** [comment]
Wouldn't you want static builds for this? What machines are you going to test these on, what are the shared libs setup on those?

**Comment by anonimal** [comment]
The same machines they are built on. If we don't cache then I end up spending up to X hours re-building to test a PR.

**Comment by danrmiller** [comment]
All set. See https://build.getmonero.org/builders/kovri-all-ubuntu-arm7/builds/504 and https://build.getmonero.org/builders/kovri-all-debian-arm8/builds/515 for examples.

**Comment by anonimal** [comment]
Thank you @danrmiller !

**Comment by anonimal** [comment]
Thank you @danrmiller !
