### ISSUE TITLE
Taiga integrations localhost is funky

### ISSUE THREAD

**Issue by michaesc** [monero-project/meta#131]
To reproduce:

Click 'Admin'
Click 'Integrations'
Click 'Github'
Find 'Payload URL'

Problem:

Payload URL shows 'localhost' but it should be taiga.getmonero.org or something public, shouldn't it?

In other words, how can this feature be used while the hostname states 'localhost'?

**Comment by danrmiller** [comment]
I'll take a look, but in the meantime, why don't you just change the URL to http://taiga.getmonero.org/api/v1/github-hook?project=11

**Comment by danrmiller** [comment]
Thanks. Looks like it works now.  

I added ```SITES["api"]["domain"] = "taiga.getmonero.org"``` to settings/local.py.

**Comment by danrmiller** [comment]
+resolved
