### ISSUE TITLE
Buildbot fails kovri-all-win32

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#135]
Apparently buildbot(?) is not running `ar` and `ranlib` for libcryptopp.a so, when the kovri cmake recipe is built, the cryptopp lib is not available: "Could not find Crypto++". Then build is successful when logging onto the same machine and building manually.

https://build.getmonero.org/builders/kovri-all-win32/builds/665

**Comment by danrmiller** [comment]
Sorry, I didn't see this until now. Here is some more info, why do you think its not finding Crypto++? 

https://build.getmonero.org/builders/kovri-all-win32/builds/685
I modified the job so it dies on the exit code 1 from cmake not finding Crypto++.  
I also set the VERBOSE environment variable so you can see how its building cryptopp.
And I made it highlight the CMakeOutput.log so we can see if a clue is in there:

https://build.getmonero.org/builders/kovri-all-win32/builds/685/steps/compile/logs/CMakeOutput.log

**Comment by danrmiller** [comment]
That job was running via bash, I don't know why, I've switched it to just let buildbot exec make like all the other jobs and it seems to work

https://build.getmonero.org/builders/kovri-all-win32/builds/686

**Comment by anonimal** [comment]
Thank you for figuring this out and resolving!
