### ISSUE TITLE
Customisations requested to Kastelo repository

### ISSUE THREAD

**Issue by michaesc** [monero-project/meta#136]
Our new repository is in use, but not yet customised. Please help us fine tune:

- [x] Remove 'Projects' from the tab bar (next to 'Code', 'Issues', 'Pull Requests', ...)
- [x] Remove 'Wiki' from the tab bar (next to 'Code', 'Issues', 'Pull Requests', ...)
- [ ] Add a IRC web hook to log Kastelo commits to #monero-hwcode
- [ ] Add a Taiga web hook as directed by https://tree.taiga.io/support/integrations/github-integration/#second:-configure-webhooks-in-your-github-repository

Our web hook 'Payload URL' is http://taiga.getmonero.org/api/v1/github-hook?project=9
~~Contact Michael to learn the web hook secret key, please.~~
Choose any secret key you want of the form [0-9A-Fa-f]{32} and tell it to Michael in a separate channel. By the way, the regular expression just indicated produces a secret of the type 51bb2f00d1234ABcd900bD00D4422998, where upper and lower case holds meaning.

- [x] Lastly, while many like the name Sekura it sounds too similar to a protocol used in Kovri. So please rename this repository from 'sekura' to **'kastelo'**.

**Q:** Why remove 'Projects' and 'Wiki'? **A:** Because we're using the Taiga system for those things.

Thank you!

**Comment by anonimal** [comment]
@michaesc Thank you for opening this issue (note: 'future' protocol).

@fluffypony @luigi1111 if you wouldn't mind, while you're here; referencing #77 and #78.

**Comment by michaesc** [comment]
@anonimal What is the name of the _future protocol_ again? I've forgotten.

@anonimal And especially thanks for informing us about adding proper information, which should read:

**Description:** The Monero hardware wallet is a printed circuit board design. It may credit card sized and composed of fewer (broader developer reach) or more (optimal electronic density) substrate layers.

**Website:** https://taiga.getmonero.org/project/michael-rfc-hwallet-1-implementation/

**Topics:** Whatever common topics are decided in #77 as well as these unique ones:

- hardware
- wallet

It seems adding topics is explained [here](https://help.github.com/articles/classifying-your-repository-with-topics/).

**License:** It seems there's a place in the GitHub config for license? If so, ours is [CERN OHL](https://github.com/monero-project/sekura/blob/master/LICENSE).

@anonimal Would you please indicate how to configure a 'GitHub webhook IRC notification' as you mention in #77? I think we want that as well, and it should refer to #monero-hwcode.

**Comment by michaesc** [comment]
Any chance of having our repository name corrected before our team meeting later this week?

**Comment by michaesc** [comment]
@luigi1111 @fluffypony We just got our USB PID assignment denied, because our repository name is instable. We worked hard to submit for this assignment, and it's quite a setback for the firmware effort.

https://github.com/pidcodes/pidcodes.github.com/pull/293#issuecomment-360561141
https://github.com/pidcodes/pidcodes.github.com/pull/293/commits/90f8ff08a757d3579c9b7d80d6933c60e7d705e5

**Comment by luigi1111** [comment]
Hi @michaesc sorry for the delay. @fluffypony is the one that makes changes using the monero-project account. I've pinged him out-of-band as I know he's been traveling.

**Comment by michaesc** [comment]
Hi @luigi1111 and @fluffypony, thanks for the great administration so far. In our new Kastelo repository let's:

- [ ] Correct the description to **The Monero Hardware Wallet**
- [ ] Correct the **IRC commit feed #monero-hwcode** which worked before the Sekura name change
- [ ] Fill in the _website_ field to **https://taiga.getmonero.org/project/michael-rfc-hwallet-1-implementation/**
- [ ] Add a **Taiga web hook** to GitHub events, this is really easy (see above for information)
- [ ] Have a well deserved coffee :coffee: break (or :beer: + :pizza: ?)

We're just a few weeks from the conclusion of RFC-HWALLET-1, which requires some of these things. Thanks again!

**Comment by anonimal** [comment]
>Correct the IRC commit feed #monero-hwcode which worked before the Sekura name change

This may be related https://github.com/monero-project/meta/issues/183.

**Comment by michaesc** [comment]
Any chance at eliminating the **low hanging fruit** at least?

- [ ] Fill in the website field to http://kastelo.org/
- [ ] Correct the description to The Monero Hardware Wallet
- [ ] Fill in topics: monero, cryptocurrency, blockchain, privacy, finance, hardware, wallet

**Comment by nahuhh** [comment]
@michaesc  can this be closed

**Comment by michaesc** [comment]
> @michaesc can this be closed
>
I think it should be closed. The requested customisations are still incomplete, and have not been done. But it seems so unlikely that a person with access to the repository will implement them, that I think it should be closed.

Thanks @nahuhh for suggesting this.
