### ISSUE TITLE
Community Meeting: 25 November 2017 17:00 UTC

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/meta#137]
**Location**

[Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | [Mattermost](https://mattermost.getmonero.org) | [Slack](https://monero.slack.com/) | Irc2P

Please PM [SGP on Reddit](https://www.reddit.com/message/compose/?to=SamsungGalaxyPlayer&subject=Monero%20Slack%20invite%20(from%20GitHub)&message=Hello%20please%20send%20a%20Monero%20Slack%20invite%20to%20the%20following%20email:) with your email for a Slack invite.

 - `#monero-community`

**Time**

[Use this timezone calculator to convert UTC to your time zone](https://www.timeanddate.com/worldclock/converter.html?iso=20171125T170000&p1=tz_et&p2=28&p3=111&p4=49&p5=179&p6=70&p7=224&p8=48&p9=136).

UTC 17:00
ICT (Bangkok) 24:00 midnight
EDT (New York) 12:00
CDT (Chicago/Dallas) 11:00
PDT (San Francisco) 9:00
EEST (Bucharest) 19:00
CSET (Brussels) 18:00
BST (London) 17:00

**Proposed Meeting Items**

0. Introduction
1. Greetings
2. Community highlights
3. FFS updates
     a. RFC-HWALLET-1 project progress
     b. Monero Integrations
4. Discuss formation of Malware Response Workgroup
5. Monero Coffee Chat
6. Open ideas time
7. Confirm next meeting date/time
8. Conclusion

**Comment by fluffypony** [comment]
Please add a discussion item:

- Discuss formation of Malware Response Workgroup

I’ll write an issue up when I get a moment, and will also invite @tuckerpreston to participate so we get support from external botnet / malware watch groups and researchers.

**Comment by SamsungGalaxyPlayer** [comment]
@fluffypony done

**Comment by SamsungGalaxyPlayer** [comment]
@fluffypony I'm checking in to make sure that someone is still interested in discussing this during the meeting tomorrow.

**Comment by fluffypony** [comment]
@SamsungGalaxyPlayer sorry I missed the meeting - was in a plane; can we move it to the next one?

**Comment by SamsungGalaxyPlayer** [comment]
@fluffypony done https://github.com/monero-project/meta/issues/141
