### ISSUE TITLE
Community Meeting: 9 December 2017 17:00 UTC

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/meta#141]
**Location**

[Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | [Mattermost](https://mattermost.getmonero.org) | [Slack](https://monero.slack.com/) | Irc2P

Please PM [SGP on Reddit](https://www.reddit.com/message/compose/?to=SamsungGalaxyPlayer&subject=Monero%20Slack%20invite%20(from%20GitHub)&message=Hello%20please%20send%20a%20Monero%20Slack%20invite%20to%20the%20following%20email:) with your email for a Slack invite.

 - `#monero-community`

**Time**

[Use this timezone calculator to convert UTC to your time zone](https://www.timeanddate.com/worldclock/converter.html?iso=20171209T170000&p1=tz_et&p2=28&p3=111&p4=49&p5=179&p6=70&p7=224&p8=48&p9=136).

UTC 17:00
ICT (Bangkok) 24:00 midnight
EDT (New York) 12:00
CDT (Chicago/Dallas) 11:00
PDT (San Francisco) 9:00
EET (Bucharest) 19:00
CET (Brussels) 18:00
UTC (London) 17:00

**Proposed Meeting Items**

0. Introduction
1. Greetings
2. Community highlights
3. FFS updates
     a. RFC-HWALLET-1 project progress
     b. Monero Video Series, comments on [final script](https://github.com/alvinjoelsantos/promo-video/blob/master/community.md)
4. Discuss formation of [Malware Response Workgroup](https://mattermost.getmonero.org/monero/channels/monero-malware-respon)
5. TBA
6. Open ideas time
7. Confirm next meeting date/time
8. Conclusion

**Comment by alvinjoelsantos** [comment]
@SamsungGalaxyPlayer could you include this item for FFS updates:

b. Monero Video Series, comments on [final script](https://github.com/alvinjoelsantos/promo-video/blob/master/community.md)

**Comment by SamsungGalaxyPlayer** [comment]
@alvinjoelsantos done

**Comment by anonimal** [comment]
Could someone add an agenda item re: solving the fireice problem? I don't think I can make the meeting but I wish you all well.

**Comment by mattcode55** [comment]
@anonimal For those out of the loop, what's the fireice problem?

**Comment by anonimal** [comment]
@mattcode55 He's a problem contributor / borderline malicious contributor. I or someone else can fill you in if needed.

**Comment by emesik** [comment]
The times for Europe are correct, however the timezones should be:

* Brussels: CET,
* Bucharest: EET,
* London: UTC

It's winter and Europe is not in the *daylight saving time* lunacy ATM.

**Comment by erciccione** [comment]
Can we remove the 1 hour limitation for this meeting and the future ones? I feel like many times discussions have been cut because of this limit, and this meeting in particular will be rich of subjects to discuss.

**Comment by fluffypony** [comment]
I don’t think that cutting the time limit is a good idea. Some discussions can be pushed to after the meeting, otherwise people that make time in their day to be there will leave or not attend at all.

**Comment by erciccione** [comment]
The problem is that sometimes the discussion is pushed after the meeting, but then, if the discussion really happens, it's usually not participated and without the initial enthusiasm. That makes the discussion weak and not definitive.
>people that make time in their day to be there will leave or not attend at all

Agree, we need to find a middle way. Maybe making the duration flexible depending by the amount of subjects? The estimated duration could be determinated at the moment the issue is opened, so anybody can organize their time before the meeting. Maybe with a maximum limit of 1h30min instead of 1h

**Comment by dewdeded** [comment]
A hard stop for the meeting isn't needed. Maybe 10 till 25 more mins, if there is demand, could be added as bonus. So there would be less time pressure and no hard cut of ongoing discussions.

**Comment by SamsungGalaxyPlayer** [comment]
@erciccione @fluffypony @dewdeded let's have the next one go on for an hour and a half, with the first hour to discussion topics and the remaining half hour to open ideas time (which often gets skipped or cut short).
