### ISSUE TITLE
Kovri: Configure buildbot to post coverage info to coveralls.io

### ISSUE THREAD

**Issue by danrmiller** [monero-project/meta#15]
Post json coverage data with the kovri repo token to coveralls as a buildstep in the kovri build factories on buildbot.

**Comment by anonimal** [comment]
This was resolved for kovri (afaict, yes?). Should this issue be extended to monero too?

**Comment by anonimal** [comment]
Is this issue still applicable?

**Comment by danrmiller** [comment]
Resolved. https://coveralls.io/github/monero-project/kovri

Monero testing has several steps to be completed, like the libwallet environment, before adding coveralls.

**Comment by anonimal** [comment]
Oops, I wasn't clear: I meant applicable for Monero.
