### ISSUE TITLE
Kovri: buildbot armv8 download now points to arm8

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#152]
Unbeknownst to me, https://build.getmonero.org/downloads/kovri-latest-linux-armv8.tar.bz2 is now 404 but https://build.getmonero.org/downloads/kovri-latest-linux-arm8.tar.bz2 is not. Which one are we sticking to? I'd prefer the original armv8.

**Comment by danrmiller** [comment]
OK I found where that was coming from, new ones will correctly be armv8.

**Comment by anonimal** [comment]
Thanks @danrmiller
