### ISSUE TITLE
Buildbot: OSX 10.13?

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#153]
Are there plans to upgrade the build system?

**Comment by danrmiller** [comment]
Yes we'll replace to 10.10 box with 10.13

**Comment by danrmiller** [comment]
Thanks @fluffypony for getting this up. 

https://build.getmonero.org/builders/kovri-all-osx-10.13/builds/1

https://build.getmonero.org/builders/monero-static-osx-10.13/builds/1

@anonimal see me on irc for testing access

**Comment by danrmiller** [comment]
+resolved

**Comment by anonimal** [comment]
Thank you @danrmiller, thank you @fluffypony.
