### ISSUE TITLE
Kovri: buildbot and/or backend is not linking openssl statically for win build

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#154]
As detailed in https://github.com/monero-project/kovri/issues/711, we now have 3 confirmations that buildbot or something backend-related is preventing the windows static build from statically linking openssl.

**Comment by anonimal** [comment]
On successful build machine:

`/C/msys64/mingw64/lib/libssl.a /C/msys64/mingw64/lib/libcrypto.a`

On [buildbot](https://build.getmonero.org/builders/kovri-static-win64/builds/362/steps/compile/logs/stdio):

`/C/msys64/mingw64/lib/libssl.dll.a /C/msys64/mingw64/lib/libcrypto.dll.a`

@danrmiller how was openssl built on the build machine?

**Comment by danrmiller** [comment]
/C/msys64/mingw64/lib/libssl.dll.a and /C/msys64/mingw64/lib/libcrypto.dll.a don't belong to the packages according to pacman -Qo, so I moved them away and ran a new build:

https://build.getmonero.org/builders/kovri-static-win64/builds/388

**Comment by anonimal** [comment]
Resolved! Thank you @danrmiller
