### ISSUE TITLE
Build: Ubuntu64: virtual memory exhausted: Cannot allocate memory

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#16]
Despite ~3GiB unallocated memory, buildslave is not releasing ~80% of swap while idle(?) (not currently building anything according to top). As a result, attempting to build kovri with gcc for testing results in OOM.

I can use clang for now, but can we still up the swap (or find another solution)?

**Comment by danrmiller** [comment]
for now i restarted the buildslave which freed it but we can talk about another solution if it happens again.

@linux64:~$ free
              total        used        free      shared  buff/cache   available
Mem:        3080680      282464     2295032        2100      503184     2623268
Swap:       2097148       17504     2079644

**Comment by anonimal** [comment]
Thanks @danrmiller. I'll reopen if this becomes an issue again.
