### ISSUE TITLE
Buildbot: Win32: No space left on device

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#172]
`C:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: final link failed: No space left on devicemake[3]: Leaving directory '/home/buildbot/slave/kovri-all-win32/build/build'`

https://build.getmonero.org/builders/kovri-all-win32/builds/786/steps/compile%20tests/logs/stdio

**Comment by danrmiller** [comment]
OK fixed, thanks.
