### ISSUE TITLE
Buildbot: debian-armv8 machine is offline

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#177]
and has been for a while now. Ticketing for housekeeping.

**Comment by danrmiller** [comment]
we had a hardware failure and its now been replaced

**Comment by anonimal** [comment]
I see that it's back online https://build.getmonero.org/builders/kovri-all-debian-arm8/builds/599/steps/compile/logs/stdio but needs more configuring. I also can't connect to the onion, I don't know if that's related.

**Comment by danrmiller** [comment]
Yes that log is from before everything was installed yes. I thought you told me on irc you could get to the new onion. If you still can't, talk to me there.

**Comment by anonimal** [comment]
You gave me a new onion that I was assuming was for the very out of date rpi3 (that was the context of conversation). The new armv8 onion works, I'll rewrite my aliases.

Thanks for fixing.

**Comment by anonimal** [comment]
Last build was Feb 24th https://build.getmonero.org/builders/kovri-all-debian-arm8/builds/601

**Comment by danrmiller** [comment]
The static build works https://build.getmonero.org/builders/kovri-static-debian-arm8/builds/350

The dynamic build works for me from a bash shell, but from buildbot we get this error:

```
g++ -march=native -DCRYPTOPP_NO_CPU_FEATURE_PROBES=1 -march=armv8.4-a+crypto -c sm4-simd.cpp
Assembler messages:
Error: unknown architecture `armv8.4-a+crypto'

Error: unrecognized option -march=armv8.4-a+crypto
GNUmakefile:1153: recipe for target 'sm4-simd.o' failed
```
https://build.getmonero.org/builders/kovri-all-debian-arm8/builds/605/steps/compile/logs/stdio

The difference is buildbot is running make via execv not a shell. Is there an environment variable we need to set or do you have any other ideas?
