### ISSUE TITLE
Buildbot: onion updates + restarts

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#178]
I've only been able to consistently reach the following build machines:

- Linux32/64
- FreeBSD
- OS X 10.12
- Cubieboard2

The remaining build machines are unavailable:

- OS X 10.10
- OS X 10.11
- ARMv7
- ARMv8 (which is currently [offline](https://github.com/monero-project/meta/issues/177))
- DragonflyBSD
- OpenBSD

The Tor versions are also out of date, some very out of date.

**Comment by danrmiller** [comment]
I'll look at this tomorrow.

* You should be able to get to the armv7 machine over tor now, let me know on IRC if not.
* Do you need the osx 10.10 machine? I'm trying to get @fluffypony to replace it with a 10.13 box.

**Comment by anonimal** [comment]
>I'll look at this tomorrow.

Thanks Dan.

>You should be able to get to the armv7 machine over tor now, let me know on IRC if not.

Awesome, works now, thanks.

>Do you need the osx 10.10 machine? I'm trying to get @fluffypony to replace it with a 10.13 box.

Not particularly, other than to keep the OS X builds in the green. I'm assuming any fixes I make to 10.11/10.12 should apply to 10.10. If not, and if we'll get [10.13](https://github.com/monero-project/meta/issues/153) soon, then I don't need access.

**Comment by danrmiller** [comment]
@anonimal you should now be able to access the osx 10.11 box via tor as well.

**Comment by anonimal** [comment]
Yes, thanks. I still can't connect to the BSDs though. Everything else that is online I can connect to.

**Comment by anonimal** [comment]
@danrmiller Please, I need to do BSD development.

**Comment by anonimal** [comment]
An updated list of the machines that I still cannot SSH into:

- ARMv8 (which is currently [offline](https://github.com/monero-project/meta/issues/177))
- macOS 10.12
- FreeBSD
- OpenBSD
