### ISSUE TITLE
Cubieboard2: upgrade to latest LTS image

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#180]
We are currently using ARMBIAN Ubuntu 14.04.5 LTS. I see that [this](https://dl.armbian.com/cubieboard2/Ubuntu_xenial_default_desktop.7z) is available (as is [this](https://dl.armbian.com/cubieboard2/Debian_stretch_next.7z)). Upgrading should resolve the various update/upgrade issues I'm having when trying to install new compilers.

**Comment by danrmiller** [comment]
Having this updated now.

**Comment by danrmiller** [comment]
This is complete, talk to me on IRC.

**Comment by anonimal** [comment]
Received. Thanks Dan!
