### ISSUE TITLE
Buildbot: hardware upgrade wishlist

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#182]
Here we can keep a running tab of any hardware upgrade requests. People can then donate funds or hardware.

**Comment by anonimal** [comment]
I'd personally enjoy much faster ARM builds. Does anyone have their eye on any specific hardware?

**Comment by danrmiller** [comment]
I've started using ccache for the monero arm builds, would you like to do that for kovri for now also?

**Comment by anonimal** [comment]
>would you like to do that for kovri for now also?

If it's worked out well, yes, that sounds great. Thanks.
