### ISSUE TITLE
GitHub notification bot not working in #kovri-dev

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#183]
I've noticed that the github notification bot is sending IRC NOTICEs to `#monero-dev` instead of PRIVMSGs (or the other way around now?...). Coincidentally, `#kovri-dev` has stopped receiving notifications for over a week now.

Did someone change any settings on our end or is this a github issue?

**Comment by anonimal** [comment]
Appears fixed.

**Comment by anonimal** [comment]
Worked for a day or two, hasn't worked since. Works fine for `#monero-dev`.

**Comment by anonimal** [comment]
Anyone? Also referencing #77.

**Comment by selsta** [comment]
Closing. The GitHub IRC notification service has been removed and we run our own bot now.
