### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#191]
This should apply to the entire build system. Ticketing for housekeeping.

Referencing https://github.com/monero-project/monero/issues/2641.

**Comment by SamsungGalaxyPlayer** [comment]
CLI: done
GUI: not yet done

**Comment by TheCharlatan** [comment]
To keep this open and update on progress on the gui build:
Cmake support on the gui build was the primary goal. I initially authored a half-broken pull request to get the ball rolling last year: https://github.com/monero-project/monero-gui/pull/2404 . Its stability has improved greatly thanks to the work of xiphon to the point where its now nearing a usable state. In the meantime I've been working on the repro builds on this branch here: https://github.com/TheCharlatan/monero-gui/tree/dependsQtSub . I'm stuck at the moment with building qt with open gl support. Once that hurdle is overcome, I think it won't be too much work to get to a fully reproducible release.

**Comment by sanecito** [comment]
Thanks for the update @TheCharlatan! Perhaps a silly question, but have you asked on the reproducible-builds.org mailing list for advice (haven't seen anything in the last two months in subject concerning Qt/OpenGL/Monero/your handle)?

**Comment by TheCharlatan** [comment]
I have not worked on the problem in the past few months, but I think this is rather something for the qt forums.

**Comment by carrington1859** [comment]
https://github.com/monero-project/monero-gui#compiling-the-monero-gui-from-source

Is it correct to say we now have reproducible builds for the GUI on everything other than Android?

**Comment by selsta** [comment]
No. macOS isn't reproducible. Not sure about android.

**Comment by plowsof** [comment]
what steps are required to solve the reproducible issues for the GUI? (we at least have a reproducible 'installer' .exe https://github.com/plowsof/monero-gui-exe

**Comment by selsta** [comment]
Let's keep track of the GUI reproducible build status in the GUI repo.
