### ISSUE TITLE
Name the 1st quarter 2018 release

### ISSUE THREAD

**Issue by fluffypony** [monero-project/meta#193]
We have to make a call pretty quickly, as we all TOTALLY forgot about this. I'll close this in the next 24 hours or so and take stock of the choice with the greatest support.

So the next element in the list is Lithium, which gives us the following options:

Lithium Lagoon Nebula
Lithium Large Magellanic Cloud
Lithium Leo Triplet
Lithium Lindsay-Shapley Ring
Lithium Little Dumbbell Nebula
Lithium Lost
Edit to add: Lithium Luna

For those unfamiliar with the naming convention, here is the relevant doc: https://github.com/monero-project/meta/blob/master/NAMING.md

**Comment by ordtrogen** [comment]
"Lithium lost"     (KISS principle ... )

**Comment by sneurlax** [comment]
Lithium Lost

**Comment by alvinjoelsantos** [comment]
Lithium Lost

**Comment by serhack** [comment]
Lithium Lost

**Comment by rbrunner7** [comment]
Well, don't want to boast, but I did bring it up at the last dev meeting. Somebody proposed *Lithium Luna*, and I like it, as did one or two other people in the meeting.

Does anything speak against simply the moon as the "thing" from astronomy, does it have to be a galaxy, a nebula or similar?

**Comment by Rafficer** [comment]
Lithium Lost

Everything else is too long.

**Comment by 4matter** [comment]
Lithium Lost

**Comment by cryptochangements34** [comment]
I like Lithium Luna, which was mentioned at the dev meeting last week

**Comment by Starmute** [comment]
I support Lithium Luna

**Comment by fluffypony** [comment]
I've added Lithium Luna to the list

**Comment by dnaleor** [comment]
Lithium Luna, +1

**Comment by curumimxara** [comment]
Lithium Luna

**Comment by 7dNp8xK3Ed** [comment]
Lithium Luna +1

**Comment by anonimal** [comment]
~~[Lithium Chemtrails](https://www.naturalnews.com/055183_chemtrails_NASA_lithium.html)~~. Lithium Luna. To the moon.

**Comment by Lafudoci** [comment]
Lithium Luna, +1

**Comment by antanst** [comment]
Lithium Luna

**Comment by defterade** [comment]
Lithium Luna

**Comment by xmronadaily** [comment]
Lithium Luna! on a dailyyyyyyyy basis bb pls.

**Comment by luigi1111** [comment]
Lithium Luna to the moona.

**Comment by dEBRUYNE-1** [comment]
Lithium Luna

**Comment by M5M400** [comment]
Since "Lithium RIP ASICS" is not an option, I vote for Lithium Luna.

**Comment by el00ruobuob** [comment]
Lithium Lobster (Nebula)
Lobster Nebula is the other name of Horseshoe, if i can trust wikipedia on that.

**Comment by MaxXor** [comment]
Lithium Luna
Lithium Liberty

**Comment by DiMiTri101** [comment]
Lithium Luna

**Comment by NebelMe** [comment]
Lithium Lost absolutely.

**Comment by hyc** [comment]
I guess we have to loosen "galaxies" to "any celestial object" but I like Lithium Luna too

**Comment by pierce403** [comment]
Can't pass up this chance to call it "Lithium Flower" :-)

https://www.youtube.com/watch?v=kG2R8LqnLOs

**Comment by ficusplant** [comment]
Lithium Lagoon Nebula

**Comment by jholmes91** [comment]
Lithium Luna

**Comment by TheFuzzStone** [comment]
Lithium Luna

**Comment by LukasRada** [comment]
Lithium Luna

**Comment by quarkxpress** [comment]
Lithium Pancake

**Comment by rehrar** [comment]
@hyc We should be careful about allowing 'any' heavenly bodies, or we'll end up with Rhodium Rehrar. ;)

*ahem* Lithium Luna.

**Comment by sammy007** [comment]
![](https://nerdygirlnotes.files.wordpress.com/2013/09/louis.jpg)

**Comment by givanse** [comment]
meta meta: add a comment with each name idea and people click the thumbs up emoji for the one they like best

**Comment by soldboyes** [comment]
Lithium Lyra

**Comment by hyc** [comment]
Ohhhh I really like that - Lithium Lyra.

**Comment by FelixWeis** [comment]
Lithium Lube

**Comment by hubstef** [comment]
Lithium Lost

**Comment by oliverw** [comment]
"Smoking Ant" 😁

**Comment by dginovker** [comment]
Lithium Lost 100%. Congrats to all the devs and contributors for their hard work!

**Comment by lmsappr** [comment]
The Lithium Labyrinth .    Since you are creating a maze for these damn ASICs.

**Comment by hundehausen** [comment]
Lithium Luna

**Comment by lettemax** [comment]
Lithium Luna

**Comment by MoonGem** [comment]
Cocaine Cowboy

**Comment by sir-lebowski** [comment]
LIthium Leotard

https://www.google.com/search?q=LIthium+Leotard

**Comment by vitorgatti** [comment]
Lithium Luna

**Comment by johnalanwoods** [comment]
Lithium Lost. 🍷

**Comment by rex4539** [comment]
Lithium Luna

**Comment by afighttilldeath** [comment]
Lithium Lost

**Comment by leafcutterant** [comment]
Lithium Luna

**Comment by TeaPanda** [comment]
Lithium Lost

**Comment by erciccione** [comment]
Podium at the moment:

Lithium Luna: **~28**
Lithium Lost: **~13**
Lithium Lyra: **4+1** (I'm the +1)

(I've used both thumbs up and direct votes from this thread)

**Comment by anonimal** [comment]
>(I've used both thumbs up and direct votes from this thread)

Some people are thumbs up'ing the same vote across multiple users. The system's been hacked!

**Comment by garnier77** [comment]
Y'all BITCHES NEED JESUS
LITHIUM LUNA

**Comment by michaelphenderson** [comment]
Lithium Leo Triplet

**Comment by razorman8669** [comment]
Lithium Lost

**Comment by eci4ever** [comment]
Lithium Lost

**Comment by kpxupc** [comment]
Lithium Lost

**Comment by kpxupc** [comment]
McLithium McLithiumface would also be good for me.

**Comment by cAP5L0CK** [comment]
Lithium Luna

**Comment by sanecito** [comment]
While I proposed Lithium Luna in the last dev meeting hoping humorously the IAU had recognized some galaxy or star by that name, searching around that doesn't seem to be the case. Thus, I would like to propose a more appropriate name with respect to schema and Monero's ideology:

Lithium [Libertas](https://in-the-sky.org/data/object.php?id=TYC1058-3400-1)

Libertas meaning 'liberty' in Latin. For more easy future reference the star names that the IAU officially recognizes can be found here:

https://www.iau.org/public/themes/naming_stars/

On a more humorous proposal:

Lithium Lobster (Nebula)

**Comment by QuickBASIC** [comment]
Lead Lesath (Arabic star name 'the sting')... Lead is poison and this release contains a poison sting (for ASIC miners). 😂😂😂

**Comment by nebuwa** [comment]
Lithium Luna

**Comment by peanutsformonkeys** [comment]
Hassium Hawkings

**Comment by SleepswithGators** [comment]
Is that not the nym (Libertas) of the poor fellow that took a good brunt of the traditional witch hunt USA has*(yes not past tense)  with cognitive liberties advocates ?  I mean "ElPresidente" and "Gwern", poor OPSEC?

**Comment by keledoro** [comment]
Lithium Luna

**Comment by jtgrassie** [comment]
Lithium Lyra

**Comment by nasaWelder** [comment]
Lithium Lycanthrope
.... means wherewolf...

**Comment by clausbertels** [comment]
#Lithium Luna

**Comment by juazki** [comment]
Lithium Luna

**Comment by Fozzimoto** [comment]
Lithium Luna

**Comment by SamsungGalaxyPlayer** [comment]
I'm simply copying an idea from [Reddit](https://www.reddit.com/r/Monero/comments/84wjun/name_the_1st_quarter_2018_release/dvt071a/): Lithium Lucasian

**Comment by qxxrbull** [comment]
Lithium Luna

**Comment by fluffypony** [comment]
Lithium Luna it is
