### ISSUE TITLE
Kovri: fix environment for Win/MinGW builds

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#2]
Effects https://github.com/monero-project/kovri/pull/431, build logs [here](https://build.getmonero.org/builders/kovri-all-win64/builds/14/steps/compile/logs/stdio) and [here](https://build.getmonero.org/builders/kovri-all-win32/builds/4/steps/compile/logs/stdio). A fix is currently in-progress, ticketing for housekeeping.

**Comment by danrmiller** [comment]
I added env={'MSYSTEM': "MINGW32"} and env={'MSYSTEM': "MINGW64"} to the respective build factories and run the make command via the mingw bash shell. Mingw32 and mingw64 builds now compile but fail on tests. See 
https://build.getmonero.org/builders/kovri-all-win32/builds/12 and 
https://build.getmonero.org/builders/kovri-all-win64/builds/23

I opened issue #5 to enable tracking these build config changes.

**Comment by anonimal** [comment]
I've pushed a [fix for tests](https://github.com/monero-project/kovri/pull/442/commits/e51e0b274ae5f89ca60c2d0cdf506ba189be3f2e) (not related to environment).  Everything looks great so far :+1: :beers: I'll reopen this issue if needed.
