### ISSUE TITLE
Win32/64: unblock firewall to allow inbound kovri connections

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#21]
I don't have privs so maybe we can pick a designated port or just give me firewall privs? I've left the firewall pop-up open on both instances for review.

**Comment by danrmiller** [comment]
I've made your account an administrator on these machines now, but both are behind NAT, so let me know if you need ports forwarded for this to actually work.

**Comment by anonimal** [comment]
Thanks @danrmiller. Closing since we've worked this out in private.
