### ISSUE TITLE
Buildbot: ubuntu-amd64: downgrade to boost 1.58 (or upgrade beyond 1.59)

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#212]
This is preventing me from testing ~~and merging~~ https://github.com/monero-project/kovri/pull/842 (as well as any other PR) on our build machine. As noted in https://github.com/monero-project/kovri/pull/854#issuecomment-382384102.

**Comment by danrmiller** [comment]
Done.

https://build.getmonero.org/builders/kovri-static-ubuntu-amd64/builds/475

https://build.getmonero.org/builders/kovri-all-ubuntu-amd64/builds/985

**Comment by anonimal** [comment]
Thank you Dan!

JFTR: the docs build error is new but unrelated. I'll open a new kovri issue.
