### ISSUE TITLE
Kovri Defcon meeting: Tuesday, May 29th, 2018, 20:00 UTC 

### ISSUE THREAD

**Issue by rehrar** [monero-project/meta#223]
### Location
- [Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | [Slack](https://monero.slack.com/) | Irc2P | [Mattermost](https://mattermost.getmonero.org)
  - #kovri-dev

### Time

Use the [timezone converter](https://www.timeanddate.com/worldclock/converter.html?iso=20180529T200000&p1=tz_gmt&p2=tz_et&p3=28&p4=111&p5=49&p6=179&p7=70&p8=224&p9=48) to see when the meeting is for you.

### Proposed Meeting Items
1. Greetings
2. Table & Materials discussion
3. Presentation discussion
4. Change Kovri logo to include pug puppy

**Comment by SRCoughlin** [comment]
@rehrar The 29th is a Tuesday.

**Comment by anonimal** [comment]
>4. Change Kovri logo to include pug puppy

lol :rofl:

**Comment by rehrar** [comment]
OH YEAH @SRCoughlin?!?!? Well, alright, it's changed now. Thanks. :)

**Comment by anonimal** [comment]
+resolved
