### ISSUE TITLE
Taiga fails to notify via email

### ISSUE THREAD

**Issue by michaesc** [monero-project/meta#227]
There is no documentation informing of what should happen when _Contact the project_ HTML form button is pressed on Taiga project pages, however common sense indicates that an email should reach the intended recipients who are most likely the project administrators.

If this is the case, then the current Taiga implementation or configuration is flawed.

### Reproduction

To reproduce an error resulting from this flaw:

1) Navigate to the [Vegas Events project](https://taiga.getmonero.org/project/michael-vegas-august-2018/)
2) Click **Contact the project team**
3) Enter a suitable test message (versioned please)
4) Ask any project administrator if they were notified by email

### Assistance

We (the Vegas team) can assist anyone repairing this flaw by making them a project member and raising them to administrator role. Please request this on #monero-community. There are **four** (!) administrators who can assist with testing.

### Related

It's possible that this flaw relates to [the problem](https://github.com/monero-project/meta/issues/131/) we had before regarding a host ACL.

**Comment by sanecito** [comment]
FYI for whoever will work/is working this... I am one of said people and can be reached via saying 'xmrscott' on #monero-community. Other three are msvb-lab, rehrar, and sean

**Comment by anonimal** [comment]
Has this issue been resolved?

**Comment by erciccione** [comment]
I currently receive emails from people clicking the "contact the project button" with no issues (for the monero localizations workgroup), but i also never had this problem in past so....
