### ISSUE TITLE
Kovri Docker Hub Repository

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#228]
The issues presented [here](https://github.com/monero-project/monero/issues/3076) are sound, but the automated build option is useful and kovri can stand to benefit because our testnet is based entirely within docker.

If monero project doesn't want an official Docker Hub (I can understand), I'll go ahead and set this up for an semi-official (in name only)/unofficial kovri.

**Comment by anonimal** [comment]
Pinging @MoroccanMalinois if interested.

**Comment by selsta** [comment]
Closing as Kovri uses its own repo now for issue tracking.
