### ISSUE TITLE
Freenode group registration

### ISSUE THREAD

**Issue by michaesc** [monero-project/meta#231]
The one(s) who administrate #monero on Freenode may register our group, allowing for user cloaking and other useful features typical of any normal online group. Information is available:

https://freenode.net/groupreg

Please establish the request by sending an email to projects@freenode.net and register Monero as a informal group project similar to Wikimedia, Ubuntu, or KDE. Thank you.

**Comment by fluffypony** [comment]
We already submitted to projects@ in November 2017, and also sent a copy to Gareth Pulham. If it hasn’t been effected yet I can chase it up.

**Comment by michaesc** [comment]
It's possible (likely?) that Freenode accepted our registration request from November 2017, so I've asked there if they know of a list or how to determine this.

Only if they respond that there is some problem, will I give you @fluffypony that information so you can follow up okay?

Regardless, it's helpful to know who our **Monero group contact** is that is listed on the submitted request. It is this person who must forward cloak requests to Freenode. If this information isn't public, would the group contact please write me so that I can make my request? Thanks.

**Comment by michaesc** [comment]
Too bad @fluffypony but we lose. The Freenode boss(in) told me that they have no record of Monero as a registered group. It seems that although our application was not rejected that it got lost or suffered an exotic degeneration.

What do you think we should do?

If you know the person who submitted it, please ask them to contact their Freenode handler? Thanks.

**Comment by fluffypony** [comment]
I've resubmitted it to projects@ and to Gareth directly

**Comment by fluffypony** [comment]
All sorted - the group contacts listed with Freenode are: fluffypony, othe, NoodleDoodle, ArticMine, luigi1111, rehrar, pigeons, moneromooo

cc @othexmr, @NoodleDoodleNoodleDoodleNoodleDoodleNoo, @ArticMine, @luigi1111, @rehrar, @danrmiller, @moneromooo-monero

**Comment by fluffypony** [comment]
Also -

"you and your GCs can request cloaks in the for @monero/<unique part> or @monero/<optional part>/<unique part>, such as @monero/riccardo or @monero/developer/fluffypony. If you or your alt GCs would like to request a cloak for a project member, contact us in #freenode, or check `/stats p` to find on call staff, or even email us again at projects@freenode.net ."

**Comment by rehrar** [comment]
@fluffypony when I get on freenode it still shows my ip address. Do I have to do anything special to get it to show otherwise since you registered me already? Maybe I'm missing something. Sorry, I'm still noob.
