### ISSUE TITLE
Buildbot: fixes required for the Windows backend

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#238]
Though this isn't appearing in buildbot, when I build patches remotely on the buildbot machine, I'm met with:

```
[  3%] Building CXX object src/core/CMakeFiles/kovri-core_unity.dir/cotire/kovri
In file included from C:/msys64/home/anonimal/kovri/build/src/core/cotire/kovri-core_CXX_unity.cxx:31:0:
C:\msys64\home\anonimal\kovri\src\core\util\filesystem.cc: In member function 'void kovri::core::StringStream::WriteByteAndString(const string&)':
C:\msys64\home\anonimal\kovri\src\core\util\filesystem.cc:131:0: note: -Wmisleading-indentation is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers
   std::uint8_t len = string.size();

C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles/kovri-core_unity.dir/cotire/kovri-core_CXX_unity.cxx.obj: section .debug_frame$_ZN8CryptoPP31IteratedHashWithStaticTransformIjNS_10EnumToTypeINS_9ByteOrderELi1EEELj64ELj20ENS_4SHA1ELj0ELb0EED2Ev: string table overflow at offset 10000031
C:\msys64\tmp\cc8q50BT.s: Assembler messages:
C:\msys64\tmp\cc8q50BT.s: Fatal error: can't close CMakeFiles/kovri-core_unity.dir/cotire/kovri-core_CXX_unity.cxx.obj: File too big
make[4]: *** [src/core/CMakeFiles/kovri-core_unity.dir/build.make:1051: src/core/CMakeFiles/kovri-core_unity.dir/cotire/kovri-core_CXX_unity.cxx.obj] Error 1
make[4]: Leaving directory '/home/anonimal/kovri/build'
make[3]: *** [CMakeFiles/Makefile2:324: src/core/CMakeFiles/kovri-core_unity.dir/all] Error 2
make[3]: Leaving directory '/home/anonimal/kovri/build'
make[2]: *** [CMakeFiles/Makefile2:366: src/core/CMakeFiles/all_unity.dir/rule] Error 2
make[2]: Leaving directory '/home/anonimal/kovri/build'
make[1]: *** [Makefile:229: all_unity] Error 2
make[1]: Leaving directory '/home/anonimal/kovri/build'
make: *** [Makefile:162: release] Error 2
```

and as such, can't do Windows development. cotire/pre-compiled headers are a memory hog. Is buildbot somehow acquiring more memory than another user would?

**Comment by coneiric** [comment]
I was getting these errors as well when trying to do multiprocessor Windows builds with cotire.

You've probably come across this section of the [manual](https://github.com/sakra/cotire/blob/master/MANUAL.md#configuring-the-generation-of-the-unity-source). Maybe decreasing the maximum number of unity includes would help?

**Comment by anonimal** [comment]
Thanks @coneiric! That solved the cotire issue. I had to set `COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES=-j1` in addition to bumping down to the usual `-j1`. Maybe cotire does this automatically within buildbot's environment (buildbot only exposing 1 core availability?).

I'd like to keep this issue open though because the windows VMs need more power.

**Comment by coneiric** [comment]
> Nevermind... the issue is repro'd once the client lib starts building.

Agh! So close...

> I'd like to keep this issue open though because the windows VMs need more power.

Strap a bigger engine on those VMs, let's hit lightspeed!

**Comment by anonimal** [comment]
The issue now affects buildbot. @danrmiller We appear to need more memory and disk space:

- https://build.getmonero.org/builders/kovri-all-win32/builds/1041/steps/compile/logs/stdio
- https://build.getmonero.org/builders/kovri-static-win32/builds/529/steps/compile/logs/stdio
- https://build.getmonero.org/builders/kovri-static-win64/builds/538/steps/compile/logs/stdio

**Comment by anonimal** [comment]
Thanks to iDunk, this appears to solve the win32 build https://github.com/monero-project/monero/issues/3521#issuecomment-377466568.

**Comment by anonimal** [comment]
iDunk has also supplied us with a side-step for win64. The issue appears entirely windows related. The patch is intrusive but it's the best we've got right now, so thanks to iDunk for patching.

**Comment by danrmiller** [comment]
@anonimal What do you need done here?

**Comment by anonimal** [comment]
@danrmiller a working win32 build https://build.getmonero.org/builders/kovri-all-win32/builds/1141 https://build.getmonero.org/builders/kovri-static-win32/builds/550

**Comment by danrmiller** [comment]
Here is the latest attempts. Any ideas?

https://build.getmonero.org/builders/kovri-static-win32/builds/564/steps/compile/logs/stdio
