### ISSUE TITLE
Monero GNU Social Instance

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#24]
Moving here from https://github.com/monero-project/kovri/issues/105.

**Comment by rehrar** [comment]
After a bit of discussion with some people in the IRC chats, most that spoke weren't thrilled about the idea of having yet another place. I figure we can have more of a discussion here. If some others who think it will be useful want to chime in, that'd be great.

**Comment by anonimal** [comment]
>having yet another place

As a champion for decentralization, Monero's hosting + usage of GNU social would be a welcome replacement (or addition) to twitter.
