### ISSUE TITLE
Time to test Pootle (localization platform) on a .getmonero server

### ISSUE THREAD

**Issue by erciccione** [monero-project/meta#247]
@danrmiller I tested Pootle locally but now we need to start the proper configuration on an online server, so we can test it live and tweak it for our needs, configurate it and start using it for localizations. Already spoke with @fluffypony about this and told me to contact you.

**Comment by erciccione** [comment]
ping @danrmiller

**Comment by danrmiller** [comment]
Hi @erciccione. Sorry I didn't see this. It might be easier to talk on irc? I'm pigeons on freenode.

**Comment by erciccione** [comment]
Pootle is uploaded and it's being tested
