### ISSUE TITLE
Unable to SSH into various backend machines

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#248]
`ssh_exchange_identification: Connection closed by remote host`

A longstanding issue, related to #178 except that I can't even do it over clearnet.

- [ ] ARMv8 (which is currently [offline](https://github.com/monero-project/meta/issues/177))
- [ ] macOS 10.12
- [ ] FreeBSD
- [ ] OpenBSD

**Comment by danrmiller** [comment]
The onion addresses for armv8 and osx 10.12 have changed. All should let you in now. Leave me a message on IRC with what time you will be available and I'll get you the info and make sure its working for you
