### ISSUE TITLE
Monero: Meeting Agenda: Sunday, Jan. 8th, 16:00 UTC

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#25]
### Location:
- [Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | Irc2P | [Slack](https://monero.slack.com)
  - `#monero-dev`

### Proposed meeting items:
1. Greetings
2. Brief review of what's been completed since the previous meeting
3. Resolve PR's for `monero-forum` and `monero-site` and `meta`
4. Code + issue discussion / Q & A
5. Any additional meeting items
6. Confirm next meeting date/time

Notes:
- Meeting log will be posted to https://getmonero.org/blog/tags/dev%20diaries

**Comment by anonimal** [comment]
Proposed items will need to be changed once I get more feedback.

**Comment by anonimal** [comment]
Adding `Resolve PR's for monero-forum and monero-site`

**Comment by anonimal** [comment]
@fluffypony @luigi1111 @moneromooo-monero I repeated asked throughout the week - all the way up to 8 hours before the scheduled meeting time - if we would have a meeting, but only 1 community member responded with a 'we should' (earlier this week) and only one dev (@hyc) responded saying that they couldn't make it. Everyone else, throughout the week, flat-out said nothing in response and, in some cases, literally continued conversations with others after I repeatedly ask my questions (as if ignoring my questions).

I know this isn't high priority, we're all busy, everyone knows meetings are extra work, and everyone seems to like ad-hoc meetings, but I don't think anyone likes to be ignored about project issues. Could we figure something out? Maybe *"Don't try to organize Monero meetings, @anonimal"* or *"Organize the Monero meetings @anonimal and corral everyone if @fluffypony is AFK"* so myself or others aren't left in the dark (and end up screwing their Sunday schedule because the meeting ends up not happening)?

**Comment by fluffypony** [comment]
@anonimal apologies - I was under the impression we would restart meetings after the middle of Jan, since mid-Dec to mid-Jan is a bit of a crazy time for everyone. I somehow missed the pings about the meeting - sorry again!!

**Comment by anonimal** [comment]
@fluffypony I totally understand, I know you're very busy with traveling and related business.
