### ISSUE TITLE
How was boost built on the freebsd machine?

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#250]
https://build.getmonero.org/builders/kovri-all-freebsd64/builds/991/steps/compile/logs/stdio

**Comment by anonimal** [comment]
#248

**Comment by danrmiller** [comment]
Boost 1.66 from https://www.boost.org/users/history/version_1_66_0.html

user-config.jam:
```
using clang : : c++ : <cxxflags>"-fvisibility=hidden -fPIC" <linkflags>"" <archiver>"ar" <striper>"strip"  <ranlib>"ranlib" <rc>"" : ;
```
```
./bootstrap.sh --with-libraries=chrono,log,program_options,date_time,thread,system,filesystem,regex,test
```

```
./b2 -d0 runtime-link=shared threadapi=pthread threading=multi link=static variant=release --layout=tagged --build-type=complete --user-config=user-config.jam -sNO_BZIP2=1 --prefix=/usr/local install cxxflags="-fPIC" linkflags="-fPIC"
```

**Comment by coneiric** [comment]
Tried to reproduce the issue locally, and everything builds fine.

System details:

* FreeBSD 11.1
* Boost 1.66 (system package)
* Clang 4.0.0
* build command: `make all-options`,`make release`, and `make release-static` complete successfully

**Comment by danrmiller** [comment]
@coneiric We can't use the system packages if we will also build a static monero because we will need them build with the -fPIC flag.

**Comment by coneiric** [comment]
@danrmiller I didn't realize that, thanks for cluing me in :) Will continue to help troubleshoot.
