### ISSUE TITLE
Meta Repo Kovri Release Party

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#252]
Well, not that kind of party.

In today's meeting #239, we've agreed to the following dates:

- July 18th, 2018: **Feature freeze**
- July 25th, 2018: **Code freeze** (realistically, we'll probably be patching die-hard bugs until release)
- August 1st, 2018: **Release date**
- August 11th, 2018: [Defcon Kovri Workshop](https://taiga.getmonero.org/project/michael-vegas-august-2018/wiki/agenda)

Why am I posting here? Well, 4 platforms will be unavailable for release because of, at this time of writing, the following:

- [ ] #250 
- [ ] #248 
- [ ] #238 
- [ ] #178 
- [ ] #177 
- [x] #112

Also, 

- [ ] #254 

What can I do to help resolve these issues?

**Comment by anonimal** [comment]
Absolutely disgraceful that this is not going to be resolved, nor will any respond, by our first release. Code freeze is in less than 48 hours.

**Comment by jonathancross** [comment]
Seems this can be closed?
@selsta
