### ISSUE TITLE
Monero Coffee Chat: 14 July 2018 17:00 UTC

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/meta#256]
![Monero Coffee Chat](https://i.imgur.com/7G4Powo.png)

**Introduction**

This monthly meeting will feature longtime active members of the Monero community, who will answer questions from others. It will be loosely organized, and it will run about one hour.

This meeting hopes to make the community more accessible and open. It will also serve as a medium to communicate the latest and upcoming developments.

**Location**

**[YouTube Livestream](https://www.youtube.com/watch?v=CxXtvMTDEuY)** with Jitsi, a free open-source video conferencing tool.

**Time**

The meeting is at 17:00 UTC instead of 16:00 UTC to accommodate the DefCon Workgroup meeting.

**Proposed Agenda**

Monero Coffee Chats intend to be casual and encourage free flows of thought. Nevertheless, the meeting will be guided by the following topics:

How people can contribute
Current initiatives and progress
Future developments
Research lab "office hours"
Guiding philosophies
Blockfolio team

**Comment by b-g-goodell** [comment]
I can be there for office hours :D

**Comment by dginovker** [comment]
I'll be there too!

**Comment by Platinumwrist** [comment]
I'm on that station 1700 UTC time thanks
