### ISSUE TITLE
Monero Reseed Server for Kovri/I2P

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#26]
Something I'd actually like to host (and may in the future) but my plate is currently full (as is everyone else's these days).

There are benefits for monero/kovri in running a reseed server (some of which I'll be happy to elaborate on) and I'd recommend reading [this](https://geti2p.net/en/get-involved/guides/reseed). Also, AFAICT, we don't *need* to use java I2P to host a reseed server because our netdb layout + RI's are that of java I2P's - so the process of netdb scraping *shouldn't* be an issue (I would need to review more before anything goes online).

Ticketing here in case anyone else is interested. I highly recommend anyone to get involved with this issue or with hosting a reseed server.  If hosted by a monero community member, ideally I would work with them to have access to the server for kovri development purposes and to help with maintenance if needed.

**Comment by SamsungGalaxyPlayer** [comment]
Is this issue still needed?
