### ISSUE TITLE
Buildbot: Ubuntu x86-64 broken for past 7 days straight

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#264]
Read-only file system. #252.

**Comment by danrmiller** [comment]
Thanks, @rehrar pointed this ticket out to me so I restarted that machine, seems to be working now:

https://build.getmonero.org/builders/kovri-all-ubuntu-amd64/builds/1216

https://build.getmonero.org/builders/kovri-static-ubuntu-amd64/builds/564

I'll setup some monitoring for this stuff but in the meantime until we can set that up please just send me a message on irc and I will be able to notice quicker.

**Comment by selsta** [comment]
Buildbot has been taken offline.
