### ISSUE TITLE
Monero/Kovri/I2P IRC server

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#27]
The Irc2P network (IRC on I2P) currently consists of 3 server operators: irc.dg.i2p, irc.postman.i2p, and irc.echelon.i2p. While they are trusted within the I2P community and have the long record with the java I2P project, the issue of IRC centralization and the *potential* for abuse (e.g., anti-Kovri sentiment leading to removal of `#kovri/#kovri-dev`) still exists *purely* by design.

I can provide assistance/details to anyone who is interested. Your contribution will make waves with Kovri and the I2P community.

**Comment by anonimal** [comment]
I'm working with @alvinjoelsantos on this, internally. We have everything working but need more time for testing.

**Comment by alvinjoelsantos** [comment]
Test IRC I2P server up and running with NickServ/ChanServ. Open issues are posted on: https://github.com/alvinjoelsantos/ircxmr

**Comment by danrmiller** [comment]
@alvinjoelsantos and I have an ircd server running and accessible via I2P. We will finish testing and configuring it for another day or 2 and then open for use and relay to freenode.

I have contacted the irc2p operators about joining the irc2p network and have now sent a more formal request which they will discuss. They advise the decision may not be quick.

+in progress

**Comment by SamsungGalaxyPlayer** [comment]
Looks like this was dropped. I'm going to close this unless someone is specifically requesting an IRC server or is hosting one. We have difficulty enough supporting the relays for Mattermost.
