### ISSUE TITLE
Kovri: FreeBSD box is offline

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#3]
Effects the ability to confirm new [static build fix](https://github.com/monero-project/kovri/pull/438) for BSD. Build log [here](https://build.getmonero.org/builders/kovri-all-freebsd64/builds/93).

**Comment by danrmiller** [comment]
https://build.getmonero.org/builders/kovri-all-freebsd64/builds/94

Restarted, rebuilt the job and reported results to https://github.com/monero-project/kovri/pull/438

**Comment by anonimal** [comment]
Awesome, thanks @danrmiller.
