### ISSUE TITLE
Buildbot: filter non-build related files from building in PR's/merges

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#30]
Is this possible? If this is implemented, then https://github.com/monero-project/kovri/pull/513 shows otherwise.  I think the filter works for .md/.asc/.conf files though. Can anyone confirm?

**Comment by danrmiller** [comment]
Yes its possible, I just need to find some time to implement and test

**Comment by anonimal** [comment]
Resolved in #11

**Comment by anonimal** [comment]
https://github.com/monero-project/kovri/pull/535 is building markdown-only changes.

**Comment by anonimal** [comment]
Can we also add Dockerfile? https://github.com/monero-project/kovri/pull/541

**Comment by anonimal** [comment]
https://github.com/monero-project/kovri/pull/547 only changes README.md but the build kicked in.

**Comment by anonimal** [comment]
There are more files that we should add to the filter, such as `.clang-format` and `.dockerignore`. Once the filter is fixed, I can just PR the additions which shouldn't trigger a build.

**Comment by anonimal** [comment]
😢

**Comment by anonimal** [comment]
https://github.com/monero-project/kovri/pull/819 shows that `.asc` files are not filtered. AFAICT, the build also still kicks in for `.md` and `.conf` and basically anything that's PR'd.

@danrmiller is there anything I can do to help resolve this issue?
