### ISSUE TITLE
[Infrastructure] Add HumHub hosted instance

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/meta#311]
I believe that a self-hosted [HumHub](https://www.humhub.org/) instance would allow for better community collaboration.

# Problem

The Monero community is quite decentralized, and it's often hard to stay updated. Enthusiasts need to follow many different IRC channels, subreddits, Twitter accounts, and follow GitHub issues to follow many parts of the ecosystem. It's often challenging.

While it's relatively simple to keep track of code changes on GitHub, it's harder to track research conversations, FFS/CCS recipient work, community conversations, and more.

Monero offers Taiga as a project management tool, but I desire something less formal that's based around what _contributors_ work on, not specific _projects_.

# Solution

I believe that using a customized HumHub installation would help keep enthusiasts up-to-date. It essentially functions as Monero-specific Twitter.

HumHub is divided into different "spaces." These spaces can be public or private. Example spaces: Monero Research Lab, Monero Community Workgroup, Monerujo. I expect most active workgroups will have their own space.

Users can post updates in the appropriate spaces. These updates are shared among everyone who follows these spaces.

Users see an aggregated list of posts in their dashboard. They can use this page to stay updated with the daily or weekly updates from Monero contributors. They can click on the specific space they want to look more into to narrow the updates down to just those of the group.

Users can comment on updates, create polls, edit documents, and more.

I created this issue to gather initial community feedback. Would you use a dashboard to more easily see what's going on?

**Comment by danrmiller** [comment]
How about fingerd/finger!!!
