### ISSUE TITLE
Celebrating Monero's 5th Moneroversary - 18 April 2019

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/meta#324]
# Edit: [click here](https://github.com/monero-project/meta/issues/324#issuecomment-482330612) for the events.

parasew brought up an interesting point during [today's Community Workgroup meeting](#323): Monero's 5th "Moneroversary" is coming up really soon on Thursday April 18.

I'm opening up this Github issue to collect ideas on how to celebrate it. Here are some of my ideas, but please chime in with more!

1. **Countdown.** Monero's first block was mined approximately 10:50 UTC (6:50 ET). This makes it more difficult for people in the US, but possibly manageable for people in Asia and Europe. We may need to give up on exact timing or have several sessions.

2. **Livestream.** This could be in Coffee Chat-style, where people come together and chat about the various aspects suggested below. I think it could be cool to have a "mini-series" style, where one host is in charge of leading specific topics in a sort of micro-documentary. Thus, it will be longer than a normal Coffee Chat, but people are not expected to participate through the entire session.

* Monero's most meaningful past moments.

* Turning points in Monero's history.

* Monero's greatest past challenges.

* Monero contributor spotlight.

* Workgroup summaries.

* Monero's top future opportunities and challenges.

* Setting up a Monero wallet and node tutorial.

* General chat.

3. **Meetup participation.** paresew shared some interest in interacting with an online session. I personally recommend a quick check-in. It's difficult to organize two groups speaking with each other well. I would like to hear more about his idea to bring online and local communities together for this event.

4. **Press coverage.** This is a great opportunity for Monero press coverage. I would like to hear the Outreach workgroup's ideas for getting attention and making this a media-worthy event. We need marketing materials for the YouTube and Twitter thumbnails, and images for blogs and news to use in their backgrounds. It's a great change to set Monero's image and to build a set of sources.

5. **Community participation.** Community members should have many opportunities to participate. I can send notifications out on Blockfolio and Delta. We can tease it days in advance on Twitter and Reddit.

For an event of this magnitude, I would love to have Monero Core Team involvement. Outside participants, including Charlie Lee and others who appreciate Monero, should be included too. Let's make this a meaningful event!

Other random thoughts:

* Ceremonial barolo drinking or giveaway

* Fun games for the community to complete live

---

## Please comment with the following:

1. your time availability in UTC

2. what activities you are interested in among those listed and among other ideas you have (be as descriptive as possible)

3. if you are willing to "chair/moderate/lead" any of those sessions

4. any other information or comments

I am free after 21:00 UTC. @fluffypony indicated he can be free at 21:00 UTC on IRC. Sarang indicated he should be free that day.

**Comment by VieYang** [comment]
Anniversary coin or anniversary banknote

**Comment by el00ruobuob** [comment]
I could be available from 20:00 UTC to 22:00 UTC on IRC or anywhere else online.  
However, i'll suggest to other people in Paris, France to have a lunch together, from 10:00 UTC to 12:00 UTC (as genesis block birthday is during our lunch hours).

**Comment by b-g-goodell** [comment]
we each post an "I am Spartacus" video admitting to being one of @moneromooo-monero

**Comment by xeagu** [comment]
I am available April 18th at 21:00 UTC as well. Including Livestream. 

I am interested in presenting some sort of mini-series during the Livestream.

It might be fun to do a sort of "Monero Torch" where individuals send an increasing amount of Monero around to each other. It seems part of a Monero Anniversary celebration would include using the technology as a demonstration. Low fees make this quite reasonable.

Could also make a montage of well known Monero community members doing something like the Ice Bucket challenge or something creative like that. Could play this montage on a loop during the day while the Livestream is not going on.

**Comment by SamsungGalaxyPlayer** [comment]
midipoet and needmoney90 are making a puzzle for the event. parasew indicated that 21:00 UTC is good timing, but I am waiting on more details.

**Comment by parasew** [comment]
hello everyone! Our plan in Vienna is as follows:
we are organising the whole day and also invited people from the monero meetup in vienna, germany, etc. 

* We will start at 10:00 CET (8:00 UTC), everyone is welcome to join and to learn about the Monero project and talk about the highlights of the past 5 years.
* at 12:30 CET (10:30 UTC) we will be starting the countdown! Everyone will be online and we will try to link existing other initiatives (@el00ruobuob?)
* cake!
* in the afternoon there will be monero workshops
* at 21:30 (19:30 UTC) there will be the Monero Austria Meetup
* at 23:00 (21:00 UTC) we plan to link in the livestream.

what do you think?

**Comment by SamsungGalaxyPlayer** [comment]
Thanks @parasew! Would you like to livestream any events before I'm available at 21:00 UTC? I can get you the information you need to stream other events. Let me know what makes sense. It could be cool to livestream the countdown, for example, even if it's just us watching people mostly standing around and celebrating in a room. Do you have the recording equipment to make this happen? TL;DR: please say what events will be recorded or livestreamed.

Furthermore, do you expect to participate in the livestream at 21:00 UTC, or simply watch it?

**Comment by parasew** [comment]
We have cams, recording equipment and a good upstream here.

Regarding the streams: i think we could definitely stream 
a) the countdown (and have people join in) with cake-cutting afterwards 
b) the evening thing

The workshops and things in between is a bit more tricky and i guess it makes more sense to not broadcast them, as people are usually more reserved when workshops are recorded. 

In the evening thing i can totally participate in the stream; we have small presentations here before, and i could then join in from another room and we project the stream in the main room.

does that make sense?

**Comment by SamsungGalaxyPlayer** [comment]
Current timeline:

| Time | Description | Livestream |
| --- | --- | ---|
| 8:00 UTC | Vienna Riat informal discussion begins | No |
| 10:30 UTC | Vienna Riat countdown to Monero launch anniversary | Yes |
| ~13:30 UTC | Vienna Riat workshops | No |
| 19:30 UTC | Vienna Riat Meetup | No |
| 21:00 UTC | Moneroversary showcase | Yes |

The showcase will continue for several hours, including the following events:

1. Discussion with top contributors, including fluffypony

2. Puzzle provided by needmoney90 and midipoet

3. More to come!

**Comment by SamsungGalaxyPlayer** [comment]
Moneroversary marketing materials, courtesy of Diego (rehrar) and his wife!

![Monero Anniversary Twitter 1448x724 2-1](https://user-images.githubusercontent.com/12520755/56245767-d0a5c900-6065-11e9-8fcc-5a190bdef7cc.jpeg)
![Monero Anniversary YouTube ~16-9](https://user-images.githubusercontent.com/12520755/56245769-d0a5c900-6065-11e9-81c5-6ba7b6aadd7f.jpeg)

Alternative image, courtesy of Thunderosa from the Monero Outreach workgroup!

![image](https://user-images.githubusercontent.com/12520755/56245821-f337e200-6065-11e9-80e3-07e91303caf6.png)

**Comment by ProkhorZ** [comment]
I can't throw a party today, but for the next [Monero Meetup in Utrecht](https://www.meetup.com/monero-meetup-utrecht-nl/), I want to summarize the history of Monero in 5 key moments. What do you think were the most decisive moments? [Tell me what you think](https://www.reddit.com/r/Monero/comments/bem1r3/what_were_the_5_key_moments_in_moneros_first_5/) on Reddit.

**Comment by SamsungGalaxyPlayer** [comment]
Media coverage, social links, and more:

# Media Coverage

https://blockonomi.com/happy-birthday-monero-xmr/

https://www.coindesk.com/privacy-crypto-monero-celebrates-its-5th-birthday

https://www.livebitcoinnews.com/monero-celebrates-its-fifth-birthday/

https://bitcoinexchangeguide.com/put-your-hands-up-and-celebrate-privacy-coin-moneros-fifth-birthday-happy-youthday-xmr/

https://www.thecryptoupdates.com/crypto-privacy-pioneer-monero-reaches-the-5th-year-milestone/

https://breakermag.com/revisiting-moneros-bizarre-origins-on-its-fifth-birthday/

https://blokt.com/guides/a-beginners-guide-to-monero

# Twitter Social Links

https://twitter.com/JEhrenhofer/status/1118547249653583872

https://twitter.com/MoneroTalk/status/1118661714885607424

https://twitter.com/el00ruobuob/status/1118741343025676288

https://twitter.com/____nevv/status/1118805699331592194

https://twitter.com/____nevv/status/1118805848313212928

https://twitter.com/____nevv/status/1118806425994657792

https://twitter.com/____nevv/status/1118807655840145410

https://twitter.com/____nevv/status/1118808321300025344

https://twitter.com/____nevv/status/1118811860403392513

https://twitter.com/monero/status/1118823215655157762

https://twitter.com/parasew/status/1118824749688328192

https://twitter.com/edbwt/status/1118829051282587648

https://twitter.com/____nevv/status/1118838595874324480

https://twitter.com/____nevv/status/1118845632179994624

https://twitter.com/xmroutreach/status/1118864453762633728

https://twitter.com/EdgeWallet/status/1118892850836643840

https://twitter.com/fluffypony/status/1118868610578026496

https://twitter.com/Trezor/status/1118916851919142912

https://twitter.com/____nevv/status/1118922867679297541

https://twitter.com/____nevv/status/1118923427900022787

https://twitter.com/MoneroTalk/status/1118923547051724802

https://twitter.com/____nevv/status/1118924147277615104

https://twitter.com/____nevv/status/1118924287715553281

https://twitter.com/____nevv/status/1118924371383472134

https://twitter.com/____nevv/status/1118924827329482752

https://twitter.com/____nevv/status/1118925168137654277

https://twitter.com/____nevv/status/1118925543943102469

https://twitter.com/____nevv/status/1118925999016693760

https://twitter.com/paruch1/status/1118927349347770368

https://twitter.com/____nevv/status/1118930644749496322

https://twitter.com/GuardaWallet/status/1118951372622389250

https://twitter.com/monero/status/1118950479462117376

https://twitter.com/EdgeWallet/status/1118963178933817344

https://twitter.com/monero/status/1118964558482280449

https://twitter.com/fluffypony/status/1118985037494521857

https://twitter.com/____nevv/status/1118997600328404992

https://twitter.com/JEhrenhofer/status/1119041709034409984

https://twitter.com/coinpaprika/status/1119170823443615744

https://twitter.com/MinerGate/status/1119276490418421761

https://twitter.com/hyc_symas/status/1119403863885471750

# Reddit Social Links

https://www.reddit.com/r/Monero/comments/bdts81/happy_5th/

https://www.reddit.com/r/Monero/comments/be8sip/moneros_anniversary_is_tomorrow_april_18_join_the/

https://www.reddit.com/r/Monero/comments/beb5fc/moneroversary_special_the_butterfly_wood_and_24k/

https://www.reddit.com/r/Monero/comments/bef0lg/monero_talk_w_tmrw_1pmest_to_celebrate_moneros/

https://www.reddit.com/r/Monero/comments/behh1e/revuo_weekly_issue_4_with_moneroversary_schedule/

https://www.reddit.com/r/Monero/comments/beiwtk/happy_birthday_monero_introducing_minko/

https://www.reddit.com/r/Monero/comments/bejjfq/monero_5yrs_birthday_party_and_openhouse/

https://www.reddit.com/r/Monero/comments/bejkan/riatat_vienna_celebrating_today_join_us_for_our/

https://www.reddit.com/r/Monero/comments/bejo6y/moneroversary_join_us_in_case_you_re_in_vienna/

https://www.reddit.com/r/Monero/comments/bek3hw/happy_fifth_moneroversary_animated_gif/

https://www.reddit.com/r/Monero/comments/belvik/to_celebrate_moneros_5th_anniversary_wookey_is/

https://www.reddit.com/r/Monero/comments/bem1r3/what_were_the_5_key_moments_in_moneros_first_5/

https://www.reddit.com/r/Monero/comments/ben39u/happy_birthday_to_monero_from_the_mymonero_team/

https://www.reddit.com/r/Monero/comments/beo356/happy_birthday_mastering_monero_free_version_has/

https://www.reddit.com/r/Monero/comments/best6e/moneroversary_puzzle/

https://www.reddit.com/r/Monero/comments/bf9qfq/moneroversary_puzzle_part_ii/
