### ISSUE TITLE
GUI meeting: 23 April 2019 @ 17:00 UTC

### ISSUE THREAD

**Issue by xmrdsc** [monero-project/meta#332]
Join in for the first weekly Monero GUI workgroup meeting.

When: Tuesday, 23 April 2019 @ 17:00 UTC
Where: #monero-gui (freenode/matrix)

### Agenda

1. Greetings
2. Agenda
    1. Discuss pending PRs
    2. Discuss Github issues
    3. Developments past week
    4. Developments coming week
3. Discuss anything you'd like
    1. Default white-theme?

**Comment by el00ruobuob** [comment]
Logs available [here](https://repo.getmonero.org/monero-project/monero-site/blob/bc2d7e6691bb47e6e3fc09f25ffa7fba67360035/_posts/2019-04-23-logs-for-the-GUI-meeting-held-on-2019-04-23.md)

**Comment by SamsungGalaxyPlayer** [comment]
@xmrdsc since this is the first meeting, do you want to share the logs to r/monero?

**Comment by xmrdsc** [comment]
@SamsungGalaxyPlayer I don't mind, it could help with exposure so that others can see what keeps us busy.
