### ISSUE TITLE
DEF CON 27 Workgroup Meeting: 18 May 2019 17:00 UTC 

### ISSUE THREAD

**Issue by sanecito** [monero-project/meta#342]
**Location**

[Freenode](https://kiwiirc.com/nextclient/#irc://irc.freenode.net/#monero-community) | [Mattermost](https://mattermost.getmonero.org/monero/channels/monero-community) | [Slack](https://monero.slack.com/) | Irc2P | [Matrix/Riot](https://about.riot.im/)

Please test the relays shortly before using. If there are any issues, please use Freenode IRC directly.

Please [PM SGP on Reddit](https://www.reddit.com/message/compose/?to=SamsungGalaxyPlayer&subject=Monero%20Slack%20invite%20(from%20GitHub)&message=Hello%20please%20send%20a%20Monero%20Slack%20invite%20to%20the%20following%20email:) with your email for a Slack invite if desired.

    #monero-community

For discussion about DefCon outside the meeting you can also use the `#monero-defcon` channel so conversation doesn't get lost like it would otherwise in `#monero-community` due to other general/workgroup chat.

Taiga instance can be found here: https://taiga.getmonero.org/project/michael-defcon-vegas/

**Time**

2019/05/18

17:00 UTC
13:00 ET
12:00 CT
10:00 PT

Use [this timezone calculator ](https://www.timeanddate.com/worldclock/converter.html?iso=20190518T170000&p1=tz_et&p2=28&p3=111&p4=49&p5=179&p6=70&p7=224&p8=48&p9=136)to convert UTC to your time zone.

**Proposed Meeting Items**

Please comment on GitHub in advance of the meeting if you would like to propose an agenda item.

1. Introduction/Greetings
2. CFP Status Update (SGP)
3. Floor planning (deadline 1 July) ¹ (SGP's [existing design on Taiga](https://taiga.getmonero.org/media/attachments/d/0/0/5/a8ba2bfe0cb7237f05ed89d9314b45f733a43b5f627bedfb351cc997c1e7/monero-defcon-village-layout-2019-v3.png))
4. Lodging Aug 5th-7th pre-DC: communal-ish like IoT w/ AirBnB, just do off strip hotel, etc?
5. Logistics receiving area (ajs)
6. Audio/Video List: review, approve, CCS funding - separate or combined with other proposals (ajs)
7. Hardware challenge and puzzle (msvb, A village badge may be widely distributed, and we are welcome to organize the distribution method as well as create badge challenges.) 
8. Opens
9. Confirm next meeting date/time

¹ Our Ballys room assignment information is:

Room | Sq.ft. | Width | Length | Ceiling | Classroom | Theater | Reception | Banquet | Exhibits | U-Shape | H-Square
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Skyview 4 | 1,858 | 32' | 59' | 12' | 100 | 285 | 185 | 120

**Comment by michaesc** [comment]
Hello @sanecito ,

Please add to the agenda:

- [ ] Floor planning (deadline 1 July) ¹
-   @SamsungGalaxyPlayer 's design
- [ ] Hardware challenge and puzzle ²

¹ Our Ballys room assignment information is:

| Room | Sq.ft. | Width | Length | Ceiling | Classroom | Theater | Reception | Banquet | Exhibits | U-Shape | H-Square |
| -------- | -------- | -------- | -------- | -------- | -------- | -------- | -------- | -------- | -------- | -------- | -------- |
| Skyview 4 | 1,858 | 32' | 59' | 12' | 100 | 285 | 185 | 120 | — | 47 | 70 |

² A village badge may be widely distributed, and we are welcome to organise the distribution method as well as [create badge challenges](https://taiga.getmonero.org/project/michael-defcon-vegas/us/27/).

**Comment by michaesc** [comment]
Hi @sanecito ,

Please add as well:

- [ ] Logistics receiving area

...for ajs.

Thanks,
Michael

**Comment by SamsungGalaxyPlayer** [comment]
I only have one other item that comes to mind: a quick CFP status update.

**Comment by ajs-xmr** [comment]
Hi @sanecito 

Could you also add this to the agenda:

- [ ] Audio/Video List: review, approve, CCS funding - separate or combined with other proposals

**Comment by sanecito** [comment]
@michaesc @SamsungGalaxyPlayer @ajs-xmr Updated, thanks! Prioritized the items that are more time sensitive (CFP, floor, lodging reservations [are almost gone at Alexis Park])
