### ISSUE TITLE
[Infrastructure] Add Jitsi hosted instance

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/meta#350]
I believe that the Monero community would benefit significantly from a self-hosted Jitsi solution. Jitsi is an open-source videoconference tool. We use it for the Coffee Chats, Breaking Monero series, and more.

Jitsi graciously provides a free service at https://meet.jit.si, but it lacks a few key features:

- [ ] It only supports up to 720p. Ideally, it should support at least 1080p.
- [ ] It includes the Jitsi logo in the upper left. Ideally, it would have a small Monero logo or no logo.
- [ ] The livestream feature is unreliable.

I believe that we have used Jitsi enough in the past to warrant a self-hosted instance of Jitsi if we can manage.

**Comment by Gingeropolous** [comment]
i think you could pull this off @SamsungGalaxyPlayer . Find a good server host, then use the jitsi ubuntu package. Relatively easy.

**Comment by SamsungGalaxyPlayer** [comment]
@Gingeropolous have you gotten the livestream feature working?

**Comment by Gingeropolous** [comment]
no i haven't tried. have u setup an instance of this?

**Comment by Sunray-Nucleon** [comment]
Is this here still needed? According to recent videos its already set up, right? btw- You did see my hint on r/monero a while ago about a bug in the jitsi login, you're patched probably! sorry, stubling in here clicking through Git, tell me if i should not just talk right out straightly :S

**Comment by Sunray-Nucleon** [comment]
@SamsungGalaxyPlayer - Is this here still needed? According to recent videos its already set up, right? btw- You did see my hint on r/monero a while ago about a bug in the jitsi login, you're patched probably! sorry, stumbling in here testing a bit through Git, tell me if i should not just talk right out straightly :S

**Comment by SamsungGalaxyPlayer** [comment]
Closing this for now since we have a self-hosted version.
