### ISSUE TITLE
IRC not relayed to I2P

### ISSUE THREAD

**Issue by selene-kovri** [monero-project/meta#376]
Hi,

It looks like #monero and #monero-dev on i2p are not relayed to Freenode. They used to be, but it's been more than a week with nothing whatsoever, and I see no relay bots. Are the relayed channels elsewhere or is the relay broken ?

**Comment by selene-kovri** [comment]
I've just released software for monero, and would like to pop into IRC to link them. I can't connect to Freenode with Tor as this requires an account already - chicken and egg.

**Comment by selsta** [comment]
It has been years and no one took initiative to setup a irc2p bridge so I will close this. Getting a Libera <-> Matrix bridge setup is higher priority currently.
