### ISSUE TITLE
Let's participate to the 6th Hacktoberfest

### ISSUE THREAD

**Issue by erciccione** [monero-project/meta#397]
We already did last year (monero-project/monero#4488) and it was nice. We got some developers participating (especially in the Ecosystem project). We participated only with the main `monero` repo las year, i think we could expand it to `monero-gui` as well (ping @dEBRUYNE-1 @selsta @xmrdsc for an opinion).

Only thing we need to do is add the label "Hacktoberfest" to issues that can be picked up by external devs, which will probalby have not much familiarity with the code.

The core repo has already some [issues labelled from last year](https://github.com/monero-project/monero/labels/hacktoberfest), maybe @moneromooo-monero could add some more?

More info: https://hacktoberfest.digitalocean.com/

**Comment by selsta** [comment]
https://github.com/monero-project/monero-gui/issues?q=is%3Aopen+is%3Aissue+label%3AHacktoberfest

Do we have to add anything else?

**Comment by erciccione** [comment]
Nope, the label is enough.
