### ISSUE TITLE
Release name for November 0.15 hard fork

### ISSUE THREAD

**Issue by rehrar** [monero-project/meta#403]
Hey everyone, every hard fork we need to come up with a name for our release. The naming convention, as described [here](https://github.com/monero-project/meta/blob/master/NAMING.md) is a chemical element (in sequence) followed by a celestial object.

Last time was the Boron Butterfly release, and so now we have reached Carbon!

What are your ideas? Carbon what?

Carbon [Cigar](https://www.nasa.gov/feature/goddard/2017/messier-82-the-cigar-galaxy/)?

Carbon Cassiopeia? 

Let's hear it!

EDIT: Due to confusion below, I will clarify something that is in the Naming Convention doc. The celestial object should be an alliteration of the element. So since we are on Carbon, the celestial object should also start with a C.

**Comment by livinginformation** [comment]
Carbon [Crab](https://www.youtube.com/watch?v=LDU_Txk06tM) (nebula)!

**Comment by RED29** [comment]
Carbon Troodon

**Comment by RED29** [comment]
Carbon [Sculptor](https://en.wikipedia.org/wiki/Sculptor_Galaxy)

**Comment by RED29** [comment]
Carbon [Cartwheel](https://en.wikipedia.org/wiki/Cartwheel_Galaxy)

**Comment by paulshapiro** [comment]
RIP my inbox. The objectively correct name is Carbon Crab.

**Comment by 1blockologist** [comment]
Carbon Atlas

**Comment by hyc** [comment]
> Carbon Atlas

Doesn't follow the naming convention.

Carbon Chamaeleon
Carbon Camelopardalis

**Comment by DTIV** [comment]
Carbon pancake

**Comment by dginovker** [comment]
Carbon Cigar Galaxy!

**Comment by 1blockologist** [comment]
> > Carbon Atlas
> 
> Doesn't follow the naming convention.

It does, you just didn't know what celestial body it was, Atlas is one of the moons of Saturn

**Comment by dginovker** [comment]
> > > Carbon Atlas
> > 
> > 
> > Doesn't follow the naming convention.
> 
> It does, you just didn't know what celestial body it was, Atlas is one of the moons of Saturn

Could have been more clear; Celestial body must also start with a C.

**Comment by 1blockologist** [comment]
> > > > Carbon Atlas
> > > 
> > > 
> > > Doesn't follow the naming convention.
> > 
> > 
> > It does, you just didn't know what celestial body it was, Atlas is one of the moons of Saturn
> 
> Could have been more clear; Celestial body must also start with a C.

ah I was wondering about the alliteration! thanks for clarifying

**Comment by dginovker** [comment]
Carbon Coma Wall

![image](https://user-images.githubusercontent.com/32943174/67448920-82f6b400-f5e6-11e9-8018-d9b73224087f.png)

https://upload.wikimedia.org/wikipedia/commons/d/db/Observable_Universe_Logarithmic_Map_%28horizontal_layout_english_annotations%29.png

**Comment by 1blockologist** [comment]
> Carbon pancake

one person is saying that its gotta start with the same letter as carbon, the unspoken rule of alliteration

**Comment by idunno101** [comment]
Supporting a comment from Reddit

_Carbon Comet_

Credit [u/toSaturnAndBeyond](https://www.reddit.com/r/Monero/comments/dm7yfu/release_name_for_november_015_hard_fork/f4ynubt?utm_source=share&utm_medium=web2x)

**Comment by resyncX** [comment]
Carbon Crescent
https://en.m.wikipedia.org/wiki/Crescent_Nebula

**Comment by SomaticFanatic** [comment]
Is there an element or celestial object that has something to do with the new RandomX PoW? Like celestial that has randomness?

**Comment by Hohhle** [comment]
Carbon Chalawan
https://en.m.wikipedia.org/wiki/47_Ursae_Majoris

Similar to the Thai folklore crocodile king, Chalawan, Monero's "...aggressive nature and...need for superiority, what... [it] had was not enough."
https://en.m.wikipedia.org/wiki/Krai_Thong

**Comment by idunno101** [comment]
> Is there an element or celestial object that has something to do with the new RandomX PoW? Like something celestial that has randomness?

Carbon Centaur

Might be related to randomness? They have a gradually changing orbit.
https://en.wikipedia.org/wiki/Centaur_(small_Solar_System_body)

**Comment by Gingeropolous** [comment]
I like Centaur or Centaurus or Centauri. In addition to potential randomness, I often joke that monero is going to alpha centauri and not the moon. Who cares if you goto the moon, your still in earths orbit. 

we have interstellar ambitions. 

even if nothing around centauri may support life.

**Comment by BigslimVdub** [comment]
Carbon Century

**Comment by hyc** [comment]
@1blockologist 
> ah I was wondering about the alliteration! thanks for clarifying

Pay attention. The naming convention was linked in the initial comment. Those rules have been the same since 2014. Read before you write. https://github.com/monero-project/meta/blob/master/NAMING.md

**Comment by gym7rjm** [comment]
Carbon Callisto

Callisto is the second largest moon of Jupiter, has a massive multi-ring structure from an impact crater, and is thought to be a good choice for a potential human base because of its low radiation levels.

**Comment by M4nk1n1** [comment]
I like Carbon Marvin after the manically depressed robot in Hitchhiker's guide to the Galaxy. (Celestial Reference)

**Comment by fluffypony** [comment]
> I like Carbon Marvin after the manically depressed robot in Hitchhiker's guide to the Galaxy. (Celestial Reference)

Nope. Read the naming conventions linked in the first post.

**Comment by wekowaka9** [comment]
First choice - Carbon Centaur

Second Choice - Carbon Chameleon (has the "kuh" as in KUH-MEE-LEE-UHN sound so this may be better)

Centaur has an 'S' sound so not sure it has uber awesomeness in the alliteration department.

**Comment by 1blockologist** [comment]
> @1blockologist
> 
> > ah I was wondering about the alliteration! thanks for clarifying
> 
> Pay attention. The naming convention was linked in the initial comment. Those rules have been the same since 2015. Read before you write. https://github.com/monero-project/meta/blob/master/NAMING.md

right, for "maximum awesome" as it has already been clarified hours before your response. I spread the word to others since they notice the alliteration too but obviously don't find it as a rule. OP should edit to avoid this distraction

**Comment by Lafudoci** [comment]
Carbon Chamaeleon - RandomX makes Monero hide from ASIC, just like a chameleon.

**Comment by SChernykh** [comment]
But why Carbon though? Copper or Cobalt sound more cool (not Chromium please).

> Cadmium
Calcium
Californium
Carbon
Cerium
Cesium
Chlorine
Chromium
Cobalt
Copernicium
Copper
Curium

**Comment by defterade** [comment]
@fluffypony 
Actually, the naming convention doesn't say that it should follow the order of the periodic table. So then why is it?

**Comment by fluffypony** [comment]
> @fluffypony
> Actually, the naming convention doesn't say that it should follow the order of the periodic table. So then why is it?

The original forum thread in 2015 does, and naming.md was updated to reflect already - refresh if you’re not seeing that.

**Comment by QuickBASIC** [comment]
> @fluffypony
> Actually, the naming convention doesn't say that it should follow the order of the periodic table. So then why is it?

It does.

> Monero's naming convention of a chemical element **(in sequence)**

Emphasis added by me.

`Carbon Comet` is getting a lot of votes, but I feel like it's too plain. I'd like to suggest `Carbon Cassini` (The Cassini division is the space between Saturn's rings.)

**Comment by gym7rjm** [comment]
Original naming convention was Element in order + Galaxy. It was paused with good reason for Warptangent 0.10. Lithium Luna 0.12.0 also abstracted the concept with Luna not being a specific celestial body. 

I'm of the opinion that the celestial body should be something specific and with some deeper meaning towards the project. 

Right now "comet" is getting a lot of traction on Reddit, but how does it relate to Monero? Other than it just being a widely recognized thing in space. It's too generic imo and Monero is too unique of a project to be basic. 

Any chance we can further refine the naming schema to be more specific?

**Comment by Gingeropolous** [comment]
Another one I like is Carbon Constellation. 

because constellations are like networks... of things... that work together kinda to form things that are bigger than them and have meaning. 

doesn't really do it for the randomx randomness thing though. 

i also like carbon chameleon. Though this would require the Monero Marketing Department to release a cover of the song "ca ca ca ca carbon ca meeel eee oon". I can't even think of the original words now. 

Oooh, how about Carbon Kablooey ? Here we're using a bit of artistic license to use Kablooey in place of The Big Bang, because i really think Randomx is gonna reshape this whole space. 

Carbon Cosmos

Carbon Constant - the cosmological constant, because randomx is gonna be IT FOREVER and no more forks and its gonna be awesome and if it breaks then the whole universe falls apart.

**Comment by binaryFate** [comment]
I find some proposals "scientifically" more interesting, but I recognize they are a bit too arcane. Main aspects should remain:

- Something that speaks to the layman. In other words, something that sounds cool, but is not too overly specific. Something that evokes a known space object (to a _large portion_ of the population?) is probably fine. Something that requires a wikipedia check just to understand what even this is about -- and not getting the space connection -- is probably not fine.

- Something that roll well on the tongue. (And I say this as a non-native English speaker, this is important!)

Because of this I favor "Carbon Comet" so far among existic proposals.

**Comment by patoshii** [comment]
carbon comet +1

**Comment by SamsungGalaxyPlayer** [comment]
Please vote in my ranked choice voting poll, using the valid names included in this issue: https://civs.cs.cornell.edu/cgi-bin/vote.pl?id=E_e228920d8a4d1cec&akey=ebaf2172a4c2dcc9

This is not a binding vote.

**Comment by Gingeropolous** [comment]
yeah im leaning toward carbon comet for the reasons listed by @binaryFate . Carbon Chameleon is a bit of a mouthful. 

But then again, who says these things out loud? We're all just typing here.

All we're all robots.

**Comment by paulshapiro** [comment]
True, "Crab" is a tad obscure. Carbon Comet sounds dope.

**Comment by SamsungGalaxyPlayer** [comment]
Carbon Chamaeleon was chosen.
