### ISSUE TITLE
Deprecate BuildBot?

### ISSUE THREAD

**Issue by fluffypony** [monero-project/meta#420]
We've used BuildBot for a long time, but the Mac and ARM servers + VM boxes are expensive. There are also environmental issues which cause builds to fail (despite the PR being fine) often enough that people have started ignoring BuildBot results.

With Gitian being stable for the CLI, and getting close to completion on the GUI, pigeons and I would like to start taking the BuildBots down and deprecating them, starting with the CLI ones. This meta issue exists to take input from everyone as to whether this is a good idea or not.

**Comment by moneromooo-monero** [comment]
I wanted buildbots years ago. In practice, I tuned them out because they just pinged you for (most of the time) irrelevant stuff. So great in theory, but not in practice unfortunately. So no objection here.

**Comment by erciccione** [comment]
I totally agree. Also, we have other tools we can use, like GitHub actions and Gitlab CI structure. Both can be contributed to by the community (Which is not the case for the buildbots).

**Comment by vtnerd** [comment]
One giant benefit of continually building is getting quicker feedback if a platform is failing. It could be a rush during release time if a replacement process isn't in place.

Boost (used to?) has a test matrix where volunteers from the community setup a unique environment to compile + run tests and report back to a web interface. The testing is only done against commits and not against each PR - which reduces load considerably. Our commits are "batched" too, so they only need to run once a week (or less) after a group of commits. I should be able to obtain the code (probably Python) for both the server and the builds that ran this matrix. It generated static html files IIRC.

If Gitian is doing cross-compiles, then these systems don't have to be lock-down secure for release building, they only need to sanity checking periodically (with a rush during the lead-up to release).

**Comment by fluffypony** [comment]
@vtnerd to be clear, I'm not saying we mustn't have CI, I'm saying that it can use cross-compilation via Jenkins or whatever rather than native builds via BuildBot.

**Comment by vtnerd** [comment]
The cross-compile will do most of what we need. It will be difficult (impossible?) to get those CI systems to run arm64 unit tests + core tests for instance. That's where the test matrix would fill the gap. Its pretty rare to find a bug specific to one platform at least.

**Comment by hyc** [comment]
Could run arm64 tests via qemu if necessary. Emulation is slow but might be good enough for periodic test purposes.

**Comment by xiphon** [comment]
Just `osx-10.11` buildslave is needed for Monero GUI releases, we don't have any other environment to build the GUI for MacOS at the moment.

**Comment by Snipa22** [comment]
Gitlab-CI's structure is quite nice for most things, I've used it extensively in professional and personal structures.  If it's just a function of cost for some of the more obscure servers, I'm more than happy to help shoulder the load for these going forwards, as long as they're somewhat within reason.

**Comment by selsta** [comment]
For the CLI repository: https://github.com/monero-project/monero/pull/6270

**Comment by selsta** [comment]
Buildbot has been taken offline. @danrmiller please keep the osx-10.12 VM alive for macOS GUI builds.
