### ISSUE TITLE
Konferenco[EU] Meeting: 8th January 2020 @ 19:00 UTC

### ISSUE THREAD

**Issue by umma08** [monero-project/meta#426]
Please join in for the first Konferenco[EU] 2020 Meeting

When: Wednesday, 8th January 2020 @ 19:00 UTC
Where: #monero-konferenco (freenode/matrix)

**edit.1:** agenda edited as per request below. 

**Agenda**

**0. Greetings**

**1.Intro**
- a short word about time and pressure (as we are probably a little behind schedule on this thing)[midipoet]

**2. Roles** https://taiga.getmonero.org/project/michael-konferenco/us/17

- any more takers for designated roles?
  - Director(!), finances (!), catering, master of ceremonies, infodesk
  - Communications related: webmaster (!), graphic designer (!)
  - What do we do if roles do not get filled?

**3. Decision Making**
- in the absence of an official director (dictator) we vote to find weak/strong consensus?
- debate and voting (informal weighting?!?) for contested items?

**4. Konferenco Venue (Berlin)?**
- scouting report (msvb)
- preferences
- deadline for decision

**5. Konferenco Date?**
- based on venue availability?
- any other suggestions? rationale? preferences?

**6. Konferenco Theme/Topic?** https://taiga.getmonero.org/project/michael-konferenco/epic/59
- do we want a theme or does it actually matter?

**7. Konferenco Finance Planning?**
- CCS?
- do we want to explore any other finance/sponsorhip options?
- determining a budget (task for finance manager?)
- do we need a full time Project Manager and can we budget for this?

**8. Team Updates**
- operations (ajs)
- programme (midipoet)
- floor and communications (rotten)

**9. Agree meeting schedule** 
- weekly meetings?

**10. Taiga Tutorial**
- Timeline
- Backlog
- Wiki

**11. Open Discussion Time**
- aob

**Comment by michaesc** [comment]
Hi @umma08 ,

Please add or merge the list of topics from:

https://taiga.getmonero.org/project/michael-konferenco/wiki/online-meetings/

...they are currently:

*   Taiga tutorial (msvb: 3 minutes)
    0. Full text search
    1. Timeline
    2. Backlog
    3. Wiki
*   Operations reports (ajs: 5 minutes)
    1. Audio video (Technik)
    2. Other productions
*   Floor management (rotten: 2 minutes)
*   Communications (rotten: 3 minutes)
*   Scouting reports (msvb: 5 minutes)
    1.  Main venue
    2.  Evening party
    3.  Accommodation
*   Program reports (midipoet: 5 minutes)
    1.  CFP methods
    2.  Parallel sessions
*   Financial questions (5 minutes)
*   Unfilled staff roles (msvb: 2 minutes)
    *  Director, catering, finances, master of ceremonies, infodesk
    *  Communications related: webmaster, graphic designer
*   Open discussion (5 minutes)

Thank you.

**Comment by umma08** [comment]
> Hi @umma08 ,
> 
> Please add or merge the list of topics from:
> 
> https://taiga.getmonero.org/project/michael-konferenco/wiki/online-meetings/


Yes, i will try and fold these in. However, i think we need to concentrate on some of the more important items (date, venue, decision making protocol) before we get into any of the specifics (catering, av, afterschool activities). 

Perhaps we can save some of these items for the subsequent meeting when more decisions have been made?
