### ISSUE TITLE
Call for Developers

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#43]
As mentioned in https://github.com/monero-project/kovri/issues/530 and https://github.com/monero-project/kovri/issues/159 we could write descriptions of requisites/internals for developing Monero/GUI/Kovri and put into publishable form. From there we could post through various mediums. We could also create a request for particular research via the MRL. The sky's the limit.

If something like this is already in place, I don't know where it is nor if it is formal. I've spoken with @fluffypony and various things are in the works so I'd consider this issue to be a general purpose proposal.

**Comment by jas99** [comment]
@anonimal Hello bro
I was moving around monero-dev irc channel to figure out how to get involved.
You wanna get in touch?

**Comment by anonimal** [comment]
Hi @jas99. I'm idling `#monero-dev` and `#kovri-dev` if you want to talk further. Other contact methods are also available [here](https://github.com/monero-project/kovri/blob/master/README.md#contact).

**Comment by jas99** [comment]
Hey @anonimal 
Was already roaming around thr :smiley: 
How much slack you guys use? and if possible would luv invite 

Thx

**Comment by anonimal** [comment]
Sent to dev@jas.bio

**Comment by rehrar** [comment]
Alright, so I've got a number of ideas as to how something like this can be done. I'll list them below:

- Outreach to university CS programs. Whether it's giving a small presentation or even seeing if a professor wouldn't mind giving some credit for contributing to the project in some way. This would entail some sort of oversight for the student, so it may be worthwhile to think of a way that it can benefit the student without putting strain on the lead devs of the project.
- Encourage involvement in other areas of the Open Source world which can involve such things as:
  - Having a few volunteers in the Open Source Initiative (OSI) in https://opensource.org (perhaps a donation in Monero here as well?)
  - Building deliberate bridges of relationship between us and other honest, open source, privacy-centered programs including seeing about integrations, accepting Monero (offering free help), or making community-raised donations in Monero to said projects.
- Volunteering to write articles or other high quality material for various open source platforms and ideas (i.e. [opensource.com](https://opensource.com)).
- Identifying communities of open source developers and reaching out to them

**Comment by SamsungGalaxyPlayer** [comment]
Is this issue still needed?
