### ISSUE TITLE
Monero's 6th "Moneroversary" Event Ideas and Planning

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/meta#438]
# [Click here for the final schedule](https://github.com/monero-project/meta/issues/438#issuecomment-612532923)

Monero's 6th "Moneroversary" (birthday/anniversary) is on April 18. It falls on a Saturday this year, so we have a ton of flexibility to host events all day. This issue shall serve as a discussion to brainstorm ideas for the event.

The 5th Moneroversary included the following events (#324):

![image](https://user-images.githubusercontent.com/12520755/74106758-d60d5c00-4b2e-11ea-964d-e7153ee2bf64.png)

Let's make the 6th Moneroversary even better! We should consider the following:

1. ~~Physical meetups and check-ins~~
2. Games
  a. Kahoot Trivia (I have a license)
  b. Secret Hitler (open-source software available)
  c. Jackbox.TV (@rehrar has a license)
  d. Meme competition
  e. Something with EtherDraw
  f. Drawful
3. Coffee Chat discussion
4. Monero spend activities (#435; @xenugrande)
5. Puzzles
6. Barolo toast

Please comment below with ideas. We can put a schedule together as the ideas start to take on some traction.

**Comment by binaryFate** [comment]
10 days to go.
Physical meetups are out of question, but all other suggestions sound good.

**Comment by SamsungGalaxyPlayer** [comment]
### DRAFT DRAFT DRAFT DRAFT

| Time | Description | Length |
| --- | --- | ---|
| 15:00 UTC | Monero History ft. TBD | 30 minutes |
| 15:30 UTC | Monero Research Lab Q&A ft. Sarang Noether, host TBD | 30 minutes |
| 16:00 UTC | Monero Compliance Q&A ft. Justin Ehrenhofer, host TBD | 30 minutes |
| 16:30 UTC | Monero Trivia, host Justin Ehrenhofer | 30 minutes |
| 17:00 UTC | Monero Coffee Chat, host TBD | 60 minutes |
| 18:00 UTC | Monero Meme Competition, host Justin Ehrenhofer | 60 minutes |
| 19:00 UTC | Monero VR Happy Hour, host Diego Salazar | ? minutes |
| 23:59 UTC | Games, TBD (Jackbox.tv, Drawful 2, Cards Against Humanity, Secret Hitler) | ? minutes |

**Comment by sanecito** [comment]
As far as host goes for some of the QA, perhaps Douglas Tuman given Monero Talk?

As for games, Jackbox would seem to be the big one. Quickly polling Twitch shows Jackbox at ~640 viewers, Drawful 2 ~150, and nothing really for the rest. Jackbox also allows for audience participation for at least some of the games.

**Comment by SamsungGalaxyPlayer** [comment]
@sanecito I have Jackbox 3 and 4.

**Comment by sanecito** [comment]
@SamsungGalaxyPlayer In that case since I believe those don't have games folks can join in on (believe it's only Jackbox 6?), perhaps Drawful 2 since it was free recently and you promoted it in -community and it has the second highest stream numbers from what I can tell (above Jackbox number was for Jackbox 6 specifically)

**Comment by SamsungGalaxyPlayer** [comment]
@sanecito only the host needs a copy of the game. Players do not need a copy to join.

**Comment by SamsungGalaxyPlayer** [comment]
https://www.reddit.com/r/Monero/comments/g4bbpy/moneroversary_feedback_requested/#bottom-comments
