### ISSUE TITLE
Monero Dev Meeting: March 29th, 2020, 17:00 UTC

### ISSUE THREAD

**Issue by rehrar** [monero-project/meta#449]
### Location
- [Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | [Slack](https://monero.slack.com/) | Irc2P | [Mattermost](https://mattermost.getmonero.org)
  - #monero-dev

### Time

Use the [timezone converter](https://www.timeanddate.com/worldclock/converter.html?iso=20200329T170000&p1=tz_gmt&p2=tz_et&p3=28&p4=111&p5=49&p6=179&p7=70&p8=224&p9=48) to see when the meeting is for you.

### Proposed Meeting Items
1. Greetings
2. Brief review of what's been completed since the previous meeting
3. Research items for discussion
4. Dev items for discussion
5. D++ and/or CLSAG
6. v0.15.1.0 discussion
7. Seeds
8. Any additional meeting items
9. Confirm next meeting date/time

**Comment by selsta** [comment]
Please add v0.15.1.0 release to the meeting items.

**Comment by binaryFate** [comment]
To discuss: seeds
