### ISSUE TITLE
Monero Village Meeting: 16 May 2020, 17:00 UTC

### ISSUE THREAD

**Issue by michaesc** [monero-project/meta#463]
https://taiga.getmonero.org/project/michael-monero-village-at-defcon-planning/

### Location

[Freenode](https://webchat.freenode.net/)|[OFTC](https://webchat.oftc.net/)|[Slack](https://monero.slack.com/)|Irc2P|[Mattermost](https://mattermost.getmonero.org/)
* #monero-defcon

### Time
Use the [timezone converter](https://www.timeanddate.com/worldclock/converter.html?iso=20200329T170000&p1=tz_gmt&p2=tz_et&p3=28&p4=111&p5=49&p6=179&p7=70&p8=224&p9=48) to see when the meeting is for you.

### Proposed Meeting Items
1. Greetings
2. Brief review of DC28 village status
3. Virtualisation research items
   * Mozilla hubs (rehrar?)
   * Cryptogaming (xmrscott)
   * Project management (sgp)
   * Stagenet node as outreach
   * What to do with Jitsi and discord
   * Childproofing content and service
4. Try to decide if MVDC happens
5. Any additional meeting items
6. Confirm next meeting date/time

**Comment by SamsungGalaxyPlayer** [comment]
I am taking the day off. However, I would like to stress that I personally do not like using Taiga. I'd rather use Microsoft Teams even.
