### ISSUE TITLE
Release name for v0.16

### ISSUE THREAD

**Issue by selsta** [monero-project/meta#464]
We need a name for the upcoming v0.16 release. The naming scheme can be found here: [NAMING.md](https://github.com/monero-project/meta/blob/master/NAMING.md)

Suggestions:

- Nitrogen Nebula
- Nitrogen Nemesis

Please put more suggestions in the comments :)

**Comment by SamsungGalaxyPlayer** [comment]
Other possible celestial objects/names:

* Naiad
* Nereid
* Nereus
* Nova
* Neutron
* Norma

**Comment by rbrunner7** [comment]
*Nitrogen Nemesis* refers to the asteroid 128 Nemesis, details see [Wikipedia](https://en.wikipedia.org/wiki/128_Nemesis).

More proposals:
* *Nitrogen Nereid*, from a [moon of Neptune](https://en.wikipedia.org/wiki/Nereid_(moon))
* *Nitrogen Nöther*, maybe admissible because there is a [moon crater](https://en.wikipedia.org/wiki/N%C3%B6ther_(crater)) with that name

**Comment by fluffypony** [comment]
What about *Nitrogen Neptune*?

**Comment by jwinterm** [comment]
I like Nitrogen Nova or Nitrogen Neutron(Star)

**Comment by vdo** [comment]
+1 for _Nitrogen Nereid_

**Comment by defterade** [comment]
+1 for Nitrogen Nebula

**Comment by caseyasparks** [comment]
I like "Neon" over "Nitrogen".

Throwing my hat in the ring for "Neon Nebula"

**Comment by selsta** [comment]
@caseyasparks v0.19 will be Neon :) This release is Nitrogen according to the naming convention.

**Comment by caseyasparks** [comment]
> @caseyasparks v0.19 will be Neon :) This release is Nitrogen according to the naming convention.

@selsta Oops! My bad on reading comprehension...

**Comment by ambys33** [comment]
Let´s go with Nitrogen Nembus!

**Comment by SamsungGalaxyPlayer** [comment]
Extra points from me if you can relate the name to Dandelion++ somehow.

**Comment by SomaticFanatic** [comment]
What sort of celestial object acts like a dandelion fluffing?

**Comment by sanecito** [comment]
Probably closest thing I can think of would be a red giant star due to the nature of it iteratively shedding like dandelion seed clusters.

**Comment by janrothen** [comment]
What about **Nitrogen Needle**

[NGC_4565 also known as the Needle Galaxy](https://en.wikipedia.org/wiki/NGC_4565)

**Comment by Lafudoci** [comment]
> Probably closest thing I can think of would be a red giant star due to the nature of it iteratively shedding like dandelion seed clusters.

[NGC_6751](https://en.wikipedia.org/wiki/NGC_6751) looks just like dandelion. But sadly the name doesn't starts with n.

**Comment by Gingeropolous** [comment]
"Nitrogen NGC6751"

then we'll be just like elon naming things unpronounceable things. its all the rage! my troll vote is on this one. 

actually might put my real vote on that one. Nice little easteregg for someone to google and then go "oh, dandelion, right"

**Comment by xmrhaelan** [comment]
+1 for Nitrogen Needle

**Comment by pluja** [comment]
> Extra points from me if you can relate the name to Dandelion++ somehow.

@SamsungGalaxyPlayer Isn't there any celestial object called Dandelion? I found some images with similar shapes to a Dandelion, so maybe there could be something similar:
http://cs.astronomy.com/cfs-file.ashx/__key/communityserver-blogs-components-weblogfiles/00-00-00-00-51-Deep_2D00_sky+objects/1738.arp148.jpg
https://www.spaceanswers.com/wp-content/uploads/2013/04/Vivid-colour-photo.jpg

Maybe Nitrogen Dandelion?

**Comment by pluja** [comment]
I really like "Nitrogen Quasar". Quasars look awesome:
![image](https://user-images.githubusercontent.com/64632615/81787079-d2f48400-9500-11ea-82fc-cdaeca938c8c.png)
![image](https://user-images.githubusercontent.com/64632615/81787178-f28bac80-9500-11ea-8426-022aefc378cf.png)

**Comment by Lafudoci** [comment]
> Maybe Nitrogen Dandelion?

Nope, the second word needs to start with "n". Please check the naming scheme in the first comment.

**Comment by Sunray-Nucleon** [comment]
Nitrogen Nucleon

isn't this dandelionish

> [...]the nucleons are partially delocalized and organize themselves according to the laws of quantum chromodynamics.

 ~~wikipedia

and its number 7 in the list and Nucleon has 7 protons and 7 electrons in the atomic structure

**Comment by rbrunner7** [comment]
There is a small crater on the moon [called Dandelion](https://en.wikipedia.org/wiki/Dandelion_Crater), named in 1971 by the Apollo 15 astronauts, but I guess it's so unimportant and badly documented that it does not serve ...

**Comment by SamsungGalaxyPlayer** [comment]
Poll using the popular options: https://civs.cs.cornell.edu/cgi-bin/vote.pl?id=E_730a152d90b774ee&akey=efaa76b359bcd1b3
