### ISSUE TITLE
Monero Village Meeting: 30 May 2020, 18:00 UTC

### ISSUE THREAD

**Issue by michaesc** [monero-project/meta#465]
https://taiga.getmonero.org/project/michael-monero-village-at-defcon-planning/

### Location

[Freenode](https://webchat.freenode.net/)|[OFTC](https://webchat.oftc.net/)|[Slack](https://monero.slack.com/)|Irc2P|[Mattermost](https://mattermost.getmonero.org/)
* #monero-defcon

### Time
Use the [timezone converter](https://www.timeanddate.com/worldclock/converter.html?iso=20200530T180000&p1=tz_gmt&p2=tz_et&p3=28&p4=111&p5=49&p6=179&p7=70&p8=224&p9=48) to see when the meeting is for you.

### Proposed Meeting Items
1. Greetings
2. Review of DC28 village status
3. Virtualisation research items
4. Fun activity content items
5. Any additional meeting items
6. Confirm next meeting date/time

**Comment by SamsungGalaxyPlayer** [comment]
This is during the Coffee Chat

**Comment by michaesc** [comment]
Thanks @SamsungGalaxyPlayer for **catching the time problem.** I changed the meeting time from 17:00 to 18:00, and hopefully there is no problem with **back to back** online activities like that?

**Comment by SamsungGalaxyPlayer** [comment]
Yeah, should be okay.
