### ISSUE TITLE
Kovri meeting: March 26th, 2017, 18:00 UTC

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#48]
### Location:
- [Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | Irc2P | [Slack](https://monero.slack.com)
  - `#monero-dev`
  - `#kovri-dev`

### Proposed meeting items:
1. Greetings
2. Brief review of what's been completed since the previous meeting
3. Monero HackerOne Bounty https://www.reddit.com/r/Monero/comments/5zmywx/monero_bounty_for_hackerone/
3. Code + ticket discussion / Q & A
4. Any additional meeting items
5. Confirm next meeting date/time

Notes:
- `#kovri-dev` and `#monero-dev` *should* be relayed to each other through the duration of the meeting
- Meeting log will be posted to https://getmonero.org/blog/tags/dev%20diaries

**Comment by fluffypony** [comment]
@anonimal can we push this one out? The Monero meeting is going to be a bit intense, and I don't want us to have time pressure if we can avoid it.

**Comment by anonimal** [comment]
@fluffypony absolutely, I will move the date to the 19th.

**Comment by guzzijones** [comment]
i will not be at the meeting due to prior arrangements.  I will be moving forward with unit tests of the address book.

**Comment by fluffypony** [comment]
@anonimal given guzzi's absence, and the out-of-sync-ness with the Monero meetings, should we push this one out to next week?

**Comment by anonimal** [comment]
I think we should do both meetings: today and next week.

**Comment by bigreddmachine** [comment]
Sorry that I missed the meeting. I had some prior commitments that given the date changed screwed me up. Will logs be posted?

**Comment by anonimal** [comment]
@bigreddmachine Yes. @dEBRUYNE-1 will post them to getmonero.org as usual. I don't know when though.

**Comment by anonimal** [comment]
@bigreddmachine https://github.com/monero-project/monero-site/pull/241

**Comment by bigreddmachine** [comment]
@anonimal thanks!
