### ISSUE TITLE
Create network upgrade (hard-fork) checklist

### ISSUE THREAD

**Issue by sethsimmons** [monero-project/meta#489]
This issue will serve as a place to create, update, and discuss a checklist that can be used for each network upgrade (hard-fork) that occurrs in the future for the Monero network.

The checklist can be seen below:

	• Security audit
	• Code audit 
	• Ledger integration
		○ Implemented in Monero codebase (if needed)
		○ Ledger app integration coded by Ledger
	• Trezor integration
		○ Implemented in Monero codebase (if needed)
		○ Trezor app integration coded by Trezor
	• Fork height set
		○ Monero-announce mailer notice 
		○ Twitter announcement 
		○ Reddit announcement 
		○ Getmonero.org announcement 
	• Notify wallets
		○ MyMonero
		○ Coinomi
		○ Exa Wallet
		○ Wookey Wallet
		○ X Wallet
		○ Guarda
		○ ZelCore
		○ Cake Wallet
		○ Monerujo
		○ Edge Wallet
		○ Exodus
		○ XMRWallet
	• Notify exchanges
		○ https://web.getmonero.org/community/merchants/#exchanges
	• Notify 3rd party payment processors
		○ https://web.getmonero.org/community/merchants/#payment-gateways
	• Notify mining pools
		○ https://miningpoolstats.stream/monero
	• Release tagged
		○ Update src/version.cpp.in with new version AND new name (if necessary)
		○ Update Gitian YML files in contrib/gitian/ to the new version number
		○ Update README.md with new fork table entry (or at least update the Recommended Monero version)
		○ Update contrib/gitian/README.md so that the instructions reflect the current version
		○ Update src/checkpoints/checkpoints.cpp with a recent hardcoded checkpoint
		○ Update src/blocks/checkpoints.dat with ./monero-blockchain-export --output-file checkpoints.dat --block-stop <recent block height> --blocksdat
		○ Update expected_block_hashes_hash in src/cryptonote_core/blockchain.cpp with checkpoints.dat sha256 hash
	• Testnet forked
	• Testnet testing/verification
		○ Ledger
		○ Trezor
		○ Release-specific testing
		○ RPC testing/update RPC documentation
	• CLI reproducible builds validated
	• CLI released
		○ https://web.getmonero.org/downloads/ updated
		○ Update hashes.txt on website
		○ Update downloads.yml on website
		○ Update auto-update DNS records
		○ Update redirects on downloads box
		○ Update seed nodes
	• GUI released
		○ https://web.getmonero.org/downloads/ updated
		○ Update hashes.txt on website
		○ Update hashes.txt.sig on website
		○ Update downloads.yml on website
		○ Update auto-update DNS records
		○ Update redirects on downloads box
	• Monero-announce mailer notice 
	• Twitter announcement 
	• Reddit announcement 
	• Getmonero.org announcement

Edit list:

- Added Exodus to exchange list
- Added "Notify 3rd party payment processors"
- Added specifics on download update process
- Added specifics on code changes needed for tagging
- Added missing wallets from https://old.reddit.com/r/Monero/comments/hp7nna/rmonero_weekly_discussion_july_11_2020_use_this/
- Added "Update hashes.txt.sig on website" to GUI section

**Comment by fluffypony** [comment]
Please add Exodus to the list of wallets

**Comment by sethsimmons** [comment]
Done, thanks for the callout!

**Comment by sethsimmons** [comment]
I added a bunch of specifics for the tagging/download page updates from the below Release Engineering list provided by @fluffypony:

```
Builds:

- DON'T FORGET TO UPDATE src/version.cpp.in with new version AND new name (if necessary)
- DON'T FORGET TO UPDATE Gitian YML files in contrib/gitian/ to the new version number
- DON'T FORGET TO UPDATE README.md with new fork table entry (or at least update the Recommended Monero version)
- DON'T FORGET TO UDDATE contrib/gitian/README.md so that the instructions reflect the current version
- DON'T FORGET TO UDDATE src/checkpoints/checkpoints.cpp with a recent hardcoded checkpoint
- DON'T FORGET TO UPDATE src/blocks/checkpoints.dat with ./monero-blockchain-export --output-file checkpoints.dat --block-stop <recent block height> --blocksdat
- DON'T FORGET TO UPDATE expected_block_hashes_hash in src/cryptonote_core/blockchain.cpp with checkpoints.dat sha256 hash
- DON'T FORGET TO POST ABOUT THE RELEASE ON THE MONERO-ANNOUNCE LIST


Final steps:

- Update hashes.txt on website
- Update downloads.yml on website
- Update auto-update DNS records
- Update redirects on downloads box
```

**Comment by glv2** [comment]
Maybe this checklist could be added to the monero-project/monero repository as a file named "RELEASE_PROCESS.md" or something similar, instead of keeping it in a github issue.

In order not to clutter up the root directory of the repository with documentation files, we could make a "doc" subdirectory, put "ANONYMITY_NETWORKS.md", "CONTRIBUTING.md", "LEVIN_PROTOCOL.md", "README.i18n.md" and "RELEASE_PROCESS.md" in there, and fix the links to those files in "README.md" if necessary.

**Comment by fluffypony** [comment]
@glv2 good point - a docs subdirectory is a great idea!

**Comment by hyc** [comment]
Might call it something like devdocs instead, since none of these are really relevant to end users.

**Comment by fluffypony** [comment]
@hyc I *think* that whatever is in the source code is relevant to developers and not end-users anyway, so I'm not averse to either docs or devdocs

**Comment by hyc** [comment]
Maybe most is. The "Using TOR" section of README.md is presumably for end users.

**Comment by erciccione** [comment]
Yeah, when @sarangnoether proposed the checklist, we assumed it should be saved somewhere in the repository (either this repo or 'monero') and used for every release. 'devdocs/RELEASE_PROCESS.md' sounds good.

As suggested during yesterday's meeting: After the checklist is created, we could make a github project based on the checklist: a single board with "todo" "in progress" and "done" tabs. Issues could be added to the board (as tasks) and people assigned to issues.

**Comment by sethsimmons** [comment]
Thanks for the feedback so far, everyone!

Any other outstanding items I’ve missed or you’d like to see added?

I’ll re-share this in IRC too just to make sure we get a good set of eyes on it, but we should probably finalize it soon to use for the CLSAG upgrade coming up.

**Comment by garlicgambit** [comment]
Couple suggestions:  
  
- Update README.md (compile) instructions to the new version number  
- Check/update README.md software dependencies and version numbers  
- Sign git tag

**Comment by fluffypony** [comment]
@garlicgambit those are all in there already

**Comment by Adreik** [comment]
What about performing tests on the RPC daemon and wallet documentation, and preparing updates to those webpages if there is any issue?

**Comment by garlicgambit** [comment]
@fluffypony if the current level of detail is appropriate for the people that will use the checklist, then you can ignore the suggestions.

**Comment by erciccione** [comment]
@sethsimmons I would add: Check if seednodes are up and ready for the hard fork.

**Comment by sethsimmons** [comment]
Added all suggestions.

**Comment by sethsimmons** [comment]
Final version: https://github.com/sethsimmons/Miscellaneous-Monero/blob/master/Monero%20Release%20Checklist.md
