### ISSUE TITLE
Community Workgroup Meeting: 29 August 2020 17:00 UTC

### ISSUE THREAD

**Issue by rehrar** [monero-project/meta#503]
## Location

    #monero-community

## Time

17:00 UTC

## Proposed Meeting Items

Please comment on GitHub in advance of the meeting if you would like to propose an agenda item.

1. Greetings
 2. MCW updates
3. CCS updates
4. Workgroup report
    a. Daemon/CLI/GUI workgroup
    b. Localization workgroup
    c. Website workgroup
    d. Outreach workgroup
    e. Monero Research Lab
5. Open ideas time
6. Confirm next meeting date/time

**Comment by sanecito** [comment]
Per msvb:
"Would you please add an agenda meeting for Grayhat?
Title: Grayhat.co invitation, Duration: 5 minutes, Subtitle: Shall we enter a village proposal?
It might not reach the level of importance needed to be included in our meeting, if you think that is true then don't make a agenda entry.
It is our last chance of getting permission to present Monero content at Grayhat (deadline on Friday in one week.)"

"Folks at the Defcon Redteam village (DC/RT) want to invite us (the general Monero community) to build a village for a online conference (usually physical in Texas) called 'Grayhat.' So I want to request a five minute duration during the meeting to find out if anybody wants to partipate in the October conference."

**Comment by michaesc** [comment]
> Per msvb:
> "Would you please add an agenda meeting for Grayhat?
>

Thank you @sanecito .
