### ISSUE TITLE
Release name for v0.17

### ISSUE THREAD

**Issue by selsta** [monero-project/meta#506]
We need a name for the upcoming v0.17 release. The naming scheme can be found here: [NAMING.md](https://github.com/monero-project/meta/blob/master/NAMING.md)

Suggestions:

- Oxygen Orion (jwinterm)
- Oxygen Oort (nioc)
- Oxygen Ogma (nioc)
- Oxygen Omikron (mooo)
- Oxygen Oumuamua (mooo)
- Oxygen Ocelot (hyc)

Please put more suggestions in the comments.

**Comment by sethsimmons** [comment]
Oxygen Orion or Oxygen Ocelot are my vote!

**Comment by sanecito** [comment]
My vote would be for Omikron so it could be followed by next release with Persei for a Futurama combo

**Comment by antanst** [comment]
Oxygen Omikron

**Comment by rbrunner7** [comment]
Oxigen [Oceana](https://en.wikipedia.org/wiki/224_Oceana)

**Comment by rbrunner7** [comment]
Oxigen [Oberon](https://en.wikipedia.org/wiki/Oberon_(moon))

**Comment by marcaufderheyde** [comment]
Oxygen Ocelot! 

Rolls off the tongue and pops as well

**Comment by serhack** [comment]
Oxygen Orion

**Comment by Adreik** [comment]
Oxygen Ophiuchus

**Comment by SChernykh** [comment]
Oxygen Orion because Orion is the most known out of all proposed names - `About 182 000 000 results` in Google search, way more than all other variants.

**Comment by rbrunner7** [comment]
> Oxygen Orion because Orion is the most known out of all proposed names - `About 182 000 000 results` in Google search, way more than all other variants.

Right, but isn't it a little, well, boring for the same reason? Tons of things must have the name *Orion*...

**Comment by BTCLovera** [comment]
Oxygen Omikron

**Comment by fluffypony** [comment]
Oxygen Orion as a nod to @orionwl (the Bitcoin lead maintainer, whose job is thankless) gets my vote.

**Comment by arod71** [comment]
Oxygen Ophelia

**Comment by tibo33** [comment]
Oxygen Ocelot seems nice
has a good ring to it and from wiki: "Typically active during twilight and at night, the ocelot tends to be solitary and territorial. It is efficient at climbing, leaping and swimming."
That's monero with CLSAG to me :-)

**Comment by juju515** [comment]
_**Oxygen Oort**_
Like the Oort cloud "A theoretical shell of comets that is believed to exist at the outermost regions of our solar system."
But is completely invisible from earth with modern technology.
Like we know it's out there... but we can't see it at all. :)
That has a Monero feel to it. Don't you think?

**Comment by Nozzy247** [comment]
"Shooting Saturn" as an homage to RingCT.

The inspiration is a top down view of Saturn, showing its rings consisting of asteroid "decoys." Yet the planet has been "shot" by a large enough astroid to make it cresent ("C" shaped) while the bullet path and horizontal blast make a blazing "T"

**Comment by vp1111** [comment]
Oxygen Orion sounds nice to the ear.

**Comment by M5M400** [comment]
Oxygen Ocelot

**Comment by lh1008** [comment]
Oxygen Omikron

**Comment by denisgoddard** [comment]
Oxygen Oumuamua

It came in from the inky unknown blackness, was briefly visible, and now returns to the interstellar Dark.

**Comment by ndorf** [comment]
There was an Ubuntu release named Oneiric Ocelot back in 2011... makes that suggestion feel a little less original.

**Comment by SamsungGalaxyPlayer** [comment]
Vote for your preferred name: https://civs.cs.cornell.edu/cgi-bin/vote.pl?id=E_864375bedf3dfb6d&akey=3e507ef6fcca6ae6
