### ISSUE TITLE
Monero meeting: March 12th, 2017, 17:00 UTC

### ISSUE THREAD

**Issue by fluffypony** [monero-project/meta#51]
### Location:

- [Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | Irc2P | [Slack](https://monero.slack.com)
  - `#monero-dev`

### Time

Use the [timezone converter](https://www.timeanddate.com/worldclock/converter.html?iso=20170312T170000&p1=tz_gmt&p2=tz_et&p3=28&p4=111&p5=49&p6=179&p7=70&p8=224&p9=48) or the image below.

<img width="994" alt="screen shot 2017-03-12 at 9 30 04 am" src="https://cloud.githubusercontent.com/assets/1944293/23830252/b2b0f574-0706-11e7-8e4e-01f5593675e8.png">

### Proposed meeting items:

1. Greetings
2. Brief review of what's been completed since the previous meeting
3. A discussion of [PR 1816](https://github.com/monero-project/monero/pull/1816), & perhaps a more general discussion of C++ templating etc.
4. A Series of Unfortunate Events: the v0.10.2.x release failures, massive regressions, and serious issues. How do we do better in future?
5. Code + ticket discussion / Q & A
6. Any additional meeting items
7. Confirm next meeting date/time

Notes:
- `#kovri-dev` and `#monero-dev` will be relayed to each other through the duration of the meeting, even though there won't be a Kovri meeting following the Monero one.
- Meeting log will be posted to https://getmonero.org/blog/tags/dev%20diaries

**Comment by bigreddmachine** [comment]
Did this meeting happen? I thought I was logged into IRC at the time and don't remember seeing any discussion.

**Comment by paulshapiro** [comment]
I believe it was post-ponied a week, until tmw.
