### ISSUE TITLE
I'm not a Web developper but something is worrying me?

### ISSUE THREAD

**Issue by stoweo112** [monero-project/meta#515]
I just heard CIA have made a Working contract for around 700-800'000 US, They ask some developpers/hackers to join their team to break XMR privacy...
I dont know very well how Monero code is written but is there a possibility they can be succesfull?
If it might be, what Monero Team can develop to stop CIA before they just put our privacy lifes into trash?

**Comment by sanecito** [comment]
This GitHub repository is primarily for discussion around releases or community coordinated events. Your question is best directed to social forums like https://www.reddit.com/r/monero
