### ISSUE TITLE
The problem with Monero transactions

### ISSUE THREAD

**Issue by Evgenii272** [monero-project/meta#523]
I am the owner of a Monero wallet. I use the desktop version of the Monero GUI to manage my funds. After updating "Oxygen Orion" (0.17), I have an expense transaction in my wallet for the entire balance of the wallet, which I did not make. Further it was failed. And the balance is still showing my funds.The details of this transaction do not include the wallet address, and the transaction does not have a transaction key, but there are network confirmations. How is this possible? Now I am trying to send these funds to another wallet, but there is an error occurs saying about an error and double spending. Why I cannot make a transaction for any amount with the balance positive?

**Comment by selsta** [comment]
Please update to v0.17.1.1 first.

Are you using simple mode or advanced mode? You can check on Settings -> Info.

If advanced mode: Local or remote node?

**Comment by Evgenii272** [comment]
> Please update to v0.17.1.1 first.
> 
> Are you using simple mode or advanced mode? You can check on Settings -> Info.
> 
> If advanced mode: Local or remote node?

The program has been updated to version v0.17.1.1
Advanced mode in use, remote node

**Comment by selsta** [comment]
Okay, if the remote node you are connected to is a trusted remote node (you can set this in Settings -> Node menu) you can click on "Rescan wallet balance" on Settings -> Wallet screen. Afterwards this issue should be resolved.


If your remote node is not a trusted remote node you have to go to Settings -> Info, click on "(Change)" next to wallet restore height and then okay twice.

**Comment by Evgenii272** [comment]
> Okay, if the remote node you are connected to is a trusted remote node (you can set this in Settings -> Node menu) you can click on "Rescan wallet balance" on Settings -> Wallet screen. Afterwards this issue should be resolved.
> 
> If your remote node is not a trusted remote node you have to go to Settings -> Info, click on "(Change)" next to wallet restore height and then okay twice.

Node is trusted
After re-scanning the wallet balance, the balance became 0.

There is an expense transaction. The details of this transaction do not include the wallet address and the transaction does not have a transaction key, but there is network confirmation. How is this possible?

**Comment by selsta** [comment]
Go to Settings -> Info, click on "(Change)" next to wallet restore height and then okay twice. Then wait for the wallet to refresh. If you still have issues afterwards please formulate the exact problem.

**Comment by Evgenii272** [comment]
> Go to Settings -> Info, click on "(Change)" next to wallet restore height and then okay twice. Then wait for the wallet to refresh. If you still have issues afterwards please formulate the exact problem.

How does this help?

Can you please answer these questions?
There is an expense transaction. The details of this transaction do not include the wallet address and the transaction does not have a transaction key, but there is network confirmation. How is this possible?

**Comment by SamsungGalaxyPlayer** [comment]
Please use another support channel like r/MoneroSupport. Meta is not the right place for these issues.
