### ISSUE TITLE
daemon failed to connect on two different computers

### ISSUE THREAD

**Issue by Frsutrated** [monero-project/meta#536]
Downloaded the GUI wallet, and  crashed my computer. Error code said wallet Daemon  failure to connect after 120 seconds. 
I tried the same on a different computer, DL'd it, same problem. Got the computer to finally sync, after 12 hours, and then again it crashed, and failed to connect after this. I would like to buy some monero, but this is useless!

**Comment by sanecito** [comment]
If you're having issues with the GUI, please file it in the GUI repository, not Meta: https://github.com/monero-project/monero-gui/issues

Meta is intended for things like conversations around meetings, infrastructure changes.

Alternatively, you can try r/MoneroSupport on Reddit which is likely to result in a quicker resolution: https://www.reddit.com/r/monerosupport/
