### ISSUE TITLE
Community Workgroup Meeting: 9 January 2021 17:00 UTC

### ISSUE THREAD

**Issue by rehrar** [monero-project/meta#539]
## Location

    #monero-community

## Time

17:00 UTC

## Proposed Meeting Items

Please comment on GitHub in advance of the meeting if you would like to propose an agenda item.

1. Greetings
2. CCS updates
3. Workgroup report
4. Meeting discussion on meetings
5. Open ideas time
6. Confirm next meeting date/time

**Comment by binaryFate** [comment]
Date is in the past

**Comment by SamsungGalaxyPlayer** [comment]
Please add #534

**Comment by rehrar** [comment]
@binaryFate changed
@SamsungGalaxyPlayer will be discussed

**Comment by SamsungGalaxyPlayer** [comment]
What's "meeting discussion on meetings"?
