### ISSUE TITLE
Remove benchmarks run from buildbot

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#54]
We'll very soon have benchmarks running within the utility binary. This means no more `kovri-benchmarks`. I personally don't have a need to run benchmarks on every build either (but that's just me) so if we remove them all-together from the build then I'm fine with that. Otherwise we'll have to run them from `kovri-util`.

**Comment by danrmiller** [comment]
>  Otherwise we'll have to run them from kovri-util.

What is the syntax to run the benchmarks with kovri-util?

**Comment by anonimal** [comment]
Currently `./kovri-util benchmark -t`

I'll ask @guzzijones to reconsider the switch or drop it completely because it currently isn't needed.

**Comment by guzzijones** [comment]
syntax is 
`kovri-util benchmark -a`

**Comment by guzzijones** [comment]
I can set -a as a default value and commit again.

**Comment by anonimal** [comment]
Done. Thanks @danrmiller.
