### ISSUE TITLE
Triptych Prioritization Meeting: 18 April 2021, 17:00 UTC

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/meta#566]
**Location**
#monero-dev on freenode (IRC)

**Time**
17:00 UTC

**Proposed Meeting Items**
Discussion of priorities of items relating to Triptych. Please comment on GitHub in advance of the meeting if you have suggestions.

**Comment by SamsungGalaxyPlayer** [comment]
It's my opinion we push with an earlier fork without Triptych, but including BP+, ringsize 15-17, and dynamic fee improvements. Triptych seems further off than proponents have suggested in my best assessment.

**Comment by dEBRUYNE-1** [comment]
@SamsungGalaxyPlayer - The idea for this meeting is to mainly discuss which aspects of Triptych should be prioritized by sarang.

**Comment by dEBRUYNE-1** [comment]
Postponed, new meeting scheduled in #568.
