### ISSUE TITLE
Village Workgroup Meeting: 26 June 2021, 18:00 UTC

### ISSUE THREAD

**Issue by michaesc** [monero-project/meta#579]
https://github.com/orgs/MoneroSpace/projects/2/

### Meeting location

[Freenode](https://webchat.freenode.net/)|[OFTC](https://webchat.oftc.net/)|[Slack](https://monero.slack.com/)|Irc2P|[Mattermost](https://mattermost.getmonero.org/)
* #monero-events

### Meeting time
Use the [timezone converter](https://www.timeanddate.com/worldclock/converter.html) to see when the meeting is for you.

### Moderation
* xmrscott

### Meeting Items
1. Greetings
1. Defcon status
1. Contest
   * [The Testnet Cointest \(official DC contest\)](https://taiga.getmonero.org/project/michael-monero-village-at-defcon/task/2/)
1. Party
1. Media
   * Switch for possible 802.3 connection **(in floorplan)**
1. Storage
1. Website
1. CFP
1. Floorplan
   * Deadline 21 June
1. Badges
   * Photo design
1. Additional items
   * Libra chat migration
1. Confirm next meeting date/time

**Comment by SamsungGalaxyPlayer** [comment]
The deadline for the floorplan is in the past?
