### ISSUE TITLE
Monero meeting: March 26th, 2017, 17:00 UTC

### ISSUE THREAD

**Issue by fluffypony** [monero-project/meta#58]
### Location:

- [Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | Irc2P | [Slack](https://monero.slack.com)
  - `#monero-dev`

### Time

Use the [timezone converter](https://www.timeanddate.com/worldclock/converter.html?iso=20170326T170000&p1=tz_gmt&p2=tz_et&p3=28&p4=111&p5=49&p6=179&p7=70&p8=224&p9=48) or the image below.

<img width="999" alt="screen shot 2017-03-19 at 7 15 00 pm" src="https://cloud.githubusercontent.com/assets/1944293/24083044/8ef95ff4-0cd8-11e7-992b-6f6123f9ed04.png">

### Proposed meeting items:

1. Greetings
2. Brief review of what's been completed since the previous meeting
3. Discussion of fireice-uk's proposal (as started in [#1828](https://github.com/monero-project/monero/issues/1828)
4. Remote nodes (ie. a discussion of [#605](https://github.com/monero-project/monero-core/pull/605)
5. Code + ticket discussion / Q & A
6. Any additional meeting items
7. Confirm next meeting date/time

Notes:
- `#kovri-dev` and `#monero-dev` will be relayed to each other through the duration of the meeting, even though there won't be a Kovri meeting following the Monero one.
- Meeting log will be posted to https://getmonero.org/blog/tags/dev%20diaries

**Comment by xmr-eric** [comment]
I'd like it if we could talk about [FireIce's proposal](https://github.com/monero-project/monero/issues/1828). RingCT has, I believe, resulted in a much slower wallet sync time, so a speedup for Intel/AMD processors seems a natural ideal.

**Comment by fluffypony** [comment]
@xmr-eric if @fireice-uk actually pitches up to a dev meeting for a change then sure, we can add it to the agenda.

**Comment by fireice-uk** [comment]
@fluffypony sure, will be there, feel free to add it.
