### ISSUE TITLE
Village Workgroup Meeting: 3 July 2021, 18:00 UTC

### ISSUE THREAD

**Issue by michaesc** [monero-project/meta#586]
https://github.com/MoneroSpace/defcon-cryptocurrency-village/projects/1/

### Meeting location

[Libera](https://web.libera.chat/)|[Matrix](https://matrix.to/#/#monero-events:monero.social?via=matrix.org&via=monero.social)
* #monero-events

### Meeting time
Use the [timezone converter](https://www.timeanddate.com/worldclock/converter.html) to see when the meeting is for you.

### Moderation
* xmrscott

### Meeting Items
1. Greetings
1. Defcon status
1. ~~Contest (was cancelled 25 June 2021)~~
   * Thanks to all the Monero Community members who refused to donate their work hours, our contest was cancelled and replaced by a Bitcoin group.
1. CCS
1. Party
   * Pool is ours, every evening.
   * Defcon official party is Saturday evening.
1. Media
   * (Improbable) switch for possible 802.3 connection **(in floorplan)**
   * Music licenses (ASCAP/RIAA) were paid by Defcon for us, except Youtube
   * Only official channels please (Discord monitored by goons for code of conduct)
1. Storage
1. Website
1. CFP
1. Floor mgmt
   * Should we move from **Champagne 1** to **Rivoli B**?
1. Badges
   * ~~Electronic cancelled (Thanks to Monero Community who refuse to contribute work)~~
   * Photo design for simple plastic staff cards
1. Additional items
1. Confirm next meeting date/time

**Comment by sanecito** [comment]
https://github.com/orgs/MoneroSpace/projects/2/

should be

https://github.com/MoneroSpace/defcon-cryptocurrency-village/projects/1

MatterMost has been deprecated, and I'd suggest having a Matrix link instead to: https://matrix.to/#/#monero-events:monero.social?via=matrix.org&via=monero.social

**Comment by IgitMo** [comment]
Is it okay to ask?
If this is a legit site of monero https://monero-mining.net/home/
