### ISSUE TITLE
Community Workgroup Meeting: 21 August 2021 17:00 UTC

### ISSUE THREAD

**Issue by Keiji-C** [monero-project/meta#599]
**Location**

[Libera.chat, #monero-community](https://libera.chat/) | [Matrix](https://matrix.to/#/#monero-community:monero.social?via=matrix.org&via=monero.social)

**Time**

17:00 UTC
19:00 CET
18:00 Irish Time
13:00 Eastern Time
10:00 Pacific Time
02:00 (2021/08/**22**) 日本標準時 

[Use this timezone calculator to convert UTC to your time zone](https://www.timeanddate.com/worldclock/converter.html?iso=20210821T170000&p1=1440&p2=28&p3=111&p4=tz_et&p5=49&p6=179&p7=70&p8=224&p9=48&p10=136&p11=248).

**Moderator**
TBD

**Proposed Meeting Items**

Please comment on GitHub in advance of the meeting if you would like to propose an agenda item.

- Introduction
- Greetings
- Community highlights
- CCS updates
    a.  ajs would like to adjust terms of xmr radio CCS after taking it over
    b. Monerujo's SideKick CCS Proposal
- Workgroup report
    a. Daemon/CLI workgroup     
    b. Localization workgroup
    c. GUI workgroup 
    d. Outreach workgroup
    e. Defcon workgroup
    f. Website workgroup
    g. Policy workgroup
    h. Malware workgroup
- Open ideas time
- Confirm next meeting date/time

**Comment by ghost** [comment]
Monerujo's SideKick CCS Proposal
