### ISSUE TITLE
Monero meeting: April 9th, 2017, 17:00 UTC

### ISSUE THREAD

**Issue by fluffypony** [monero-project/meta#60]
### Location:

- [Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | Irc2P | [Slack](https://monero.slack.com)
  - `#monero-dev`

### Time

Use the [timezone converter](https://www.timeanddate.com/worldclock/converter.html?iso=20170326T170000&p1=tz_gmt&p2=tz_et&p3=28&p4=111&p5=49&p6=179&p7=70&p8=224&p9=48) or the image below.

![screen shot 2017-04-02 at 12 55 12 am](https://cloud.githubusercontent.com/assets/1944293/24583063/1b7502d8-173f-11e7-9e63-d50c340aae9f.png)

### Proposed meeting items:

1. Greetings
2. Brief review of what's been completed since the previous meeting
3. Code + ticket discussion / Q & A
4. GetMonero.org redesign discussion
5. Any additional meeting items
6. Confirm next meeting date/time

Notes:
- `#kovri-dev` and `#monero-dev` will be relayed to each other through the duration of the meeting.
- Meeting log will be posted to https://getmonero.org/blog/tags/dev%20diaries

**Comment by rehrar** [comment]
Hey, I've got a couple of designs I'd like to show the everyone at the meeting. Would this be something that we can talk about briefly?

We can talk about which design is the better and get opinions from devs and core team as to important info? Or something like that. Would just like to run the designs past you all.

(for the interested, all drafts are in the album)
design 1: http://imgur.com/a/MwyxX
design 2: http://imgur.com/a/H9i3z

**Comment by DaveyJonesXMR** [comment]
@fluffypony Any new date?
