### ISSUE TITLE
After greetings , this issue is intended to request the improvement of the project documentation in the following aspects :

### ISSUE THREAD

**Issue by AAH20** [monero-project/meta#605]
After greetings , this issue is intended to request the improvement of the project documentation in the following aspects : 

 1-getmonero.org admin privileges contributors identification 

2-Creating a blog section related to all legal cases , regulations,KYCs in the most stable crypto exchange platforms 

3-Raising the public situational awareness when it comes to monero's security policies , bug bounty programs 

4-you have to find a way to get monero out of the blackbox which is always matching monero with the dark markets

Finally you have to keep an eye on ciphertrace and binance and what is happening to them recently , and provide monero's community with these updates , 

regards.

__Originally posted by @AAH20 in https://github.com/monero-project/monero/issues/7909__

**Comment by AAH20** [comment]
updates of this kind of community posts would be a good start , https://www.reddit.com/r/Monero/comments/o0sura/an_open_letter_to_the_core_team/

**Comment by scottAnselmo** [comment]
Website suggestions / PRs can be made on https://github.com/monero-project/monero-site
Anyone can PR a blog post or revise placement of Bounty link in header.
