### ISSUE TITLE
Labeling Bot

### ISSUE THREAD

**Issue by medusadigital** [monero-project/meta#62]
The Monero Core Team does not have time to lable the Issues (especially in monero-core Repo).

This increases workload for everybody and with rising complexity, neees to be changed in my view. Labeling and Filteing Issues is a powerfull tool which will help support planing and at the same time increases transparency. 

The idea has been coming up during discussions on how to enable certain people to label issues, but withiout giving them full repo access. since github does not support selective permissioning, the idea of a labeling bot came up. 

the bot could ideally be controlled via IRC or similar.

**Comment by danrmiller** [comment]
@medusadigital , the bot will label the issue in this "meta" repository if you make a comment in this form:

```
@issue-helper label:NAME_OF_LABEL
```

These are the currently supported labels:

bug
feature
improvement
question
task
blocker
critical
important
low_priority
in_progress
resolved

To start testing you and I are the authorized users the bot will listen to.

**Comment by danrmiller** [comment]
@issue-helper label:in_progress

**Comment by medusadigital** [comment]
@issue-helper label:improvement

**Comment by anonimal** [comment]
@danrmiller can you please add `proposal` https://github.com/monero-project/meta/issues/81#issuecomment-314244961 and give me authorization?

**Comment by danrmiller** [comment]
Thanks anonimal. Will roll this out shortly with the unlabelling and issue closing additions.

**Comment by anonimal** [comment]
Awesome, thanks 😄

**Comment by danrmiller** [comment]
I've switched to using https://github.com/aljungberg/cappbot which has our required features of access control lists, labeling, unlabeling, closing and re-opening issues via comments.

You no longer need to ping the @issue-helper. To add or remove a label, preface the label name with + or - on a line all by itself.
To close an issue, add the resolved or duplicate label. To re-open a closed issue, remove the resolved or duplicate tag.

For example:

+task

-in_progress

+in progress

Label Changes: By request, "proposal" and "duplicate" and "invalid" have been added,
low_priority and in_progress have been changed to "low priority" and "in progress".

The current list of labels, to be determined in https://github.com/monero-project/meta/issues/90


```
bug
feature
question
task
blocker
critical
important
low priority
in progress
resolved
proposal
duplicate
invalid
```

Please excuse this spam below so I can use the legacy bot to create the labels needed. The new bot will not add a label that doesn't already exist.


@issue-helper label:feature
@issue-helper label:blocker
@issue-helper label:critical
@issue-helper label:important
@issue-helper label:low priority
@issue-helper label:in progress
@issue-helper label:resolved

**Comment by danrmiller** [comment]
@issue-helper label:in progress

**Comment by danrmiller** [comment]
-bug
-feature
-improvement
-question
task
-blocker
-critical
-important
-low priority
in progress
-resolved
-proposal

**Comment by selsta** [comment]
Labeling bot has been replaced by Github triage user role.
