### ISSUE TITLE
Release name for 0.18

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/meta#623]
Discussion: https://forum.monero.space/d/151-what-to-name-the-next-monero-release-018

Based on [Monero's release naming convention](https://github.com/monero-project/meta/blob/master/NAMING.md), Monero's next release name will be:

`Fluorine` + Celestial Object

"Alliteration or assonance is also required, for maximum awesomeness."

What should Monero's 0.18 release be named? Fluorine what?

Possible choices include (some of which stretch the definition of Celestial Object):

* Fluorine Fornax
* Fluorine Fath
* Fluorine Firewheel
* Fluorine Firmament
* Fluorine Furnace

...or anything else you come up with!

I'll run a ranked choice poll later as I have done the last few releases following initial feedback.

**Comment by bitlamas** [comment]
Fluorine [Fornjot](https://en.wikipedia.org/wiki/Fornjot_(moon))

**Comment by hyc** [comment]
As I suggested before: Fluorine Flamingo

https://web.pa.msu.edu/people/horvatin/Astronomy_Facts/obsolete_pages/phoenicopterus.htm

Or its Latin name Phoenicopterus. Fluorine Phoenicopterus would be a pain to write out frequently tho.

**Comment by carrington1859** [comment]
For context, I suggested "Flourine Firewheel" for two reason:

1. It sounds epic.
2. "Firewheel Galaxy" seems to be a less common name for the Pinwheel Galaxy, also known as Messier 101 which is a very nice looking galaxy https://en.wikipedia.org/wiki/Pinwheel_Galaxy

I'm not actually sure if "Firewheel Galaxy" is an alternative english name, or a literal translation of the german name for Messier 101.

I think Firmament and Fornax sound nice as well

**Comment by lh1008** [comment]
`Flourine Circinus`

**Comment by erciccione** [comment]
Fluorine Firmament

**Comment by SamsungGalaxyPlayer** [comment]
Vote for your favorite release names: https://civs1.civs.us/cgi-bin/vote.pl?id=E_8dffadad37ce3e70&akey=96d937b30d8ef7d6

**Comment by pseacrest** [comment]
Firewheel all the way

**Comment by SamsungGalaxyPlayer** [comment]
Fluorine Fermi was the condorcet winner.

![image](https://user-images.githubusercontent.com/12520755/142736743-c20d89ca-01f3-4c25-af30-8f351d85cb24.png)

https://civs1.civs.us/cgi-bin/results.pl?id=E_8dffadad37ce3e70

**Comment by hyc** [comment]
Really? It doesn't even satisfy the assonance condition.

**Comment by fluffypony** [comment]
> Really? It doesn't even satisfy the assonance condition.

That's a good point, I didn't think about that. It's not *strictly* compliant.

**Comment by SamsungGalaxyPlayer** [comment]
@hyc @fluffypony it's "Alliteration ***OR*** assonance" :)

**Comment by pseacrest** [comment]
Firewheel will be next
