### ISSUE TITLE
Create formalized FFS process

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#63]
I posted a thread quite some time ago in the forum but I cannot seem to find it. 

Basically, we have a [loosely tied together sticky](https://forum.getmonero.org/7/open-tasks/2379/forum-funding-system-ffs-sticky) which should be formalized with caveats and contingencies in place. 

This issue also includes linking/placement/location for easy access (so the general public actually knows that it exists 😄), e.g., website.

**Comment by Gingeropolous** [comment]
To the githubs!

https://github.com/monero-project/meta/pull/66

**Comment by anonimal** [comment]
Referencing https://forum.getmonero.org/t/2576.

**Comment by SamsungGalaxyPlayer** [comment]
This has been done

https://ccs.getmonero.org/what-is-ccs/
https://ccs.getmonero.org/how-to-ccs/
