### ISSUE TITLE
Monero Dev Meeting; v15 network upgrade - Sat 29 January 2022 @ 17:00 UTC 

### ISSUE THREAD

**Issue by rottenwheel** [monero-project/meta#652]
Location: IRC; [libera.chat](https://libera.chat/#monero-dev) #monero-dev | [Matrix](https://matrix.to/#/#monero-dev:monero.social).

Time:
17:00 UTC. [Check in your timezone](https://www.timeanddate.com/worldclock/converter.html?iso=20220129T170000&p1=1440).

Main discussion topics:

1. Greetings.
2. [Monero v15 hard-fork](https://github.com/monero-project/meta/issues/630). (PRs to be reviewed and merged).
3. Reassess schedule for rollout.

Please chime in the comments section ahead of time if you would like to propose an agenda item, rephrase an agenda topic, or any other type of deliberation to have an effective meeting.

Chat log will be posted below after meeting has concluded.

Meeting chairperson: localmonero05.

**Comment by erciccione** [comment]
You are banned from the matrix Monero channels (and not only those) for repeated toxic behaviour, which includes homophobic statements, harassment, doxxing and repeated insults. I find quite comical that you are trying to call and chair the meeting with an alternative account. Do you really expect people to participate?

**Comment by rottenwheel** [comment]
@erciccione What happens in social media is outside of what occurs in IRC channels, XMR Workgroup Meetings, or development matters, Ciccione. I cannot, for the life of me, have a diplomatic dialogue with someone who posts in a Matrix room these supremely subjective opinions about someone else based off of social network posts.

> FFS the guy regularly posts on twitter 'speaches' from paramilitary nazi organizations, racist and anti-vaxx content. Stop enabling him.

Quote extracted from a screenshot Twitter profile @_geonic posted months ago, of which, _you_ are the author. Unfortunately, that Twitter profile has been deleted by such Monero Outreach Workgroup member.

What I personally find comical is that the same people imposing bans on IRC accounts, Matrix side, on the basis of violating libera.chat policies, believe that ban is any effective: IRC-to-IRC messages keep flowing like nothing has happened. The same people who wanted community members to flock to Matrix, are effectively and actively alienating their Matrix fellows from reading what I post using any of my IRC accounts, including @carrington1859, who has brought it up twice, to no avail from Monero Matrix moderation 'team'. Carrington has to finish the meeting from Matrix and go hit libera.monerologs.net to catch up with what has been said on IRC and be able to post full chat log after the matter, to close the issue in meta; is this a good experience for a meeting chairperson?

I have been present for all recent Monero Research Lab, Monero Events, Monero Community meetings, via IRC. I have successfully pinged zkao, h4sh3d to kick weekly #monero-swap meetings back up. I need to stay on top of Monero meetings because I am publishing [Revuo](https://localmonero.co/revuo) Issues every Sunday. Do we need to reconsider whether the Matrix ban is effective, perhaps? 

![Matrix ban reasoning](https://user-images.githubusercontent.com/92872541/151244161-89dc0d4e-e8b5-477c-982f-e5762a146ca2.png)

Yes, I expect people to participate because a week after having opened the issue, nobody besides just two or three people have voiced their opposition to me being the meeting chairperson; just three or four days before the meeting takes place, no less.

Do we really need to get lost in fighting over what X, Y, Z said, did or posted on social media in 2022? Really? The cancel culture stemming from some of you shows it colours every now and then, and it certainly rubs some people off as a childish stunt to attain clout and acceptance from the crowd; not to mention it prevents enthusiasts, developers and researchers from engaging with development and outreach matters, just because there's different perspectives; seems to me.

Let's get to work and leave the personal grudges behind, shall we? This network upgrade is much more important than any other fluff between anyone of us.

**Comment by ghost** [comment]
lmao wannabe influencer

**Comment by SamsungGalaxyPlayer** [comment]
Please use: https://github.com/monero-project/meta/issues/655

**Comment by SaltAce** [comment]
> Please use: #655

I've been waiting and excited for this meeting since it was first published in Revuo. I'm not sure why personal grduges are factoring in to why this issue was cancelled and a second issue opened? This kind of weird, last minute changes from within the community for what seems to be silly reasoning is making it harder for plebs like me who are genuinely interested to be able to readily jump in and participate. But cool. Gatekeepers gonna gatekeep, I guess.

**Comment by ghost** [comment]
> > Please use: #655
> 
> I've been waiting and excited for this meeting since it was first published in Revuo. I'm not sure why personal grduges are factoring in to why this issue was cancelled and a second issue opened? This kind of weird, last minute changes from within the community for what seems to be silly reasoning is making it harder for plebs like me who are genuinely interested to be able to readily jump in and participate. But cool. Gatekeepers gonna gatekeep, I guess.

the meeting is still at same time to discuss same topics - feel free to join
