### ISSUE TITLE
Kovri meeting: May 7th, 2017, 18:00 UTC

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#67]
### Location:
- [Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | Irc2P | [Slack](https://monero.slack.com)
  - `#kovri-dev`

### Proposed meeting items:
1. Greetings
2. Brief review of what's been completed since the previous meeting
3. More preparation for [96boards.org OpenHours showcase for Kovri / Monero](https://github.com/monero-project/meta/issues/46) (@fluffypony @danrmiller location status)
4. Status (again) of [Monero HackerOne umbrella and bounty](https://github.com/monero-project/meta/issues/39). [hackerone.com/monero](https://hackerone.com/monero) is online but we need to resolve FFS funding before inviting researchers. VRP status for all projects + bounty status
5. Open forum for https://github.com/monero-project/kovri/issues/630
6. Website status (@rehrar @bigreddmachine @alvinjoelsantos @danrmiller)
7. @EinMByte ...where is he? Github repo privilege discussion
8. Code + ticket discussion / Q & A
9. Any additional meeting items
10. Confirm next meeting date/time

Notes:
- Meeting log will be posted to https://getmonero.org/blog/tags/dev%20diaries

**Comment by anonimal** [comment]
Points moved from https://github.com/monero-project/meta/issues/61 because of no-shows.

**Comment by bigreddmachine** [comment]
Yeah... sorry about that. I should have given you a heads up. It's crunch time for me with some research stuff. I *think* I can make it to this meeting though.

**Comment by guzzijones** [comment]
On vaca this weekend. Making good progress on removing the client context global. Learning a ton about the codebase in the process and i2p.
