### ISSUE TITLE
MoneroKon 2022 Planning Meeting: Sunday 20th March 2022 @ 18:00 UTC

### ISSUE THREAD

**Issue by ajs-xmr** [monero-project/meta#673]
**Location **

- IRC: #monero-events
- Matrix: [#monero-events:monero.social](https://matrix.to/#/#monero-events:monero.social?via=matrix.org&via=monero.social) ([Instructions for joining the Matrix server](https://forum.monero.space/d/79-how-to-join-the-monero-core-team-matrix-server-web))
- Telegram: https://t.me/monerokon

**Time**: 18:00 UTC

**Agenda**:
1. Greetings
2. Update on contract for venue (midipoet/DR)
3. Graphics/design v3 (gnuteardrops)
4. CfP committee
5. Outdoor floorplan ideas
6. Exhibitor tent canopies
7. Agree next steps
8. AOB
9. Confirm next meeting time and date

Please comment on GitHub in advance of the meeting if you would like to propose an agenda item.

**Comment by michaesc** [comment]
Hello @ajs-xmr ,

Would you please add to the agenda:

- Indoor and **outdoor floorplan** ideas
- Local rental of **exhibitor tent** canopies

...to this agenda. Dankon and obrigado!
