### ISSUE TITLE
No process for Matrix room moderation

### ISSUE THREAD

**Issue by snex** [monero-project/meta#679]
The Matrix room is currently run like [this](https://www.youtube.com/watch?v=ndc3-JMVYAw). There isn't even a list of mods in order to discuss issues. In room, they hide behind a bot called Banhammer and interact with it in secret. Out of room (as in, after they ban you for disagreeing with them), there isn't even a way to get a list at all. A popular member of the community named Rottenwheel remains banned for "threatening to dox people." I have not seen any evidence of this behavior, and do not see it from him in any other room he's in. Maybe he did it, but it shouldn't be a matter of simply trusting mods on the issue. There should be open documentation with logs somewhere on every ban.

I was banned because I answered a few questions a user had about setting up a mining rig, another user named endor00 (who is apparently a mod? Or is good friends with one?) started insisting that new miners was "bad for everyone" (his words), which he later changed to "bad for the community" and finally "bad for established miners." A third user who was chatting through the bridge with some Japanese characters as his name started insulting me. For daring to argue my position, I was banned for "trolling." I have no logs to show because when you are banned from a Matrix room on Element, the room is wiped.

Regardless of whether you believe me, you shouldn't have to. There should be a full log of the incident, who issued the ban, who reviewed it upon dispute, etc etc. The current mode of operation is unacceptable.

**Comment by SamsungGalaxyPlayer** [comment]
I will look into the case and see what happened.

**Comment by snex** [comment]
I appreciate that but I don't really want this to be about me. I only list my case because it's the only detailed info I have. I want to see a transparent process. If that process sees my ban as justified, fine. But it should be auditable by anyone.

**Comment by plowsof** [comment]
We now have a mod resolutions room on matrix. I think this can be closed
