### ISSUE TITLE
Website Meeting: May 7th 2017, 19:00 UTC

### ISSUE THREAD

**Issue by rehrar** [monero-project/meta#68]
What up kids?

So, first time I've ever done one of these. Basically, the website is coming along just fine. I've worked up the wires for pretty much all of the pages. By the time of the meeting, all of the wires will be complete and ready to present to the community for feedback. 

Rather than post something on reddit or get trickles of feedback from IRC, I thought I'd just hold a little meeting for **anyone who wants to attend** to give feedback. This meeting will be held after the Kovri meeting in #monero. Without further ado, here's the agenda:

1. Who's here?
2. Presentation of Site Map and Wires
3. Questions/Clarifications (time to look over above)
4. Suggestions
5. Anything else?

I don't know how to get logs of this via bot, so I will probably just copy and format them myself, unless there's somebody who volunteers to do it. Please plan on attending and giving your feedback. :) Thanks everyone!

Rehrar

**Comment by rehrar** [comment]
Hey guys, I'm on mobile and I don't know how to edit on mobile, but for now 

1. Who's here?
2. Presentation of Site Map and Wires
3. Questions/Clarifications (time to look over above)
4. Suggestions
5. Translations
6. xmrgues1 presentation
7. Anything else?

**Comment by anonimal** [comment]
@rehrar how did this go? Are there logs anywhere?

**Comment by rehrar** [comment]
@anonimal https://monerobase.com/wiki/WebdevMeeting_2017-05-07

I think it went aight.
