### ISSUE TITLE
Abuse page is missing

### ISSUE THREAD

**Issue by JokerGermany** [monero-project/meta#683]
Because there is no abuse contact and i don't know how to reach the server admin, users of monero.social are banned from some rooms because spammers are using the server for automatically creating users and use them for spam. If this shall be changed, a admin can get in contact with me. Sorry for the inconvenience

**Comment by scottAnselmo** [comment]
IT staff appointed by Core to be in charge of monero.social is looking into this. So while an abuse contact page may not be posted soon, there are steps being taken against the spam right now.

In the interim, please notify the room admin of any spam issues if this is happening in monero-* rooms if you continue to see them in a few hours. The room admins should be able to escalate to Core's IT if needed.

**Comment by danrmiller** [comment]
I've been given your matrix contact and sent you a message there and am also checking into this report with a few others. 

Also, we'll get that abuse page and email address up.

Thanks

**Comment by nahuhh** [comment]
this issue sounds specific to matrix. 

thete is a Matrix moderation resokutions room now: https://matrix.to/#/!bISEWdLkMDtVezWkga:monero.social?via=monero.social&via=matrix.org&via=hackliberty.org

@selsta @danrmiller @plowsof

**Comment by nahuhh** [comment]
this issue sounds specific to matrix. 

there is a Matrix moderation resolutions room now: https://matrix.to/#/!bISEWdLkMDtVezWkga:monero.social?via=monero.social&via=matrix.org&via=hackliberty.org

@selsta @danrmiller @plowsof
