### ISSUE TITLE
Monero meeting: June 25th, 2017, 17:00 UTC

### ISSUE THREAD

**Issue by fluffypony** [monero-project/meta#70]
### Location:

- [Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | Irc2P | [Slack](https://monero.slack.com)
  - `#monero-dev`

### Time

Use the [timezone converter](https://www.timeanddate.com/worldclock/converter.html?iso=20170625T170000&p1=tz_gmt&p2=tz_et&p3=28&p4=111&p5=49&p6=179&p7=70&p8=224&p9=48) or the image below.

<img width="999" alt="screen shot 2017-06-11 at 7 54 21 pm" src="https://user-images.githubusercontent.com/1944293/27013211-d3f7c0de-4edf-11e7-91a1-f82278087a24.png">

### Proposed meeting items:

1. Greetings
2. Brief review of what's been completed since the previous meeting
3. Code + ticket discussion / Q & A
4. Reimagining the FFS (discussion)
5. Any additional meeting items
6. Confirm next meeting date/time

Notes:
- Given that workgroups are starting to hold their own meetings, we will no longer be relaying between channels. Please make an effort to attend all meetings relevant to you. Monero contributors should at least try attend the Kovri meeting in \#kovri-dev immediately after this one.
- Meeting log will be posted to https://getmonero.org/blog/tags/dev%20diaries

**Comment by JollyMort** [comment]
next meeting time, today?

**Comment by anonimal** [comment]
@fluffypony can you please close?

**Comment by danrmiller** [comment]
+resolved
