### ISSUE TITLE
Update GetKovri.org

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#72]
I don't know what getkovri.org is pulling from but it should be https://github.com/anonimal/kovri-site until monero-project/kovri-site is online.

**Comment by danrmiller** [comment]
That is the repo deployed to getkovri.org, origin  https://github.com/anonimal/kovri-site.git (fetch)

We aren't auto-updating during the preview period, we are still at the 740f3d1f2ddd61807db2aca8a41c5de1793eb447 from when the preview setup was requested.

**Comment by anonimal** [comment]
I wasn't sure if the backend was pulling from the old ajs repo or not. But yes, I would hope there would be some automation for pulling from HEAD on master; even if the site isn't "officially" online.

**Comment by danrmiller** [comment]
As you requested in IRC, https://getkovri.org/ has been updated from 740f3d1f2ddd61807db2aca8a41c5de1793eb447 to 67dcff9c74ca83094e5dd9124e46b0030d266736.
New required gem jekyll-multiple-languages-plugin has been installed.

**Comment by anonimal** [comment]
As agreed to in IRC, future updates will be done manually. Thanks @danrmiller. Closing.
