### ISSUE TITLE
GetKovri.net?

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#73]
Why not this domain too?

**Comment by serhack** [comment]
I purchased it. It has who is privacy too.  :D Thanks community!

**Comment by anonimal** [comment]
Thank you @serhack :+1:

**Comment by anonimal** [comment]
JFTR: getkovri.net currently redirects to getkovri.org. @ArticMine has secured kovri.org, which also redirects to getkovri.org.

We'll continue to work internally to decide how to pursue domain ownership, etc. Thanks everyone 😄

**Comment by anonimal** [comment]
^ also, reimbursement if so desired.

**Comment by serhack** [comment]
@anonimal Thanks for your work!
