### ISSUE TITLE
MoneroKon 2023 Planning Meeting: Saturday 17th September 2022 @ 18:00 UTC

### ISSUE THREAD

**Issue by umma08** [monero-project/meta#733]
**Location** 

IRC: #monero-events
Matrix: [#monero-events:monero.social](https://matrix.to/#/#monero-events:monero.social?via=matrix.org&via=monero.social) ([Instructions for joining the Matrix server](https://forum.monero.space/d/79-how-to-join-the-monero-core-team-matrix-server-web))

**Time:** 18:00 UTC

**Agenda:**

1. Greetings
2. Monero 2022 status (midipoet+DR)
3. MoneroKon 2023 status (ajs)
4. MoneroKon 2023 - [Role Pledging](https://github.com/MoneroKon/meta/issues/4)
5. MoneroKon 2023 - [Venue selection](https://github.com/MoneroKon/meta/issues/1)
6. MoneroKon 2023 - [Kanban](https://github.com/orgs/MoneroKon/projects/1)
7. AOB
8. Confirm next meeting time and date

Please comment on GitHub in advance of the meeting if you would like to propose an agenda item.

**Comment by michaesc** [comment]
I think the Telegram group is no longer active, so it should be removed from the **Location** subtitle.

**Comment by umma08** [comment]
> I think the Telegram group is no longer active, so it should be removed from the **Location** subtitle.

removed

**Comment by umma08** [comment]
Next meeting 1st October 2022

https://github.com/monero-project/meta/issues/735
