### ISSUE TITLE
Downloads on the Get.Monero site are down!

### ISSUE THREAD

**Issue by todd198132** [monero-project/meta#789]
I can't download the software I need to open my wallet! 
?
A lot of the site is giving Cloudflare error, can someone tell the mods please?

**Comment by selsta** [comment]
We are aware of the issue but only a limited amount of people have access to the website infrastructure for security reasons so I don't know when it will be fixed.

**Comment by todd198132** [comment]
Thank you, oh dear looks like I'm without my wallet for some time then as I didn't have a copy of the download stored. I wanted to get some Monero sent this morning. Thanks for the response anyhow

**Comment by selsta** [comment]
Here is a mirror that I host myself, but only use these if you know how to **verify the signature** and **check hashes**.

- CLI: https://gui.xmr.pm/files/cli/v0.18.1.2/
- GUI: https://gui.xmr.pm/v0.18.1.2.html
- Signed hashes: https://raw.githubusercontent.com/monero-project/monero-site/master/downloads/hashes.txt
- binaryFate's PGP key: https://github.com/monero-project/monero/blob/master/utils/gpg_keys/binaryfate.asc

**Comment by todd198132** [comment]
Thank you! How helpful! You are a gods send!

**Comment by plowsof** [comment]
for visibility: Site is currently offline due to work being done (OS upgrade / site dependencies and such) the Core team are aware / the ones performing the work.

**Comment by selsta** [comment]
Issue is resolved.
