### ISSUE TITLE
Community Meeting: 18 June 2017 18:30 UTC

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/meta#79]
**Location**

[Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | [Slack](https://monero.slack.com/) | Irc2P

 - `#monero`

**Time**

[Use this timezone calculator to convert UTC to your time zone](https://www.timeanddate.com/worldclock/converter.html?iso=20170618T183000&p1=tz_gmt&p2=tz_et&p3=28&p4=111&p5=49&p6=179&p7=70&p8=224&p9=48).

GMT 18:30
ICT (Bangkok) 01:30
EDT (New York) 14:30
CDT (Dallas) 13:30
PDT (San Francisco) 11:30
EEST (Bucharest) 21:30
CSET (Brussels) 20:30

**Proposed Meeting Items**

0. Introduction
1. Greetings
2. Explanation of Monero Community Values and Goals
3. Local Activity and News
4. The Kovri opportunity
5. Translations
6. Organization Announcement
7. Open Idea Sharing and Discussion
8. Confirm Next Meeting Date/Time

**Comment by anonimal** [comment]
Is there any chance we could have this after the kovri dev meeting or before the monero dev meeting? Or does everyone want to avoid having 3 meetings in a row in a single day?

**Comment by anonimal** [comment]
@SamsungGalaxyPlayer meeting log?

**Comment by SamsungGalaxyPlayer** [comment]
@anonimal dEBRUYNE is still formatting them.
