### ISSUE TITLE
Kovri: setup cubieboard 2 for testing

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#8]
@danrmiller knows the details. This includes min req for boost, a current openssl, and vastly increased swap space (probably 2gig min). cmake and gcc-4.9 have already been installed.

**Comment by danrmiller** [comment]
I think we are talking about the cubieboard 2 device.

OpenSSL: /usr/lib/arm-linux-gnueabihf/libssl.so;/usr/lib/arm-linux-gnueabihf/libcrypto.so (version "1.0.1f") 
Boost (system/thread) version: 1.62.0 is in /usr/local/lib/
Swap:      2068476

**Comment by anonimal** [comment]
Yes, I was unsure if you wanted that info public.

**Comment by anonimal** [comment]
Deps are installed and swap was setup to spec but the build is still crashing because of low memory. Can we increase swap to 3GiB?

**Comment by danrmiller** [comment]
Swap:      4194300          0    4194300

**Comment by anonimal** [comment]
Darn, gcc needs more but that's ok: I'll use clang instead (which doesn't even require the previous 2GiB swap).

We're up and running, thanks @danrmiller!

Note: fortunately, I cannot reproduce https://github.com/monero-project/kovri/issues/434.
