### ISSUE TITLE
New Kovri logo

### ISSUE THREAD

**Issue by rehrar** [monero-project/meta#80]
As discussed with anonimal at various times, it would be in our best interests to get a professionally made logo done. We can look through behance and find some people we think would be a good fit stylistically.

**Comment by anonimal** [comment]
For reference, previous logo work here: https://github.com/monero-project/kovri/issues/282

**Comment by rehrar** [comment]
Alright, so I thought that I'd ask a few questions to begin putting together a brief.

1. If you have to describe Kovri in a sentence, but you couldn't use any of the obvious words (anonymous, privacy), how would you do it? As an example, if I had to describe Google in this way, it may be something like: "A global internet platform that connects people to information."

2. What three individual words would you use to describe Kovri (you can use obvious ones this time)? Now take those three words and rank them in order of importance. By the end you should have a list of three words ranked by order of importance.

That's it for now. I'll use this as a spring board to bring some ideas.

**Comment by anonimal** [comment]
>but you couldn't use any of the obvious words 

But that's usually the intent behind describing things: to accurately say what they are or what they do - and sometimes that description is obvious.

Since we perform a finite number of objectives, do you mean to open a thesaurus and rephrase our mission statement? If that's the case, then why don't we instead refine our [existing statement](https://github.com/monero-project/kovri-docs/blob/master/end-user/FAQ.md#what-is-kovri)? Or do you simply mean to broaden our target audience?

With that said, if I had to describe Kovri in one sentence *without* using keywords, I would say something like:

*Kovri is an internet application which allows you to safely use other internet applications by concealing your geographical location by routing and encrypting your internet data.*

But this may be too vague.

>What three individual words would you use to describe Kovri (you can use obvious ones this time)? Now take those three words and rank them in order of importance. By the end you should have a list of three words ranked by order of importance.

Should "internet" be implied?

If not:

1. Internet
2. Anonymity
3. Privacy

If so:

1. Anonymity
2. Privacy
3. Network

**Comment by Gingeropolous** [comment]
Kovri gives you access to a secondary network that exists on top of the internet where all information is protected.

Private  
Protected  
Network

**Comment by rehrar** [comment]
@anonimal the idea of the first exercise is not to fine tune the original statement, but rather to come up with different imagery that may not have been thought of initially. Going with the Google (search engine) example, if we were to just say 'search engine' then that limits the images that spring to mind, but when we use more evocative imagery (like connecting people to information) it brings about all sorts of images that would not have existed before.

So yes, we're not trying to make things confusing for people, so the official statement should not be changed. This is merely an exercise for bringing new ideas (that can potentially be worked into the logo) to mind that may not have been there if we went with the obvious.

That said, good work guys so far. I appreciate you working with me here.

**Comment by anonimal** [comment]
>"A global internet platform that connects people to information."
>but when we use more evocative imagery (like connecting people to information)

I must say, that google example can be applied to countless other internet institutions (eBay, Craigslist, Slack, ...). The imagery is too vague and broad but I do understand your point.

If I said "smoke, plate-armor, spider-web" (to describe concealment, protection, and the internet), and though those images would be more enjoyable to an artist, those images are also too vague and broad to describe Kovri.

Sometimes boring specifics need to be boring specifics - but let's see what else we can come up with. Personally, I'd rather bounce ideas off the artist once one is chosen (again).

**Comment by knaccc** [comment]
Kovri makes your geographic location and internet activity invisible and untraceable using a worldwide network of privacy protecting intermediary nodes.

Unlike a VPN, there is no single point of failure that can expose your activity, and to an observer it cannot even be determined that you are using any kind of privacy enhancing network at all.

**Comment by rehrar** [comment]
Ok, next up is just a couple more questions for clarification:

1. When we think of the Kovri brand, what are some things we do NOT want to see. This can be as specific as the logo (i.e. @anonimal said that he didn't want a big K anywhere in the logo as the main focal point), or about the brand in general (i.e. if we had something against the color purple, which has implications beyond the logo).

2. Should I be expanding my focus a bit and write a brief for the Kovri brand as a whole? If you're not quite sure what I mean when I ask this question, then I am probably overthinking it. :shrimp:

**Comment by anonimal** [comment]
>When we think of the Kovri brand, what are some things we do NOT want to see. This can be as specific as the logo (i.e. @anonimal said that he didn't want a big K anywhere in the logo as the main focal point), or about the brand in general (i.e. if we had something against the color purple, which has implications beyond the logo).

I remember this being covered extensively in (at least) some of the 2016 meetings (as documented in the monero-site repo):

```bash
$ cd monero-site/ && grep -Ri "kovri logo" _posts/ | cut -d: -f1 | sort -u
_posts/2016-07-31-logs-for-the-Kovri-dev-meeting-held-on-2016-07-31.md
_posts/2016-08-28-logs-for-the-Kovri-dev-meeting-held-on-2016-08-28.md
_posts/2016-09-11-logs-for-the-Kovri-dev-meeting-held-on-2016-09-11.md
_posts/2016-09-11-overview-and-logs-for-the-dev-meeting-held-on-2016-09-11.md
_posts/2016-10-02-logs-for-the-Kovri-dev-meeting-held-on-2016-10-02.md
_posts/2016-10-16-logs-for-the-Kovri-dev-meeting-held-on-2016-10-16.md
_posts/2016-10-30-logs-for-the-Kovri-dev-meeting-held-on-2016-10-30.md
_posts/2017-06-25-logs-for-the-Kovri-dev-meeting-held-on-2017-06-25.md
```

>Should I be expanding my focus a bit and write a brief for the Kovri brand as a whole? If you're not quite sure what I mean when I ask this question, then I am probably overthinking it. 🦐

If doing so will help resolve this issue and create a better logo, sure; sounds interesting.

**Comment by anonimal** [comment]
Draft brief here https://github.com/rehrar/meta/commit/15b009565703d20a9e87dd6a2f8dc3fab0417169

**Comment by anonimal** [comment]
Moved to https://gitlab.com/kovri-project/kovri-meta/issues/5.

**Comment by anonimal** [comment]
+duplicate
