### ISSUE TITLE
Mattermost Migration

### ISSUE THREAD

**Issue by serhack** [monero-project/meta#81]
Hello,
I am a web developer and sysadmin. I'm managing about 2 servers and 3 vps for my clients. I installed some applications like gitlab and mattermost.

We are a large community and large community need a great web app in order to share every opinion, idea about monero and kovri projects.

Slack needs too much money, we are 462 users in slack; with telegram and irc gateway we can reach +1000 users.

Mattermost will be a nice alternative, I can setup it without problems. We need a vps like this https://my.hostus.us/cart.php?a=confproduct&i=0

- 6GB RAM
- 6GB vSwap
- 4 vCPU Cores (Fair Share)
- 150GB Disk Space
- 5TB Bandwidth
- 1Gbps Port (Fair Share)
- 1 x IPv4 Address
- 6 x IPv6 Addresses
- OpenVZ / Breeze Control Panel

Please share your idea, suggestions

**Comment by anonimal** [comment]
I like the idea of mattermost but have not used it myself. @LivingInformation?

**Comment by medusadigital** [comment]
@issue-helper label:question

**Comment by anonimal** [comment]
@medusadigital this is actually a proposal, not a question. @issue-helper label:proposal

**Comment by danrmiller** [comment]
-question

**Comment by erciccione** [comment]
Totally agree with this. An open source alternative is necessary, but why not riot? Mattermost is more slack-alike but we already have a channel on matrix with an irc relay and i think we can move it on a private server. I never used Mattermost, what are the potential benefits over riot?

**Comment by psine** [comment]
I agree that we could use a better communication platform, but how about a Discourse forum?  It is a forum, not chat / messaging, but I personally find forums more useful for most purposes.  It is open source and by far the slickest forum platform I've seen, much better than Reddit, imo.  In fact, it is the forum used by MatterMost itself:

https://forum.mattermost.org/

**Comment by danrmiller** [comment]
+in progress

**Comment by SamsungGalaxyPlayer** [comment]
https://taiga.getmonero.org/project/sgp-mattermost-migration/kanban

**Comment by michaesc** [comment]
It seems that all pull requests referenced by this bug report have been merged and the main idea of Mattermost integration has been implemented.

Good work, folks. Should we close this bug report now?

**Comment by erciccione** [comment]
@michaesc I would consider the migration complete once we completely got rid of slack in favour of MatterMost.

**Comment by rehrar** [comment]
Unfortunately I don't foresee the Slack will ever be 100% replaced. There are people that prefer it and will not switch over. The goal is for workgroups to use MM instead of Slack, so all planning, work, and implementation can at least be somewhat private (i.e. we control the data).

With that in mind, I think it safe to say that this issue is indeed complete for the time being.

**Comment by erciccione** [comment]
>Unfortunately I don't foresee the Slack will ever be 100% replaced. There are people that prefer it and will not switch over

Fair enough, but we should at least discourage to use it

**Comment by rehrar** [comment]
@serhack can we close this issue? :)

**Comment by serhack** [comment]
Sure @rehrar ! For everyone the mattermost instance is https://mattermost.getmonero.org
