### ISSUE TITLE
HackerOne: create eligible categories + update the report template + define bounty distribution

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#83]
As discussed in `#kovri-dev`, create categories on H1 for each monero-project umbrella repo. Example, for Kovri's alpha release, only create crypto impl + research bounty categories.

**Comment by medusadigital** [comment]
(testing labelbot)

@issue-helper label:task

**Comment by anonimal** [comment]
Referencing https://github.com/monero-project/kovri/issues/630.

**Comment by anonimal** [comment]
I think we need to finalize tiers of bounty award too. `N` XMR for `X` tier, or similar.

**Comment by fluffypony** [comment]
Re: tiers, I think we need to feel it out based on the severity of the bug reported, and going USD bounties at the time. Ideally the money we've raised lasts us a long time, maybe indefinitely.

**Comment by anonimal** [comment]
This issue can be closed once #142 is merged.
