### ISSUE TITLE
MoneroKon 2023 Planning Meeting: Saturday 10th June 2023 @ 17:00 UTC

### ISSUE THREAD

**Issue by ajs-xmr** [monero-project/meta#848]
**Location **

- IRC: #monero-events
- Matrix: [#monero-events:monero.social](https://matrix.to/#/#monero-events:monero.social?via=matrix.org&via=monero.social) ([Instructions for joining the Matrix server](https://forum.monero.space/d/79-how-to-join-the-monero-core-team-matrix-server-web))
- XMPP: [monerokon@muc.xmpp.is](xmpp:monerokon@muc.xmpp.is?join)

**Time**: 17:00 UTC

**Agenda**:
- Greetings
- Status update
- Merch Bags
- Marketing - Reddit AMA, MoneroTalk
- Re-booking venues for 2024 during PBW 
- AOB
- Confirm next meeting time and date

Please comment on GitHub in advance of the meeting if you would like to propose an agenda item.

**Comment by michaesc** [comment]
Please add to the agenda the possibility of adding Liberty Travel to the sponsor list, for their contributions of coffee and mate service.
