### ISSUE TITLE
MoneroKon 2023 Planning Meeting: Saturday 8 July 2023 @ 17:00 UTC

### ISSUE THREAD

**Issue by Dadajo1** [monero-project/meta#860]
Location 

IRC: #monero-events
Matrix: [#monero-events:monero.social](https://matrix.to/#/#monero-events:monero.social?via=matrix.org&via=monero.social) ([Instructions for joining the Matrix server](https://forum.monero.space/d/79-how-to-join-the-monero-core-team-matrix-server-web))
XMPP: [monerokon@muc.xmpp.is](xmpp:monerokon@muc.xmpp.is?join)
Time: 17:00 UTC

Agenda:

1. Greetings
2. Pending invoices (https://invoice.monerokon.com)
3. Invoice approval Process
4. Reflections MK 23
5. Video editing
6. Volunteer names for credits
7. Make MK a not for profit organization. see MAGIC (https://magicgrants.org/funds/monero/monero_fund)
8. Re-booking venues for 2024 during PBW
9. AOB

Confirm next meeting time and date
Please comment on GitHub in advance of the meeting if you would like to propose an agenda item.

**Comment by plowsof** [comment]
- sponsor adverts during streams (_only_ rinos appeared and nobody elses) - needs to be remedied for edits / next years stream.
- perks of being a top sponsor (speaking slot) where not provided to majesticbank but where requested/denied. (i am not exactly sure what was promised (an x minute speaking slot*). I would like to hear why this happened and if rino/cake wallet received these perks.

disclaimer: i did not attend monerokon 2023
- a patron told me they enquired about purchasing a badge from msvb labs and where quoted 160 euros. i kindly ask to hear msvb labs side of the story. did this happen? and how would payment have been accepted (card?monero?)
- is msvb a volunteer or a business owner profiting from the event, or both? should they receive hotel/travel reimbursements? where they selling merch at the event or giving it away? who decided on the location of the merch table? (was it in a prime location?)

**Comment by franciscom0301** [comment]
Regarding (2) I will provide an invoice with my expenses as full time volunteer during the event.

**Comment by franciscom0301** [comment]
@Dadajo1 @ajs-xmr Should we also discuss what to do with the BTC funds?

**Comment by monerobull** [comment]
> @Dadajo1 @ajs-xmr Should we also discuss what to do with the BTC funds?

I believe those were already swapped to XMR.
