### ISSUE TITLE
Win32/64: Install Inno Setup and modify buildbot's kovri nightly-build command

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#88]
```
@anonimal       pigeons: I'll open a meta issue re: ^. All we need to do now is install Inno Setup on both win machines and have buildbot output an .exe instead of .zip when passing the `-f` switch in the bash script :)
```

- Inno Setup download [here](http://www.jrsoftware.org/isdl.php#stable)
- By default, our Inno Setup scripts will currently produce the filenames `KovriSetup32.exe` or `KovriSetup64.exe` but our bash installer will rename them to commit hash + platform + arch + date if filename is unspecified. This may or may not be desirable so we may want to keep what we're doing now with buildbot (`kovri-latest-win64.exe`, etc.)
- Referencing https://github.com/monero-project/kovri/pull/673

**Comment by danrmiller** [comment]
+resolved
