### ISSUE TITLE
Bring back the Telegram relays

### ISSUE THREAD

**Issue by medusadigital** [monero-project/meta#89]
Right now the telegram releays are down due to so much advertising and scam spam due to bots. With the current bubble the problem intesified a lot.

Since the relays have shown to be great, i think it would be cool to bring them up again.

what do we need for this? 

- more mods in the telegram channels?
- do the relays need to filter links, or certain links (since its all pushed to IRC directly) ?

**Comment by selsta** [comment]
I think we can close this, there doesn't seem to be much interest for it and adding a Telegram bridge would add a lot of noise to our IRC / Matrix channel.
