### ISSUE TITLE
Onion/Garlic sites for hosted services and build/testing machines

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#9]
I believe that @fluffypony mentioned at some point *something* along these lines - but I'd like to see for certain where we stand and what the plan was exactly (I do like the idea very much :+1:).

Referencing https://github.com/monero-project/kovri/issues/46 and https://github.com/monero-project/kovri/issues/90.

**Comment by danrmiller** [comment]
We have i2p and tor services pointed to the buildbot web interface and the gitlab mirror, but I was holding off adding the rewrite rules to the web server until we get everything on a new box. But I can go ahead and do that and we'll just move everything later.

But this is the first I heard about i2p/tor access to the build and test machines, but I don't see why we can't set that up for the contributors who already access these machines.

**Comment by anonimal** [comment]
Re: build machines, an onion service would greatly reduce the knowledge-set of exits; which I think would be a good thing. Unless anyone else plans to use an I2P tunnel, I will personally stick to an onion service because speed and flexibility is more of a priority than security for me (in terms of keeping up with the builds and run-time testing) but I support any decision that's made.

**Comment by anonimal** [comment]
All build machines (except windows) are now accessible via onion service. Thank you @danrmiller !!! 🎉 👍 😂

Note: buildbot login now has fixed rewrite rules so i2p login is possible. Another thanks to @danrmiller.

**Comment by danrmiller** [comment]
I've got the windows machines and arm testing machines ready for you

**Comment by anonimal** [comment]
Windows and ARM onions are working 😂 This resolves the build/test portion. @danrmiller  is this issue resolved?

**Comment by danrmiller** [comment]
Yes, resolved.

**Comment by anonimal** [comment]
I'm reopening until monero-project/kovri#46 and monero-project/kovri#90 are *both* resolved. monero-project/kovri#46 may take a long while to resolve though, just FYI.

**Comment by anonimal** [comment]
@danrmiller I'll rename the issue once it's down to resolving monero-project/kovri#46 and the Monero website.

**Comment by anonimal** [comment]
@danrmiller http://monero-repo.i2p redirects to https://monero-repo.i2p/users/sign_in (failed browser expectations ensue).

**Comment by danrmiller** [comment]
Sign-ins won't be enabled on this read-only mirror, if you want to browse use 
http://monero-repo.i2p/monero-project

I'll fix it so via i2p http://monero-repo.i2p/ goes to http://monero-repo.i2p/monero-project/ or something and let you know, but can't look at it today.

**Comment by anonimal** [comment]
Ok, thanks. I didn't think to login, I was mostly complaining about the https redirect but this can work too.

I'm trying to git over http but the site appears offline. Can you please give me a ping when it's back online?

**Comment by danrmiller** [comment]
OK I restarted i2p and it seems back. This was the error:
CRIT  [uterWatchdog] 2p.router.tasks.RouterWatchdog: Router appears hung, or there is severe network congestion.  Watchdog starts barking!

One day we'll use kovri.

**Comment by anonimal** [comment]
That java I2P error is not uncommon and is usually just a temporary issue. We actually *can* use kovri now but I won't push to use it.

I'm now getting `500` and `504` responses when trying to git over http. The site looks offline again after the first `500`.

**Comment by danrmiller** [comment]
I left you some messages on IRC. The i2p link is slow; something times out along the way, I've tried adjusting load balancer http buffer sizes and various other things time out. Maybe we'll change the tunnel and use ssh for git instead, and I'll try a few other things.

**Comment by danrmiller** [comment]
We no longer use this buildot system for years, this can be closed
