### ISSUE TITLE
Define Labels for Meta repository

### ISSUE THREAD

**Issue by medusadigital** [monero-project/meta#90]
Since the Labelbot (https://github.com/monero-project/meta/issues/62) will probably be able to hadle different labels in each repo, i personally think the meta repository should have its own usefull labels. 

A list of possible Labels should e created.

@issue-helper label:task

**Comment by sanecito** [comment]
Labels that should exist:

- Infrastructure
- Meeting

**Comment by sanecito** [comment]
Also another:
- Discussion

**Comment by SamsungGalaxyPlayer** [comment]
Revisiting this. I think there are two main ways to divide the labels based on how this meta has been used the last several years:

* Type
  * Infrastructure
  * Meeting
  * Discussion
* Workgroup (if relevant)
  * Community
  * MRL
  * Dev
  * (etc)

**Comment by plowsof** [comment]
a call for adding a "Discussion" label to relevant issues and gathering people for a community meeting / or a specific 'meta meeting' to resolve them them has been made.

**Comment by nahuhh** [comment]
> Revisiting this. I think there are two main ways to divide the labels based on how this meta has been used the last several years:
> 
> * Type
>   * Infrastructure
>   * Meeting
>   * Discussion
> * Workgroup (if relevant)
>   * Community
>   * MRL
>   * Dev
>   * (etc)

@selsta

**Comment by selsta** [comment]
Done.
