### ISSUE TITLE
Kovri meeting: July 23rd, 2017, 18:00 UTC

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#91]
### Location:
- [Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | Irc2P | [Slack](https://monero.slack.com)
  - `#kovri-dev`

### Proposed meeting items:
1. Greetings
2. Brief review of what's been completed since the previous meeting
3. Contributor FFS check-in / status
4. Meta Issue #27 : Where should we officially host the IRC server?
5. Open Meta issue review https://github.com/monero-project/meta/issues
6. Code + ticket discussion / Q & A
7. Any additional meeting items
8. Confirm next meeting date/time

Notes:
- Meeting log will be posted to https://getmonero.org/blog/tags/dev%20diaries

**Comment by alvinjoelsantos** [comment]
Meta Issue #27 : Where should we officially host the IRC server?

**Comment by anonimal** [comment]
Thanks @alvinjoelsantos, item has been added.
