### ISSUE TITLE
Build: add doxygen build step for Kovri

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#94]
So issues like https://github.com/monero-project/kovri/pull/677 are caught sooner and https://github.com/monero-project/kovri-site/issues/5 runs smoothly. The buildbot step would run our Doxygen build option with a simple `make doxygen`.

**Comment by anonimal** [comment]
Note: if resources are a concern, we could simply apply this step to the Linux x86-64 builder.

**Comment by danrmiller** [comment]
Ready to go on the static nightly builds once https://github.com/monero-project/kovri/pull/677 is merged. I'll wait to PR the buildbot config until after @luigi1111 merges #93

**Comment by anonimal** [comment]
https://github.com/monero-project/kovri/pull/677 has been merged. Thank you so much @danrmiller.

>I'll wait to PR the buildbot config until after @luigi1111 merges #93

Just a git FYI if it helps, if you approve of #93, there's also the option of basing a topic branch off of my remote and then PR'ing your changes before @luigi1111 merges #93 (the PR would include my commits but that's ok since they will be merged anyway, assuming @luigi1111 approves).

**Comment by danrmiller** [comment]
+resolved
